# Generated by Django 3.0.7 on 2020-08-07 18:28

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('vendor', '0017_DateTimeField_instead_of_DateField'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationIntegration',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.UUIDField(default=uuid.uuid4)),
                ('authentication', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'organization_vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='integrations',
                        to='vendor.OrganizationVendor',
                    ),
                ),
            ],
        ),
    ]
