# Generated by Django 3.0.7 on 2020-08-20 17:28

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vendor', '0017_DateTimeField_instead_of_DateField'),
        ('organization', '0007_DateTimeField_instead_of_DateField'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionAccount',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=100)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('already_exists', 'Already Exists'),
                            ('success', 'Success'),
                            ('error', 'Error'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('control', models.UUIDField(default=uuid.uuid4)),
                ('authentication', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.TextField()),
                (
                    'metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor'
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationIntegration',
        ),
        migrations.AddField(
            model_name='connectionaccount',
            name='integration',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='connection_accounts',
                to='integration.Integration',
            ),
        ),
        migrations.AddField(
            model_name='connectionaccount',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='connection_accounts',
                to='organization.Organization',
            ),
        ),
    ]
