# Generated by Django 3.0.7 on 2020-09-08 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0002_integration_and_connection_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='connectionaccount',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='connected_integrations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
