# Generated by Django 3.0.7 on 2020-10-16 22:20

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0003_connection_account_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={
                'ordering': [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F('metadata'),
                        descending=True,
                        nulls_last=True,
                    )
                ]
            },
        ),
    ]
