# Generated by Django 3.1.2 on 2020-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0004_adding_ordering_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='authentication',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='integration',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
