# Generated by Django 3.1.2 on 2020-11-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0005_migrate_json_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionResponseHistory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                (
                    'connection_account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='response_history',
                        to='integration.connectionaccount',
                    ),
                ),
            ],
        ),
    ]
