# Generated by Django 3.1.2 on 2020-12-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0007_add_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Unknown'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                ],
                default='000',
                max_length=20,
            ),
        ),
    ]
