# Generated by Django 3.1.2 on 2020-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0008_connectionaccount_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionaccount',
            name='configuration_state',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
