# Generated by Django 3.1.2 on 2020-12-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0015_laikaobject_is_manually_created'),
        ('integration', '0009_connectionaccount_configuration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionresponsehistory',
            name='laika_object',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='objects.laikaobject',
            ),
        ),
    ]
