# Generated by Django 3.1.2 on 2021-01-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0011_connectionaccount_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('sync', 'Sync'),
                    ('already_exists', 'Already Exists'),
                    ('success', 'Success'),
                    ('error', 'Error'),
                    ('setup_complete', 'Setup Complete'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
