# Generated by Django 3.1.2 on 2021-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0012_connectionaccount_new_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Unknown'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                ],
                default='000',
                max_length=20,
            ),
        ),
    ]
