# Generated by Django 3.1.2 on 2021-03-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0014_adding_aws_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Unknown'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                    ('007', 'AWS error'),
                    ('008', 'Expired account'),
                ],
                default='000',
                max_length=20,
            ),
        ),
    ]
