# Generated by Django 3.1.2 on 2021-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0015_add_account_expired_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='category',
            field=models.CharField(
                choices=[
                    ('business_suites', 'Business Suites'),
                    ('developer_tools', 'Developer Tools'),
                    ('monitoring_logging', 'Monitoring Logging'),
                    ('project_management', 'Project Management'),
                    ('it_device_management', 'IT Device Management'),
                    ('payroll', 'Payroll'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=36,
            ),
        ),
    ]
