# Generated by Django 3.1.6 on 2021-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0017_add_azure_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='category',
            field=models.CharField(
                choices=[
                    ('business_suites', 'Business Suites'),
                    ('cloud_service_providers', 'Cloud Service Providers'),
                    ('developer_tools', 'Developer Tools'),
                    ('monitoring_logging', 'Monitoring Logging'),
                    ('project_management', 'Project Management'),
                    ('it_device_management', 'IT Device Management'),
                    ('payroll', 'Payroll'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=36,
            ),
        ),
    ]
