# Generated by Django 3.1.12 on 2021-07-13 21:18

from django.db import migrations, models

import integration.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0021_add_result_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='email_logo',
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                storage=laika.storage.PublicMediaStorage(),
                upload_to=integration.models.integration_email_logo_directory_path,
                validators=[integration.models.validate_email_logo_extension],
            ),
        ),
    ]
