# Generated by Django 3.1.12 on 2021-07-19 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0023_connection_account_unique_alias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectionaccount',
            unique_together=set(),
        ),
    ]
