# Generated by Django 3.1.12 on 2021-07-28 21:51
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_payroll_feature_flags(apps, schema_editor):
    flag_model = apps.get_model('feature', 'Flag')
    payroll_flag = flag_model.objects.filter(name='payrollIntegrationsFeatureFlag')
    logger.info(f'Deleting {payroll_flag.count()} payroll feature flags!')
    payroll_flag.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0024_unique_together_connection'),
    ]

    operations = [migrations.RunPython(delete_payroll_feature_flags)]
