# Generated by Django 3.1.12 on 2021-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0025_delete_payroll_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Unknown'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                    ('007', 'AWS error'),
                    ('008', 'Expired account'),
                    ('009', 'Azure error'),
                    ('010', 'Google Cloud (GCP) error'),
                    ('011', 'Provider Server Error'),
                    ('012', 'Resource not found'),
                ],
                default='000',
                max_length=20,
            ),
        ),
    ]
