# Generated by Django 3.1.12 on 2021-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0027_add_api_limit_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionaccount',
            name='send_mail_error',
            field=models.BooleanField(default=True),
        ),
    ]
