# Generated by Django 3.1.12 on 2021-09-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0030_add_provider_graphql_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='connected_integrations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
