# Generated by Django 3.1.12 on 2021-09-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0031_connection_account_created_by_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
