# Generated by Django 3.1.12 on 2021-09-22 21:51
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_csp_and_monitor_feature_flag(apps, schema_editor):
    flag_model = apps.get_model('feature', 'Flag')
    flags = [
        'awsIntegrationFeatureFlag',
        'azureIntegrationFeatureFlag',
        'gcpIntegrationFeatureFlag',
        'monitorsFeatureFlag',
    ]
    csp_and_monitor_flags = flag_model.objects.filter(name__in=flags)
    logger.info(
        f'Deleting {csp_and_monitor_flags.count()} csp and monitor feature flags!'
    )
    csp_and_monitor_flags.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0033_migrate_clubhouse_connections'),
    ]

    operations = [migrations.RunPython(delete_csp_and_monitor_feature_flag)]
