# Generated by Django 3.1.12 on 2021-11-23 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vendor', '0024_add_number_of_users_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0038_add_field_reason_error_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVendorUserSSO',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('status', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'connection_account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vendor_users_sso',
                        to='integration.connectionaccount',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sso_user',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sso_users',
                        to='vendor.organizationvendor',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='organizationvendorusersso',
            constraint=models.UniqueConstraint(
                fields=('email', 'vendor', 'connection_account'),
                name='email_vendor_connection_account',
            ),
        ),
    ]
