# Generated by Django 3.1.12 on 2021-12-15 20:46

from django.db import migrations, models

from integration import error_codes

DEFAULT_ERROR_CODES = [
    error_codes.INSUFFICIENT_PERMISSIONS,
    error_codes.BAD_CLIENT_CREDENTIALS,
]


def allow_send_email_error_codes(apps, schema_editor):
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')
    for code in DEFAULT_ERROR_CODES:
        error_updated, _ = error_catalogue_model.objects.update_or_create(
            code=code, defaults={'send_email': True}
        )


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0039_add_integration_organization_vendor_user_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcatalogue',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(allow_send_email_error_codes),
    ]
