# Generated by Django 3.1.12 on 2022-03-07 17:22
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def remove_never_frequency(apps, _):
    connection_account_model = apps.get_model('integration', 'ConnectionAccount')
    connection_accounts = connection_account_model.objects.filter(
        configuration_state__frequency='never'
    )
    logger.info(
        f'{connection_accounts.count()} connection accounts with NEVER '
        'value configuration state'
    )
    for ca in connection_accounts:
        if ca.configuration_state.get('frequency'):
            del ca.configuration_state['frequency']
            ca.save()
            logger.info(f'removing NEVER from connection account: {ca.id}')


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0049_add_bad_gateway_error_code'),
    ]

    operations = [migrations.RunPython(remove_never_frequency)]
