# Generated by Django 3.1.12 on 2022-03-10 14:45

from django.db import migrations

from integration.error_codes import DENIAL_OF_CONSENT


def add_wizard_message_to_denial_of_consent(apps, _):
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')
    error_catalogue_model.objects.filter(code=DENIAL_OF_CONSENT).update(
        default_wizard_message='<p>The connection request was denied by the user.</p>'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0050_remove_never_frequency'),
    ]

    operations = [migrations.RunPython(add_wizard_message_to_denial_of_consent)]
