# Generated by Django 3.2.12 on 2022-04-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0052_delete_objects_on_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionresponsehistory',
            name='object_data_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
