# Generated by Django 3.2.13 on 2022-06-10 14:00

import django.db.models.deletion
from django.db import migrations, models


def add_initial_version_for_integrations(apps, _):
    integration_model = apps.get_model('integration', 'Integration')
    integration_version_model = apps.get_model('integration', 'IntegrationVersion')
    integrations = integration_model.objects.all()
    for integration in integrations:
        version_metadata = integration.metadata if integration.metadata else {}
        version_metadata['permissions'] = []
        initial_version = integration_version_model.objects.create(
            version_number='1.0.0',
            description='Initial Version',
            metadata=version_metadata,
            integration=integration,
        )
        for connection in integration.connection_accounts.all():
            connection.integration_version = initial_version
            connection.save()


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0053_object_data_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationVersion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('version_number', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'integration',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='integration.integration',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='connectionaccount',
            name='integration_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='connection_accounts',
                to='integration.integrationversion',
            ),
        ),
        migrations.RunPython(add_initial_version_for_integrations),
    ]
