# Generated by Django 3.2.13 on 2022-07-18 18:14

from django.db import migrations

from integration.models import IntegrationVersion

DEVICE_SCOPE = 'https://graph.microsoft.com/Device.Read.All'
PERMISSIONS = {
    "human-readable": [
        "Read audit log data",
        "Read directory data, such as users, groups, devices and apps",
        "Read group memberships",
        "Maintain access to data you have given it access to",
        "Read all users full profiles",
    ],
    "granular-permissions": [
        "AuditLog.Read.All",
        "Directory.Read.All",
        "GroupMember.Read.All",
        "offline_access",
        "User.Read.All",
    ],
    "type": "Read Only",
}


def update_permission_description_for_microsoft_365(apps, _):
    integration_version_model: IntegrationVersion = apps.get_model(
        'integration', 'IntegrationVersion'
    )
    first_integration_version = integration_version_model.objects.filter(
        integration__vendor__name='Microsoft 365', version_number='1.0.0'
    ).first()
    if first_integration_version:
        first_integration_version.metadata['permissions'] = PERMISSIONS
        first_integration_version.save()


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0055_add_integration_permissions'),
    ]

    operations = [migrations.RunPython(update_permission_description_for_microsoft_365)]
