# Generated by Django 3.2.13 on 2022-07-18 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0056_update_microsoft365_permissions_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionResponseHistory',
        ),
    ]
