# Generated by Django 3.2.15 on 2022-08-25 19:31
import logging

from django.db import migrations

from integration.error_codes import USER_INPUT_ERROR

logger = logging.getLogger(__name__)

NEW_ERROR_CODE = {
    'wizard_error_code': '002',
    'wizard_message': (
        'The provided object ID is incorrect. Please enter the correct value and try'
        ' again.'
    ),
}


def add_azure_object_id_alert(apps, _):
    integration_model = apps.get_model('integration', 'Integration')
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')
    try:
        integration = integration_model.objects.get(
            vendor__name__iexact='Microsoft Azure'
        )
        error = error_catalogue_model.objects.get(code=USER_INPUT_ERROR)
        NEW_ERROR_CODE.update({'error': error})
        integration.alerts.create(**NEW_ERROR_CODE)
    except integration_model.DoesNotExist:
        logger.info(f'The integration called Microsoft Azure not exist to add alerts')


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0058_add_new_github_apps_wizard_error_message'),
    ]

    operations = [migrations.RunPython(add_azure_object_id_alert)]
