# Generated by Django 3.2.15 on 2022-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0059_add_azure_object_id_integration_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Other'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                    ('007', 'Expired Token'),
                    ('011', 'Provider Server Error'),
                    ('012', 'Resource not found'),
                    ('013', 'API call exceeded rate limit due to too many requests'),
                    ('014', 'Github App is not installed on the organization'),
                    ('015', 'Provider Graphql API Error'),
                    ('016', 'Connection Time Out'),
                    ('017', 'Default GraphQL Error'),
                    ('018', 'Access Revoked'),
                    ('019', 'The user entered an invalid value'),
                    ('020', 'Gateway Timeout'),
                    ('008', 'Bad Gateway'),
                    ('021', 'Bad request syntax or unsupported method'),
                ],
                default='000',
                max_length=20,
            ),
        ),
    ]
