# Generated by Django 3.2.15 on 2022-10-27 19:49
import logging

from django.db import migrations

from integration.error_codes import INSUFFICIENT_PERMISSIONS

logger = logging.getLogger(__name__)


NEW_ERROR_CODE = {
    'wizard_error_code': '001',
    'wizard_message': 'Administrator privileges are required to integrate with Linear',
}


def add_administrator_privileges_required_error_code(apps, _):
    integration_model = apps.get_model('integration', 'Integration')
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')

    integration = integration_model.objects.filter(
        vendor__name__iexact='Linear'
    ).first()
    error = error_catalogue_model.objects.get(code=INSUFFICIENT_PERMISSIONS)

    if integration:
        integration.alerts.create(**NEW_ERROR_CODE, error=error)
    else:
        logger.info(f'The integration called Linear not exist to add alerts')


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0065_add_is_not_admin_integration_alert_for_jamf'),
    ]

    operations = [
        migrations.RunPython(add_administrator_privileges_required_error_code)
    ]
