# Generated by Django 3.2.15 on 2022-12-01 02:33

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0068_decrypt_github_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionAccountDebugAction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                (
                    'description',
                    tinymce.models.HTMLField(blank=True, default='', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='connectionaccount',
            name='debug_status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='connection_accounts',
                to='integration.connectionaccountdebugaction',
            ),
        ),
    ]
