# Generated by Django 3.2.15 on 2022-11-30 23:26

from django.db import migrations

ACTIONS = [
    {
        'name': 'Pending Laika Action',
        'status': 'LAIKA_ACTION_REQUIRED',
        'description': (
            '<p>Sit tight! The Laika Support Team is currently working to remediate'
            ' your connection account.<br><strong>This issue will be resolved in 24'
            ' hours.</strong></p>'
        ),
    },
    {
        'name': 'Pending Investigation',
        'status': 'UNDER_INVESTIGATION',
        'description': (
            'Sit tight! The Laika Support Team is currently reviewing this error. A'
            ' notification will be sent if action is required.'
        ),
    },
]


def add_debug_action_status(apps, _):
    connection_account_debug_action_model = apps.get_model(
        'integration', 'ConnectionAccountDebugAction'
    )
    for action in ACTIONS:
        connection_account_debug_action_model.objects.create(**action)


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0069_add_connection_account_debug_action'),
    ]

    operations = [migrations.RunPython(add_debug_action_status)]
