# Generated by Django 3.1.2 on 2021-05-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
        ('fieldwork', '0001_create_fieldwork_base_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_internal_comment', models.BooleanField(default=False)),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evidence_comments',
                        to='comment.comment',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evidence_comments',
                        to='fieldwork.evidence',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='comments',
            field=models.ManyToManyField(
                related_name='evidence',
                through='fieldwork.EvidenceComment',
                to='comment.Comment',
            ),
        ),
    ]
