# Generated by Django 3.1.6 on 2021-05-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0002_create_evidence_comment_moodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchlogic',
            name='evidence',
        ),
        migrations.AddField(
            model_name='fetchlogic',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='EvidenceFetchLogic',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ev_fetch_logic',
                        to='fieldwork.evidence',
                    ),
                ),
                (
                    'fetch_logic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ev_fetch_logic',
                        to='fieldwork.fetchlogic',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='fetch_logic',
            field=models.ManyToManyField(
                related_name='evidence',
                through='fieldwork.EvidenceFetchLogic',
                to='fieldwork.FetchLogic',
            ),
        ),
    ]
