# Generated by Django 3.1.6 on 2021-05-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0015_add_alerts_perms_to_groups'),
        ('fieldwork', '0003_update_fetch_logic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchlogic',
            name='audit',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fetch_logic',
                to='audit.audit',
            ),
        ),
    ]
