# Generated by Django 3.1.6 on 2021-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0004_add_fetch_logic_model_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_laika_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
