# Generated by Django 3.1.2 on 2021-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0006_create_evidence_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
