# Generated by Django 3.1.2 on 2021-06-03 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import fieldwork.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0007_evidence_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=fieldwork.models.attachment_upload_directory,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('POLICY', 'Policy'),
                            ('LEGACY_DOCUMENT', 'Legacy Document'),
                            ('FILE', 'File'),
                            ('TEAM', 'Team'),
                            ('OFFICER', 'Officer'),
                            ('LINK', 'Link'),
                            ('LAIKA_PAPER', 'Laika Paper'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attachment',
                        to='fieldwork.evidence',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='EvidenceAttachment',
        ),
    ]
