# Generated by Django 3.1.2 on 2021-06-03 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0008_add_attachment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
    ]
