# Generated by Django 3.1.6 on 2021-06-07 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0009_remove_attachment_type'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE codename = 'bulk_review_evidence'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.user_user_user_permissions
                WHERE permission_id in
                (
                  SELECT id FROM public.auth_permission
                  WHERE codename = 'bulk_review_evidence' 
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_permission
                WHERE codename = 'bulk_review_evidence';
                COMMIT;
            ''',
            reverse_sql='',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE codename = 'review_evidence'
                )
                AND group_id in (
                  SELECT g.id FROM public.auth_group g
                  WHERE g.name ilike '%_admin'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
    ]
