# Generated by Django 3.1.6 on 2021-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0010_update_review_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
