# Generated by Django 3.1.6 on 2021-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0011_add_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
