# Generated by Django 3.1.12 on 2021-07-13 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0013_add_evidence_comments_permissions'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
                update fieldwork_evidence fe1
                set display_id = (select concat('ER-', split_part(fe.display_id, 'EV-', 2)) new_id
                from fieldwork_evidence fe
                where fe.id = fe1.id);
            COMMIT;
        '''
        )
    ]
