# Generated by Django 3.1.12 on 2021-07-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0015_add_can_see_fieldwork_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='from_fetch',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
