# Generated by Django 3.1.12 on 2021-07-22 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import fieldwork.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0014_policy_is_visible_in_dataroom'),
        ('audit', '0019_audit_auto_fetch_run'),
        ('fieldwork', '0016_add_from_fetch_to_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalAttachment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=fieldwork.models.tmp_attachment_upload_directory,
                    ),
                ),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_tmp_attachment',
                        to='audit.audit',
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy',
                        to='policy.policy',
                    ),
                ),
            ],
        ),
    ]
