# Generated by Django 3.1.12 on 2021-08-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0026_add_one_to_one_relationship_with_link'),
        ('training', '0015_training_roles_update_default_value'),
        ('fieldwork', '0017_add_temporalattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalattachment',
            name='document',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='document',
                to='evidence.evidence',
            ),
        ),
        migrations.AddField(
            model_name='temporalattachment',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='temporalattachment',
            name='training',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='training',
                to='training.training',
            ),
        ),
    ]
