# Generated by Django 3.1.12 on 2021-08-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0050_add_unaccent_extension'),
        ('fieldwork', '0018_add_logic_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalattachment',
            name='is_officer_log',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='temporalattachment',
            name='team',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='team',
                to='user.team',
            ),
        ),
    ]
