# Generated by Django 3.1.12 on 2021-08-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0007_update_regex_field'),
        ('fieldwork', '0019_add_fields_tmp_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaaudittype',
            name='criteria',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='criteria_audit_types',
                to='fieldwork.criteria',
            ),
        ),
        migrations.AlterField(
            model_name='criteriaaudittype',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='certification.certification',
            ),
        ),
    ]
