# Generated by Django 3.1.12 on 2021-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0020_update_criteria_audit_type_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchlogic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
