# Generated by Django 3.1.12 on 2021-08-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0021_add_description_to_fetchlogic'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalattachment',
            name='is_vendor_log',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
