# Generated by Django 3.1.12 on 2021-08-25 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0025_add_view_attachment_permission'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                    INSERT into
                        public.auth_group_permissions (group_id, permission_id) (
                        SELECT
                            g.id AS group_id, p.id AS permission_id 
                        FROM
                            public.auth_group g 
                            cross join
                            public.auth_permission p 
                        WHERE
                            (
                            g.name = 'auditor' or g.name = 'auditor_admin'
                            )
                            AND p.codename = ANY (array [
                            'view_requirement',
                            'delete_requirement'
                            ]
                            )
                        )
                    ON CONFLICT DO NOTHING;
                    COMMIT;
              '''
        )
    ]
