# Generated by Django 3.1.12 on 2021-08-26 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0026_assign_requirement_permission_to_auditor'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                    BEGIN;
                    INSERT into
                       public.auth_group_permissions (group_id, 
                       permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE g.name != 'auditor_admin' AND g.name ilike 
                       '%_admin'
                          AND p.codename = 'view_fieldwork'
                        )
                    ON CONFLICT DO NOTHING;
                    COMMIT;
                '''
        ),
    ]
