# Generated by Django 3.1.12 on 2021-08-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0027_add_see_fieldwork_permission_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporalattachment',
            name='is_officer_log',
        ),
        migrations.RemoveField(
            model_name='temporalattachment',
            name='is_vendor_log',
        ),
        migrations.AddField(
            model_name='temporalattachment',
            name='fetch_logic',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fl_tmp_attachment',
                to='fieldwork.fetchlogic',
            ),
        ),
    ]
