# Generated by Django 3.1.12 on 2021-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0028_update_tmp_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
