# Generated by Django 3.1.12 on 2021-09-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
        ('fieldwork', '0031_create_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='requirement_comments',
                        to='comment.comment',
                    ),
                ),
                (
                    'requirement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='requirement_comments',
                        to='fieldwork.requirement',
                    ),
                ),
            ],
        ),
    ]
