# Generated by Django 3.1.6 on 2021-07-06 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0033_add_requirement_comment_permissions'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike 'auditor_admin' 
                  )
                  AND p.codename = ANY (array [
                    'add_requirementcomment',
                    'delete_requirementcomment',
                    'change_requirementcomment',
                    'view_requirementcomment' ]
                    )
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        )
    ]
