# Generated by Django 3.1.12 on 2021-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0037_add_test_result_empty_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='times_moved_back_to_open',
            field=models.IntegerField(default=0),
        ),
    ]
