# Generated by Django 3.1.12 on 2021-10-21 20:48

from django.db import migrations

from user.constants import AUDITOR, AUDITOR_ADMIN


def add_pool_value_all_evidence_comments(apps, schema_editor):
    evidence_comments = apps.get_model('fieldwork', 'EvidenceComment')
    for ev_comment in evidence_comments.objects.all():
        if not ev_comment.is_internal_comment or ev_comment.comment.owner is None:
            ev_comment.pool = 'all'
        else:
            if ev_comment.comment.owner.role in [AUDITOR, AUDITOR_ADMIN]:
                ev_comment.pool = 'lcl'
            else:
                ev_comment.pool = 'laika'
        ev_comment.save()


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0039_add_pool_field_to_evidence_comment_model'),
    ]

    operations = [
        migrations.RunPython(add_pool_value_all_evidence_comments),
    ]
