# Generated by Django 3.1.12 on 2021-11-11 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0040_infer_pool_value_evidence_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='tester',
        ),
    ]
