# Generated by Django 3.1.12 on 2021-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0041_remove_tester_reviewer_from_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='exclude_in_report',
            field=models.BooleanField(default=False),
        ),
    ]
