# Generated by Django 3.1.12 on 2021-11-18 00:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0042_requirement_exclude_in_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceStatusTransition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'from_status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('submitted', 'Submitted'),
                            ('auditor_accepted', 'Auditor Accepted'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'to_status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('submitted', 'Submitted'),
                            ('auditor_accepted', 'Auditor Accepted'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status_transitions',
                        to='fieldwork.evidence',
                    ),
                ),
            ],
        ),
    ]
