# Generated by Django 3.1.12 on 2021-11-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0043_create_evidence_status_transition_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_fetch_logic_accurate',
            field=models.BooleanField(default=False),
        ),
    ]
