# Generated by Django 3.1.12 on 2022-01-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0044_evidence_is_fetch_logic_accurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='run_account_lo_fetch',
            field=models.CharField(
                choices=[('run', 'run'), ('skip', 'skip'), ('still_run', 'still_run')],
                default='run',
                max_length=50,
            ),
        ),
    ]
