# Generated by Django 3.1.12 on 2022-02-08 22:45

import django.db.models.deletion
from django.db import migrations, models

from fieldwork.constants import EVIDENCE_STATUS


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0004_add_population_feature_flag'),
        ('fieldwork', '0045_evidence_run_account_lo_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sample',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attachments',
                to='population.sample',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='er_type',
            field=models.CharField(
                choices=[
                    ('evidence_request', 'evidence_request'),
                    ('sample_er', 'sample_er'),
                ],
                default='er',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(
                choices=EVIDENCE_STATUS, default='open', max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='evidencestatustransition',
            name='from_status',
            field=models.CharField(choices=EVIDENCE_STATUS, max_length=50),
        ),
        migrations.AlterField(
            model_name='evidencestatustransition',
            name='to_status',
            field=models.CharField(choices=EVIDENCE_STATUS, max_length=50),
        ),
    ]
