# Generated by Django 3.1.12 on 2022-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0046_sample_ers_model_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='er_type',
            field=models.CharField(
                choices=[
                    ('evidence_request', 'evidence_request'),
                    ('sample_er', 'sample_er'),
                ],
                default='evidence_request',
                max_length=50,
            ),
        ),
    ]
