# Generated by Django 3.1.12 on 2022-03-09 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0047_sample_ers_model_type_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name_plural': 'Evidence Request'},
        ),
    ]
