# Generated by Django 3.1.12 on 2022-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0048_evidence_verbose_name_plural_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
