# Generated by Django 3.2.12 on 2022-03-29 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0049_adding_is_deleted_field_to_test_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criteriarequirement',
            unique_together={('criteria', 'requirement')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementevidence',
            unique_together={('evidence', 'requirement')},
        ),
    ]
