# Generated by Django 3.2.12 on 2022-03-31 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0047_override_export_file'),
        ('fieldwork', '0050_contraints_criteriarequirement_requirementevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='audit',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='criteria',
                to='audit.audit',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together={('display_id', 'audit')},
        ),
    ]
