# Generated by Django 3.2.13 on 2022-06-02 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0053_fill_er_attachments_has_been_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceMetric',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrations_counter', models.JSONField(blank=True, null=True)),
                ('monitors_count', models.IntegerField(default=0)),
                (
                    'evidence_request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='metrics',
                        to='fieldwork.evidence',
                    ),
                ),
            ],
        ),
    ]
