# Generated by Django 3.2.13 on 2022-06-10 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fieldwork', '0054_create_evidence_request_metrics_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='reviewer_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tester_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='times_moved_back_to_open',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequirementStatusTransition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'from_status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('under_review', 'Under Review'),
                            ('completed', 'Completed'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'to_status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('under_review', 'Under Review'),
                            ('completed', 'Completed'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'requirement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status_transitions',
                        to='fieldwork.requirement',
                    ),
                ),
                (
                    'status_updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='requirement_status_transitions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
