# Generated by Django 3.2.13 on 2022-06-29 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0055_requirement_metrics'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            Delete from fieldwork_evidencemetric;

            with METRICS as (
            select fa.evidence_id,
            count(fa.evidence_id) as integrations_count,
            null as monitors_count
            from fieldwork_attachment fa
            join fieldwork_evidence fe on fe.id = fa.evidence_id
            join audit_audit aa on aa.id = fe.audit_id
            join organization_organization oo on oo.id = aa.organization_id
            where fa.name ~ 'ACCOUNT|BACKGROUND_CHECK|BACKGROUND_REQUEST|
                DEVICE|EVENT|USER|MONITOR|PULL_REQUEST|REPOSITORY|SERVICE_ACCOUNT'
            AND fa.is_deleted = False
            group by fa.evidence_id
            UNION
            select fa.evidence_id, null as integrations_count, count(fa.evidence_id) monitors_count
            from fieldwork_attachment fa
            join fieldwork_evidence fe on fe.id = fa.evidence_id
            join audit_audit aa on aa.id = fe.audit_id
            join organization_organization oo on oo.id = aa.organization_id
            where fa.name ilike any(array['%[AWS] All s3 buckets are encrypted%',
            '%[AWS] s3 buckets are not publicly available%',
            '%[AWS] All DynamoDB instances are encrypted%',
            '%[AWS] DynamoDB instances are continuously backed up%',
            '%[AWS] All RDS databases are encrypted%',
            '%[AWS] RDS Databases are not publicly accessible%',
            '%[AWS] RDS cluster snapshots are encrypted%',
            '%[AWS] All secrets automatically rotate%',
            '%[AWS] CloudTrail is configured%',
            '%[AWS] All users have MFA enabled%',
            '%[Devices] All devices are encrypted%',
            '%[Accounts] Cloud infrastructure connected to Laika%',
            '%[Integration Users] All Github users have MFA%',
            '%[Accounts] MDM software connected to Laika%',
            '%[Repositories] All Repositories are private%',
            '%[AWS] Config is enabled%',
            '%[AWS] CloudWatch alarms are configured%',
            '%[Devices] All devices are encrypted%',
            '%[Policies] Information Security Policy Exists in Laika%',
            '%[Repositories] All Repositories are private%',
            '%[AWS] s3 buckets are not publicly available%',
            '%[Integration Users] All users have MFA enabled%',
            '%[Azure] Active Directory groups have security defaults enabled%',
            '%[Azure] No custom subscription IAM roles exist%',
            '%[Azure] Storage accounts are not publicly available%',
            '%[Azure] Storage accounts enforce encryption in transit%',
            '%[Azure] Storage containers do not allow public access%',
            '%[Azure] Storage account denies network access by default%',
            '%[Azure] All storage accounts are protected by soft deletion%',
            '%[Azure] SQL Servers have auditing enabled%',
            '%[Azure] Sql Databases are encrypted by default%',
            '%[Test] [Integration Users] All users have MFA enabled%',
            '%[Azure] SQL Servers have auditing enabled%',
            '%[AWS] All RDS databases are encrypted%',
            '%[Accounts] MDM software connected to Laika%',
            '%[AWS] All s3 buckets are encrypted%',
            '%[GCP] SQL Databases prohibit access from the open internet%',
            '%[GCP] Logging is configured%',
            '%[GCP] All secrets automatically rotate%',
            '%[GCP] All users have MFA enabled%',
            '%[GCP] Cloud monitoring is configured%',
            '%[GCP] All Compute Instances are using non-default service accts%',
            '%[GCP] All Compute Instances have explicit scopes%',
            '%[AWS] Strong password requirements are enforced%',
            '%[GCP] SQL Databases are backed up%',
            '%[Azure] Active Directory groups have security defaults enabled%',
            '%[GCP] All users have MFA enabled%',
            '%[Integration Users] All users have MFA enabled%',
            '%[GCP] All secrets automatically rotate%',
            '%[Azure] Sql Databases are encrypted by default%',
            '%[GCP] All Cloud Logs are Captured and Archived%',
            '%[GCP] Cloud SQL Database Instances Require SSL%',
            '%[Azure] Sql Databases are encrypted by default%',
            '%[Subtasks] No recurring tasks are overdue%',
            '%recurring tasks - test monitor%',
            '%[Azure] PostgreSQL Database Servers Enforce SSL Connections%',
            '%[Integration Users] All users have MFA enabled%',
            '%[AWS] All RDS databases are encrypted%',
            '%[AWS] RDS Databases are not publicly accessible%',
            '%[AWS] All s3 buckets are encrypted%',
            '%[Policies] Information Security Policy Published in Laika%',
            '%[AWS] SNS topics are encrypted at rest%',
            '%[AWS] CloudTrail trail logs are encrypted with KMS CMK%',
            '%[AWS] Redshift cluster encryption in transit is enabled%',
            '%[Azure] SQL Servers have auditing enabled%',
            '%[GCP] SQL Databases are backed up%',
            '%Custom Test Monitor%',
            '%[Azure] All storage accounts are protected by soft deletion%',
            '%[Azure] SQL Servers have auditing enabled%',
            '%[AWS] Log group encryption at rest should be enabled%',
            '%[Policies] Employee Handbook is Published%',
            '%[Policies] Information Security Policy Exists in Laika%',
            '%[AWS] All DynamoDB instances are encrypted%',
            '%[AWS] s3 buckets are not publicly available%',
            '%[AWS] All s3 buckets are encrypted%',
            '%[Devices] All devices are encrypted%',
            '%[GCP] Cloud SQL Database Instances Require SSL%',
            '%[Repositories] All Repositories are private%',
            '%[GCP] SQL Databases are backed up%',
            '%[GCP] All Compute Instances use instance-specific SSH keys%',
            '%[AWS] RDS DB instances have Multi AZ enabled%',
            '%[AWS] RDS DB instances have Multi AZ enabled%',
            '%[AWS] Non-Aurora RDS DB instances have deletion protection enabled%',
            '%[Azure] Public network access is disabled for MySQL servers%',
            '%[Azure] Public network access is disabled for MySQL servers%',
            '%[Azure] Compute VMs have automatic updates enabled%',
            '%[Azure] Compute VMs have automatic updates enabled%',
            '%[Azure] Storage account denies network access by default%',
            '%[Azure] No custom subscription IAM roles exist%',
            '%[AWS] Auto Scaling launch config public IP should be disabled%',
            '%[Azure] Storage Accounts restrict network access%',
            '%[Azure] Storage accounts should have infrastructure encryption%',
            '%[AWS] No EC2 instances stopped for longer than 30 days%',
            '%[Azure] MySQL Servers have SSL enabled%',
            '%[Azure] MySQL infrastructure encryption is enabled%',
            '%[AWS] EC2 instances are not publicly available%',
            '%[AWS] EC2 instances are in VPCs%',
            '%[Azure] MariaDB Servers have public access disabled%',
            '%[AWS] EC2 Instances have detailed monitoring enabled%',
            '%[AWS] EBS volume encryption at rest enabled%',
            '%[Azure] Keyvault Vaults disallow public network access%',
            '%[AWS] Redshift clusters automatically upgrade major versions%',
            '%[Azure] keyvault soft delete enabled%',
            '%[AWS] Redshift clusters retain backups for at least 7 days%',
            '%[AWS] RDS DB automatically upgrades minor version%',
            '%[Azure] Keyvault Secrets have expiration set%',
            '%[AWS] Aurora RDS DB clusters have deletion protection enabled%',
            '%[Azure] Redis caches are in virtual networks%',
            '%[GCP] Compute Instances have shielded VM enabled%',
            '%[GCP] Compute Instances have confidential computing enabled%',
            '%[GCP] Compute Instances disable serial port connections%',
            '%[AWS] RDS DB instances have deletion protection enabled%',
            '%[AWS] RDS DB clusters have deletion protection enabled%',
            '%[AWS] RDS DB clusters have deletion protection enabled%',
            '%[AWS] Aurora RDS DB clusters have deletion protection enabled%',
            '%[AWS] Aurora RDS DB clusters have Multi AZ enabled%',
            '%[AWS] RDS DB instances have Multi AZ enabled%',
            '%[AWS] All s3 buckets are encrypted%',
            '%[AWS] EBS volume encryption at rest enabled%'])
            And fa.is_deleted = False
            group by fa.evidence_id )

            INSERT INTO fieldwork_evidencemetric
            (evidence_request_id,
            integrations_counter, monitors_count, created_at, updated_at)
            select METRICS.evidence_id,
            CONCAT('{"general":',COALESCE(MAX(METRICS.integrations_count), 0),'}')::jsonb as integrations_count,
            COALESCE(MAX(METRICS.monitors_count), 0) as monitors_count,
            NOW(),
            NOW()
            from METRICS
            group by METRICS.evidence_id;
        ''',
            reverse_sql='',
        )
    ]
