# Generated by Django 3.2.13 on 2022-07-14 16:53

import django.db.models.deletion
from django.db import migrations, models

from fieldwork.constants import (
    LAIKA_EVIDENCE_SOURCE_TYPE,
    LAIKA_WF_SOURCE_TYPE,
    MONITOR_SOURCE_TYPE,
    OBJECT_SOURCE_TYPE,
    OTHER_SOURCE_TYPE,
    POLICY_SOURCE_TYPE,
)


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0056_backfill_er_monitor_integration_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentSourceType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(default='other', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attachments',
                to='fieldwork.attachmentsourcetype',
            ),
        ),
        migrations.RunSQL(
            f'''
            INSERT INTO public.fieldwork_attachmentsourcetype (name)
                VALUES ('{OTHER_SOURCE_TYPE}'), ('{OBJECT_SOURCE_TYPE}'), ('{MONITOR_SOURCE_TYPE}'),
                        ('{LAIKA_WF_SOURCE_TYPE}'), ('{LAIKA_EVIDENCE_SOURCE_TYPE}'), ('{POLICY_SOURCE_TYPE}');
            '''
        ),
    ]
