# Generated by Django 3.2.14 on 2022-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0057_create_attachme_source_type_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attachmentsourcetype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
