# Generated by Django 3.2.15 on 2022-09-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0060_adding_fields_to_track_er_back_to_open_reasons'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(
                check=models.Q(('er_type__in', ['evidence_request', 'sample_er'])),
                name='fieldwork_evidence_valid_er_type',
            ),
        ),
    ]
