# Generated by Django 3.2.15 on 2022-10-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0061_adding_er_type_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
