# Generated by Django 3.2.15 on 2022-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0062_criteria_is_qualified'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidencemetric',
            constraint=models.UniqueConstraint(
                fields=('evidence_request',), name='unique_evidence_request'
            ),
        ),
    ]
