# Generated by Django 3.2.15 on 2022-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0063_add_metrics_er_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentsourcetype',
            name='template',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='Automated source template'
            ),
        ),
    ]
