# Generated by Django 3.2.15 on 2022-11-25 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fieldwork', '0064_add_template_attachmentsourcetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_er_attachment',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='evidencestatustransition',
            name='laika_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencestatustransition',
            name='transitioned_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='er_status_transitions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
