# Generated by Django 3.2.15 on 2022-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0065_new_columns_for_transition_attach_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='origin_source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
