# Generated by Django 3.2.15 on 2022-11-28 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fieldwork', '0066_add_origin_source_id_to_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='origin_source_id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
