# Generated by Django 3.2.15 on 2022-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0069_add_automated_test_result_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='times_run_automate_test',
            field=models.IntegerField(default=0),
        ),
    ]
