# Generated by Django 3.2.15 on 2022-12-13 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0070_test_times_run_automate_test'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name = 'auditor_admin' or
                     g.name = 'auditor'
                  )
                  AND p.codename = 'change_criteria'
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        ),
    ]
