# Generated by Django 3.1.2 on 2021-01-05 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('POST', 'POST'),
                            ('MENTION', 'MENTION'),
                            ('REPLY', 'REPLY'),
                            ('RESOLVE', 'RESOLVE'),
                            ('UNRESOLVE', 'UNRESOLVE'),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    'receiver',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alerts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='alert_sender',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
