# Generated by Django 3.1.2 on 2021-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0001_adding_alert_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
