# Generated by Django 3.1.2 on 2021-01-12 20:11

from django.contrib.auth.management import create_permissions
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0002_alert_viewed'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike '%_admin' 
                     OR g.name ilike '%_super' 
                     OR g.name ilike '%_member'
                  )
                  AND p.codename = ANY (array [
                    'add_alert',
                    'change_alert',
                    'delete_alert',
                    'view_alert']
                    )
                )
                  ON CONFLICT DO NOTHING;
        '''
        )
    ]
