# Generated by Django 3.1.2 on 2021-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0003_add_alert_permissions_to_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('POST', 'POST'),
                    ('MENTION', 'MENTION'),
                    ('REPLY', 'REPLY'),
                    ('RESOLVE', 'RESOLVE'),
                    ('UNRESOLVE', 'UNRESOLVE'),
                    ('NEW_ASSIGNMENT', 'NEW_ASSIGNMENT'),
                    ('ASSIGNMENT_COMPLETED', 'ASSIGNMENT_COMPLETED'),
                ],
                max_length=25,
            ),
        ),
    ]
