# Generated by Django 3.1.12 on 2022-02-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='airtable_api_key',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='controlblueprint',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='controls',
                to='blueprint.controlgroupblueprint',
            ),
        ),
        migrations.AlterField(
            model_name='controlblueprint',
            name='implementation_guide',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='control',
                to='blueprint.implementationguideblueprint',
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='airtable_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
