# Generated by Django 3.1.12 on 2022-02-04 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0002_add_airtable_api_key_fix_control_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlgroupblueprint',
            options={'verbose_name_plural': 'Groups Blueprint'},
        ),
    ]
