# Generated by Django 3.1.12 on 2022-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0003_control_group_verbose_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemBlueprint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('is_required', models.BooleanField(default=False)),
                ('is_recurrent', models.BooleanField(default=False)),
                ('requires_evidence', models.BooleanField(default=False)),
                (
                    'recurrent_schedule',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('weekly', 'Weekly'),
                            ('monthly', 'Monthly'),
                            ('quarterly', 'Quarterly'),
                            ('semi_annually', 'Semi annually'),
                            ('annually', 'Annually'),
                            ('bi_annually', 'Bi annually'),
                        ],
                        default='weekly',
                        max_length=999,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('new', 'New'),
                            ('pending', 'Pending'),
                            ('completed', 'Completed'),
                            ('not_applicable', 'Not Applicable'),
                        ],
                        default='new',
                        max_length=15,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Action Items Blueprint',
            },
        ),
        migrations.AddField(
            model_name='controlblueprint',
            name='action_items',
            field=models.ManyToManyField(
                related_name='controls_blueprint', to='blueprint.ActionItemBlueprint'
            ),
        ),
    ]
