# Generated by Django 3.1.12 on 2022-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0004_action_item_blueprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlfamilyblueprint',
            options={'verbose_name_plural': 'Control Family Blueprint'},
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
