# Generated by Django 3.1.12 on 2022-02-10 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0006_add_airtable_record_id_to_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagblueprint',
            options={'verbose_name_plural': 'Tags Blueprint'},
        ),
    ]
