# Generated by Django 3.1.12 on 2022-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0007_tag_verbose_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='airtable_link',
            field=models.CharField(
                blank=True, max_length=2000, verbose_name='Airtable Base ID'
            ),
        ),
    ]
