# Generated by Django 3.1.12 on 2022-02-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0009_certificationproxy_certificationsectionproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationsectionproxy',
            options={
                'verbose_name': 'Certification Sections',
                'verbose_name_plural': 'Certification Sections Blueprint',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
