# Generated by Django 3.1.12 on 2022-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0010_change_proxy_verbiage'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlgroupblueprint',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
