# Generated by Django 3.1.12 on 2022-03-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0011_add_group_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlblueprint',
            name='family',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='controls',
                to='blueprint.controlfamilyblueprint',
            ),
        ),
    ]
