# Generated by Django 3.1.12 on 2022-03-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0012_make_null_control_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlgroupblueprint',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
