# Generated by Django 3.1.12 on 2022-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0013_change_updated_at_from_blueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlblueprint',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
