# Generated by Django 3.1.12 on 2022-03-09 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0014_remove_auto_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemblueprint',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionitemblueprint',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
