# Generated by Django 3.1.12 on 2022-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0017_officerblueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                    ('Tags', 'Tags'),
                    ('Officers', 'Officers'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
