# Generated by Django 3.1.12 on 2022-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0020_team_blueprint_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamblueprint',
            name='charter',
            field=models.TextField(blank=True),
        ),
    ]
