# Generated by Django 3.1.12 on 2022-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0021_team_blueprint_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistBlueprint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('checklist', models.TextField(max_length=200, unique=True)),
                ('airtable_record_id', models.CharField(blank=True, max_length=512)),
                ('type', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Checklist Blueprint',
            },
        ),
    ]
