# Generated by Django 3.1.12 on 2022-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0022_checklistblueprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistblueprint',
            name='reference_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistblueprint',
            name='checklist',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Checklist', 'Checklist'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                    ('Tags', 'Tags'),
                    ('Teams (Charters)', 'Teams'),
                    ('Officers', 'Officers'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
