# Generated by Django 3.1.12 on 2022-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0023_checklist_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBlueprint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('airtable_record_id', models.CharField(blank=True, max_length=512)),
                ('type_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('display_index', models.IntegerField()),
                ('is_system_type', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Object Types Blueprint',
            },
        ),
    ]
