# Generated by Django 3.2.13 on 2022-05-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0025_blueprint_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAttributeBlueprint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('object_type_name', models.CharField(max_length=100)),
                ('airtable_record_id', models.CharField(blank=True, max_length=512)),
                ('display_index', models.IntegerField()),
                ('attribute_type', models.CharField(max_length=100)),
                ('max_length', models.IntegerField()),
                ('is_protected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Object Type Attributes Blueprint',
            },
        ),
    ]
