# Generated by Django 3.2.13 on 2022-05-10 00:30

from django.db import migrations, models

import blueprint.models.training
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0027_training_blueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Checklist', 'Checklist'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                    ('Tags', 'Tags'),
                    ('Teams (Charters)', 'Teams'),
                    ('Files', 'Training'),
                    ('Object Types', 'Object'),
                    ('Officers', 'Officers'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='trainingblueprint',
            name='file_attachment',
            field=models.FileField(
                blank=True,
                max_length=512,
                storage=laika.storage.PublicMediaStorage(),
                upload_to=blueprint.models.training.training_file_directory_path,
            ),
        ),
    ]
