# Generated by Django 3.2.13 on 2022-05-17 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0070_add_onboarding_response_model'),
        ('blueprint', '0030_control_blueprint_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintHistory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('upload_action', models.TextField(max_length=200)),
                ('content_description', models.TextField(max_length=2048)),
                ('status', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='blueprint_history',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blueprint_history',
                        to='organization.organization',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Blueprint History',
            },
        ),
    ]
