# Generated by Django 3.2.13 on 2022-05-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0031_blueprinthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectattributeblueprint',
            name='default_value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
