# Generated by Django 3.2.13 on 2022-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0033_objectattributeblueprint_select_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectattributeblueprint',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
