# Generated by Django 3.2.13 on 2022-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0034_objectattributeblueprint_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBlueprint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('questionnaire', models.TextField(max_length=200)),
                ('airtable_record_id', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('short_answer', models.TextField(blank=True, default='')),
                ('short_answer_options', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Questions Blueprint',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Checklist', 'Checklist'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                    ('Tags', 'Tags'),
                    ('Teams (Charters)', 'Teams'),
                    ('Files', 'Training'),
                    ('Object Types', 'Object'),
                    ('Object Type Attributes', 'Object Attributes'),
                    ('Officers', 'Officers'),
                    ('Questions', 'Questions'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
