# Generated by Django 3.2.13 on 2022-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0035_question_blueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectattributeblueprint',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
