# Generated by Django 3.2.13 on 2022-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0036_alter_objectattributeblueprint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectattributeblueprint',
            name='reference_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
