# Generated by Django 3.2.13 on 2022-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0037_objectattributeblueprint_reference_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implementationguideblueprint',
            old_name='text',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='implementationguideblueprint',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Checklist', 'Checklist'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                    ('Tags', 'Tags'),
                    ('Teams (Charters)', 'Teams'),
                    ('Files', 'Training'),
                    ('Object Types', 'Object'),
                    ('Object Type Attributes', 'Object Attributes'),
                    ('Officers', 'Officers'),
                    ('Questions', 'Questions'),
                    ('Implementation Guides', 'Guides'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
