# Generated by Django 3.2.13 on 2022-07-05 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0038_implementation_guide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementationguideblueprint',
            options={'verbose_name_plural': 'Implementation Guides Blueprint'},
        ),
    ]
