# Generated by Django 3.2.13 on 2022-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0039_alter_implementationguideblueprint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlblueprint',
            name='framework_tag',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
