# Generated by Django 3.2.15 on 2022-08-17 22:45

from django.db import migrations, models

suggested_owner_choices = [
    ('Technical', 'Technical'),
    ('Human Resources', 'Human Resources'),
    ('Compliance', 'Compliance'),
]


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0042_alter_actionitemblueprint_recurrent_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemblueprint',
            name='suggested_owner',
            field=models.CharField(
                null=True,
                choices=suggested_owner_choices,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='controlblueprint',
            name='suggested_owner',
            field=models.CharField(
                null=True,
                choices=suggested_owner_choices,
                max_length=50,
            ),
        ),
    ]
