# Generated by Django 3.2.15 on 2022-09-29 02:46

from django.db import migrations, models

import blueprint.models.evidence_metadata
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0043_add_suggested_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceMetadataBlueprint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('reference_id', models.CharField(max_length=255)),
                ('airtable_record_id', models.CharField(blank=True, max_length=512)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'attachment',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PublicMediaStorage(),
                        upload_to=blueprint.models.evidence_metadata.evidence_metadata_attachments_directory_path,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Evidences Metadata Blueprint',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(
                choices=[
                    ('Global', 'Global'),
                    ('Controls', 'Controls'),
                    ('Certification', 'Certification'),
                    ('Certification Sections', 'Certification Sections'),
                    ('Checklist', 'Checklist'),
                    ('Control Family', 'Control Family'),
                    ('Action Items', 'Action Items'),
                    ('Groups', 'Groups'),
                    ('Tags', 'Tags'),
                    ('Teams (Charters)', 'Teams'),
                    ('Files', 'Training'),
                    ('Object Types', 'Object'),
                    ('Object Type Attributes', 'Object Attributes'),
                    ('Officers', 'Officers'),
                    ('Questions', 'Questions'),
                    ('Implementation Guides', 'Guides'),
                    ('Evidences Metadata', 'Evidences Metadata'),
                ],
                default='Controls',
                max_length=1024,
                unique=True,
            ),
        ),
    ]
