# Generated by Django 3.2.15 on 2022-10-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0044_add_evidence_metadata_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlblueprint',
            name='display_id',
            field=models.IntegerField(
                default=9999999, verbose_name='display id (within group)'
            ),
        ),
    ]
