# Generated by Django 3.2.15 on 2022-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0045_controlblueprint_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemblueprint',
            name='display_id',
            field=models.IntegerField(default=9999999),
        ),
    ]
