# Generated by Django 3.2.15 on 2022-11-30 20:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0046_actionitemblueprint_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemblueprint',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
