# Generated by Django 3.2.15 on 2022-12-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0047_alter_actionitemblueprint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemBlueprintTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='action_item_tags',
                        to='blueprint.actionitemblueprint',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='blueprint.tagblueprint',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='actionitemblueprint',
            name='tags',
            field=models.ManyToManyField(
                related_name='action_items',
                through='blueprint.ActionItemBlueprintTag',
                to='blueprint.TagBlueprint',
            ),
        ),
    ]
