DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 50
MAX_REPORT_NAME_LENGTH = 250
FILTER_DAYS = 'time'
ARCHIVED = 'archived'
FILTER_STATUS = 'status'
FILTER_SHARING_ACTIVE = 'active'
FILTER_SHARING_INACTIVE = 'inactive'
