# Generated by Django 3.0.2 on 2020-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
