# Generated by Django 3.0.2 on 2020-02-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('address', '0001_squashed-address'),
        ('organization', '0002_auto_20200204_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_address',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='billing_address',
                to='address.Address',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tier',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PREMIUM', 'Premium'),
                    ('STARTER', 'Starter'),
                    ('TEASER', 'Teaser'),
                ],
                max_length=10,
            ),
        ),
    ]
