# Generated by Django 3.0.3 on 2020-03-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('address', '0001_squashed-address'),
        ('organization', '0004_import_dynamo_to_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='billing_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='billing_address',
                to='address.Address',
            ),
        ),
    ]
