# Generated by Django 3.0.3 on 2020-04-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('address', '0001_squashed-address'),
        ('organization', '0005_auto_20200304_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='billing_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='billing_address',
                to='address.Address',
            ),
        ),
    ]
