# Generated by Django 3.0.7 on 2020-09-23 15:38

from django.db import migrations, models

import laika.storage
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0007_DateTimeField_instead_of_DateField'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(
                blank=True,
                max_length=2000,
                storage=laika.storage.PublicMediaStorage(),
                upload_to=organization.models.organization_file_directory_path,
            ),
        ),
    ]
