# Generated by Django 3.1.2 on 2021-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0008_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='compliance_architect',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='customer_success_manager',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
