# Generated by Django 3.1.2 on 2021-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0009_adding_csm_ca_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={
                'permissions': [
                    ('view_onboarding_state', 'Can view onboarding pages only'),
                    ('change_onboarding_state', 'Can change onboarding pages'),
                ]
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(
                choices=[('ONBOARDING', 'ONBOARDING'), ('ACTIVE', 'ACTIVE')],
                default='ACTIVE',
                max_length=20,
            ),
        ),
    ]
