# Generated by Django 3.1.2 on 2021-02-09 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0010_adding_state_and_permissions'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike '%_super'
                             OR g.name ilike '%_admin'
                             OR g.name ilike '%_member'
                             OR g.name ilike '%_viewer'
                             OR g.name ilike '%_sales'
                          )
                          AND p.codename = 'view_onboarding_state'
                    )
                    ON CONFLICT DO NOTHING;
            '''
        ),
        migrations.RunSQL(
            '''
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                            g.name ilike '%_super'
                            AND p.codename = 'change_onboarding_state'
                    )
                    ON CONFLICT DO NOTHING;
            '''
        ),
    ]
