# Generated by Django 3.1.2 on 2021-03-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0012_adding_is_active_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'stage',
                    models.CharField(
                        choices=[
                            ('NOT_STARTED', 'NOT_STARTED'),
                            ('GETTING_STARTED', 'GETTING_STARTED'),
                            ('PEOPLE_AND_LOCATIONS', 'PEOPLE_AND_LOCATIONS'),
                            ('ASSET_AND_VENDORS', 'ASSET_AND_VENDORS'),
                            ('COMPLIANCE_PROGRAM', 'COMPLIANCE_PROGRAM'),
                            ('INVITE_TEAM', 'INVITE_TEAM'),
                        ],
                        default='NOT_STARTED',
                        max_length=50,
                    ),
                ),
                ('step', models.IntegerField(blank=True, default=1, null=True)),
                ('period_ends', models.IntegerField(default=31)),
                ('control_prescription', models.BooleanField(default=False)),
                ('documentation_review', models.BooleanField(default=False)),
                ('operational_maturity_review', models.BooleanField(default=False)),
                ('risk_assessment', models.BooleanField(default=False)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='onboarding',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
    ]
