# Generated by Django 3.1.2 on 2021-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0013_create_onboarding_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='period_ends',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='period_ends',
            field=models.DateField(blank=True, null=True),
        ),
    ]
