# Generated by Django 3.1.2 on 2021-03-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0014_update_period_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='onboarding',
            constraint=models.CheckConstraint(
                check=models.Q(
                    stage__in=[
                        'NOT_STARTED',
                        'GETTING_STARTED',
                        'PEOPLE_AND_LOCATIONS',
                        'ASSET_AND_VENDORS',
                        'COMPLIANCE_PROGRAM',
                        'INVITE_TEAM',
                    ]
                ),
                name='organization_onboarding_stages_valid',
            ),
        ),
    ]
