# Generated by Django 3.1.2 on 2021-03-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0015_add_db_constraint_onboarding_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLocation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=255)),
                ('hq', models.BooleanField(default=False)),
                (
                    'address',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organization_location',
                        to='address.address',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='locations',
            field=models.ManyToManyField(
                related_name='organizations',
                through='organization.OrganizationLocation',
                to='address.Address',
            ),
        ),
    ]
