# Generated by Django 3.1.2 on 2021-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0016_add_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
