# Generated by Django 3.1.2 on 2021-03-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0017_add_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='compliance_architect_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_ca',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='customer_success_manager_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_csm',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
