# Generated by Django 3.1.2 on 2021-03-10 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0018_adding_csm_ca_as_users'),
    ]

    operations = [
        migrations.RunSQL(
            ''' 
           BEGIN;
           UPDATE organization_organization oo
           SET    compliance_architect_user_id = subquery.id
           FROM   (SELECT id, email,
                    CASE
                        WHEN email = 'dana@heylaika.com' THEN 'Dana Mueller'
                        WHEN email = 'cristina@heylaika.com' THEN 'Cristina Bartolacci'
                        WHEN email = 'shawn@heylaika.com' THEN 'Shawn Studholme'
                        ELSE NULL
                    END AS NAME
                    FROM   user_user
                    WHERE  email IN ( 'dana@heylaika.com', 
                    'cristina@heylaika.com', 'shawn@heylaika.com')
                    AND is_staff = true
                    ) AS subquery
           WHERE  oo.compliance_architect LIKE subquery.NAME;
           COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
           BEGIN;
           UPDATE organization_organization oo
           SET    customer_success_manager_user_id = subquery.id
           FROM   (SELECT id, email,
                    CASE
                        WHEN email = 'amalia@heylaika.com' THEN 'Amalia Simpson'
                        WHEN email = 'annie@heylaika.com' THEN 'Annie Black'
                        WHEN email = 'vince@heylaika.com' THEN 'Vince Loncto'
                        ELSE NULL
                    END AS NAME
                    FROM   user_user
                    WHERE  email IN ( 'amalia@heylaika.com', 
                    'annie@heylaika.com', 'vince@heylaika.com' )
                    AND is_staff = true
                    ) AS subquery
           WHERE  oo.customer_success_manager LIKE subquery.NAME;
           COMMIT;
        '''
        ),
    ]
