# Generated by Django 3.1.2 on 2021-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0019_adding_values_to_csm_ca_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='onboarding',
            name='organization_onboarding_stages_valid',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='step',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='state',
            field=models.CharField(
                choices=[
                    ('INIT', 'INIT'),
                    ('ENROLLED', 'ENROLLED'),
                    ('REVIEW', 'REVIEW'),
                    ('READY', 'READY'),
                    ('COMPLETED', 'COMPLETED'),
                ],
                default='INIT',
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name='onboarding',
            constraint=models.CheckConstraint(
                check=models.Q(
                    state__in=['INIT', 'ENROLLED', 'REVIEW', 'READY', 'COMPLETED']
                ),
                name='organization_onboarding_states_valid',
            ),
        ),
    ]
