# Generated by Django 3.1.2 on 2021-03-15 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0020_changing_stage_to_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auditor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_auditor',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
