# Generated by Django 3.1.2 on 2021-03-15 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0021_organization_auditor'),
    ]

    operations = [
        migrations.RunSQL(
            ''' 
        BEGIN;
        UPDATE organization_organization oo
        SET    auditor_id = subquery.id
        FROM   (SELECT id
                FROM   user_user
                WHERE  email = 'leith@laikacompliance.com'
                AND is_staff = true
                ) AS subquery
        WHERE  oo.auditor_id is NULL;
        COMMIT;
        '''
        ),
    ]
