# Generated by Django 3.1.2 on 2021-03-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0022_migrating_auditor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sfdc_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
