# Generated by Django 3.1.2 on 2021-03-31 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0024_adding_values_to_sfdc_field'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'view_onboarding_state' OR
                    codename = 'change_onboarding_state'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.user_user_user_permissions
                WHERE permission_id in
                (
                  SELECT id FROM public.auth_permission
                  WHERE
                    codename = 'view_onboarding_state' OR
                    codename = 'change_onboarding_state'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_permission
                WHERE
                codename = 'view_onboarding_state' OR
                codename = 'change_onboarding_state';
                COMMIT;
            ''',
            reverse_sql='',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='onboarding',
            options={
                'permissions': [('super_onboarding', 'Can super access onboarding')]
            },
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike '%_super'
                             OR g.name ilike '%_admin'
                             OR g.name ilike '%_member'
                             OR g.name ilike '%_viewer'
                             OR g.name ilike '%_sales'
                          )
                          AND p.codename = 'view_onboarding'
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'view_onboarding'
                );
                COMMIT;
            ''',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike '%_super'
                             OR g.name ilike '%_admin'
                          )
                          AND p.codename = 'change_onboarding'
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'change_onboarding'
                );
                COMMIT;
            ''',
        ),
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike '%_super'
                          )
                          AND p.codename = 'super_onboarding'
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'super_onboarding'
                );
                COMMIT;
            ''',
        ),
    ]
