# Generated by Django 3.1.2 on 2021-04-12 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0025_removing_onboarding_state_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSetupStep',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('CONTROL_PRESCRIPTION', 'CONTROL_PRESCRIPTION'),
                            ('DOCUMENTATION_REVIEW', 'DOCUMENTATION_REVIEW'),
                            (
                                'OPERATIONAL_MATURITY_REVIEW',
                                'OPERATIONAL_MATURITY_REVIEW',
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'onboarding',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='setup_steps',
                        to='organization.onboarding',
                    ),
                ),
            ],
        ),
    ]
