# Generated by Django 3.1.2 on 2021-04-12 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0026_create_onboarding_setup_step_model'),
    ]

    def insert_data(apps, schema_editor):
        onboarding_model = apps.get_model('organization', 'Onboarding')
        setup_step_model = apps.get_model('organization', 'OnboardingSetupStep')
        for onboarding in onboarding_model.objects.all():
            setup_step_model.objects.create(
                onboarding=onboarding,
                name='CONTROL_PRESCRIPTION',
                completed=onboarding.control_prescription,
            )
            setup_step_model.objects.create(
                onboarding=onboarding,
                name='DOCUMENTATION_REVIEW',
                completed=onboarding.documentation_review,
            )
            setup_step_model.objects.create(
                onboarding=onboarding,
                name='OPERATIONAL_MATURITY_REVIEW',
                completed=onboarding.operational_maturity_review,
            )

    operations = [migrations.RunPython(insert_data)]
