# Generated by Django 3.1.2 on 2021-04-12 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0027_migrate_onboarding_data_to_setup_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='control_prescription',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='documentation_review',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='operational_maturity_review',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='risk_assessment',
        ),
    ]
