# Generated by Django 3.1.2 on 2021-04-19 20:11

from django.db import migrations


def add_global_menu_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='globalMenuFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0028_remove_onboarding_step_columns'),
    ]

    operations = [migrations.RunPython(add_global_menu_feature_flag)]
