# Generated by Django 3.1.2 on 2021-04-23 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0029_add_global_menu_feature_flag'),
    ]

    operations = [
        # DELETE all Location permissions from groups
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'add_organizationlocation' OR
                    codename = 'change_organizationlocation' OR
                    codename = 'delete_organizationlocation' OR
                    codename = 'view_organizationlocation'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        # DELETE all Location permissions from user permissions
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.user_user_user_permissions
                WHERE permission_id in
                (
                  SELECT id FROM public.auth_permission
                  WHERE
                    codename = 'add_organizationlocation' OR
                    codename = 'change_organizationlocation' OR
                    codename = 'delete_organizationlocation' OR
                    codename = 'view_organizationlocation'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        # ADD all Location permissions to Super, Admin and Members
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike '%_super'
                             OR g.name ilike '%_admin'
                             OR g.name ilike '%_member'
                          )
                          AND 
                          (
                             p.codename = 'add_organizationlocation'
                             OR p.codename = 'change_organizationlocation'
                             OR p.codename = 'delete_organizationlocation'
                             OR p.codename = 'view_organizationlocation'
                          )
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                    BEGIN;
                    DELETE FROM public.auth_group_permissions 
                    WHERE permission_id in 
                    (
                      SELECT id FROM public.auth_permission 
                      WHERE
                        codename = 'add_organizationlocation' OR
                        codename = 'change_organizationlocation' OR
                        codename = 'delete_organizationlocation' OR
                        codename = 'view_organizationlocation'
                    );
                    COMMIT;
                ''',
        ),
    ]
