# Generated by Django 3.1.2 on 2021-04-23 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0030_adding_location_permissions'),
    ]

    operations = [
        # DELETE all Onboarding permissions from groups
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'add_onboarding'
                    OR codename = 'add_onboardingpolicy'
                    OR codename = 'add_onboardingsetupstep'
                    OR codename = 'change_onboarding'
                    OR codename = 'change_onboardingpolicy'
                    OR codename = 'change_onboardingsetupstep'
                    OR codename = 'delete_onboarding'
                    OR codename = 'delete_onboardingpolicy'
                    OR codename = 'delete_onboardingsetupstep'
                    OR codename = 'super_onboarding'
                    OR codename = 'view_onboarding'
                    OR codename = 'view_onboardingpolicy'
                    OR codename = 'view_onboardingsetupstep'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        # DELETE all Onboarding permissions from user permissions
        migrations.RunSQL(
            '''
                BEGIN;
                DELETE FROM public.user_user_user_permissions
                WHERE permission_id in
                (
                  SELECT id FROM public.auth_permission
                  WHERE
                    codename = 'add_onboarding'
                    OR codename = 'add_onboardingpolicy'
                    OR codename = 'add_onboardingsetupstep'
                    OR codename = 'change_onboarding'
                    OR codename = 'change_onboardingpolicy'
                    OR codename = 'change_onboardingsetupstep'
                    OR codename = 'delete_onboarding'
                    OR codename = 'delete_onboardingpolicy'
                    OR codename = 'delete_onboardingsetupstep'
                    OR codename = 'super_onboarding'
                    OR codename = 'view_onboarding'
                    OR codename = 'view_onboardingpolicy'
                    OR codename = 'view_onboardingsetupstep'
                );
                COMMIT;
            ''',
            reverse_sql='',
        ),
        # ADD Onboarding permissions to Super
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike 'premium_super'
                          )
                          AND 
                          (
                            codename = 'super_onboarding'
                          )
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'super_onboarding'
                );
                COMMIT;
            ''',
        ),
        # ADD Onboarding permissions to Super and Admin
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                             g.name ilike '%_super'
                             OR g.name ilike '%_admin'
                          )
                          AND 
                          (
                            codename = 'add_onboarding'
                            OR codename = 'add_onboardingpolicy'
                            OR codename = 'add_onboardingsetupstep'
                            OR codename = 'change_onboarding'
                            OR codename = 'change_onboardingpolicy'
                            OR codename = 'change_onboardingsetupstep'
                            OR codename = 'delete_onboarding'
                            OR codename = 'delete_onboardingpolicy'
                            OR codename = 'delete_onboardingsetupstep'
                          )
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'add_onboarding'
                    OR codename = 'add_onboardingpolicy'
                    OR codename = 'add_onboardingsetupstep'
                    OR codename = 'change_onboarding'
                    OR codename = 'change_onboardingpolicy'
                    OR codename = 'change_onboardingsetupstep'
                    OR codename = 'delete_onboarding'
                    OR codename = 'delete_onboardingpolicy'
                    OR codename = 'delete_onboardingsetupstep'
                );
                COMMIT;
            ''',
        ),
        # ADD Onboarding permissions to all Groups
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                       SELECT
                          g.id AS group_id, p.id AS permission_id 
                       FROM
                          public.auth_group g 
                          cross join
                             public.auth_permission p 
                       WHERE
                          (
                            codename = 'view_onboarding'
                            OR codename = 'view_onboardingpolicy'
                            OR codename = 'view_onboardingsetupstep'
                          )
                    )
                    ON CONFLICT DO NOTHING;
                COMMIT;
            ''',
            reverse_sql='''
                BEGIN;
                DELETE FROM public.auth_group_permissions 
                WHERE permission_id in 
                (
                  SELECT id FROM public.auth_permission 
                  WHERE
                    codename = 'view_onboarding'
                    OR codename = 'view_onboardingpolicy'
                    OR codename = 'view_onboardingsetupstep'
                );
                COMMIT;
            ''',
        ),
    ]
