# Generated by Django 3.1.2 on 2021-05-05 19:08

from django.db import migrations


def add_archived_programs_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.filter(
        archived_program__isnull=False
    ).distinct('id'):
        flag_model.objects.get_or_create(
            name='archivedProgramsFeatureFlag',
            organization=organization,
            defaults={'is_enabled': True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0031_adding_onboarding_permissions'),
        ('program', '0031_create_archived_user_model'),
    ]

    operations = [migrations.RunPython(add_archived_programs_feature_flag)]
