# Generated by Django 3.1.6 on 2021-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0032_adding_archived_programs_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(
                choices=[('ONBOARDING', 'ONBOARDING'), ('ACTIVE', 'ACTIVE')],
                default='ONBOARDING',
                max_length=20,
            ),
        ),
    ]
