# Generated by Django 3.1.6 on 2021-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0034_organization_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=2000),
        ),
    ]
