# Generated by Django 3.1.6 on 2021-05-17 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0035_alter_name_website_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='compliance_architect',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='customer_success_manager',
        ),
    ]
