# Generated by Django 3.1.6 on 2021-05-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0017_add_audit_firm_fk'),
        ('organization', '0036_delete_csm_and_ca_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_firms',
            field=models.ManyToManyField(
                related_name='organizations',
                through='audit.OrganizationAuditFirm',
                to='audit.AuditFirm',
            ),
        ),
    ]
