# Generated by Django 3.1.6 on 2021-05-29 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0037_organization_audit_firms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='auditor',
        ),
    ]
