# Generated by Django 3.1.6 on 2021-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0038_remove_organization_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tier',
            field=models.CharField(
                choices=[
                    ('PREMIUM', 'Premium'),
                    ('STARTER', 'Starter'),
                    ('TEASER', 'Teaser'),
                ],
                default='PREMIUM',
                max_length=10,
            ),
        ),
    ]
