# Generated by Django 3.1.6 on 2021-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'organization',
            '0039_make_organization_tier_required_and_set_default_to_premium',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contract_sign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
