# Generated by Django 3.1.2 on 2021-06-01 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0040_organization_contract_sign_date'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            DROP TABLE IF EXISTS billing_plan
        '''
        )
    ]
