# Generated by Django 3.1.6 on 2021-06-07 00:13

from django.db import migrations


def remove_program_feature_flag(apps, schema_editor):
    Flag = apps.get_model('feature', 'Flag')
    Flag.objects.filter(
        name__in=('programsFeatureFlag', 'programsLegacyFeatureFlag')
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0041_drop_plan_table'),
    ]

    operations = [migrations.RunPython(remove_program_feature_flag)]
