# Generated by Django 3.1.6 on 2021-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0042_delete_program_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsetupstep',
            name='name',
            field=models.CharField(
                choices=[
                    ('CONTROL_PRESCRIPTION', 'CONTROL_PRESCRIPTION'),
                    ('DOCUMENTATION_REVIEW', 'DOCUMENTATION_REVIEW'),
                    ('OPERATIONAL_MATURITY_REVIEW', 'OPERATIONAL_MATURITY_REVIEW'),
                    ('SELECT_CERTIFICATIONS', 'SELECT_CERTIFICATIONS'),
                    ('SEED_RELEVANT_DOCUMENTS', 'SEED_RELEVANT_DOCUMENTS'),
                ],
                max_length=50,
            ),
        ),
    ]
