# Generated by Django 3.1.12 on 2021-07-23 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0044_add_missing_flags_to_old_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                (
                    'customer_participant',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('notes', models.TextField()),
                ('action_items', models.TextField()),
                ('active', models.BooleanField(default=True)),
                (
                    'cx_participant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='check_ins',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='check_ins',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
    ]
