# Generated by Django 3.1.12 on 2021-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0045_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
