# Generated by Django 3.1.12 on 2021-08-23 16:35

from django.db import migrations


def add_github_classic_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')
    organizations_with_successful_github_connections = (
        organization_model.objects.filter(
            connection_accounts__integration__vendor__name__iexact='Github',
            connection_accounts__status='success',
        )
    )

    for organization in organizations_with_successful_github_connections:
        flag_model.objects.get_or_create(
            name='githubClassicIntegrationFeatureFlag',
            organization=organization,
            defaults={'is_enabled': True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0046_organization_is_internal'),
    ]

    operations = [migrations.RunPython(add_github_classic_feature_flag)]
