# Generated by Django 3.1.6 on 2021-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'organization',
            '0047_add_github_classic_feature_flag_to_successful_organizations',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='target_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
