# Generated by Django 3.1.12 on 2021-09-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0048_organization_target_audit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contract_sign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='target_audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
