# Generated by Django 3.1.12 on 2021-09-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0049_alter_contract_and_audit_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='product_or_service_description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
