# Generated by Django 3.1.12 on 2021-09-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0003_tag_is_manual'),
        ('organization', '0052_checklist_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationchecklist',
            name='items',
        ),
        migrations.AlterField(
            model_name='organizationchecklistitem',
            name='organization_checklist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='organization.organizationchecklist',
            ),
        ),
        migrations.AlterField(
            model_name='organizationchecklistitem',
            name='task_type',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.tag'
            ),
        ),
    ]
