# Generated by Django 3.1.12 on 2021-09-29 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0003_tag_is_manual'),
        ('organization', '0053_update_checklist_related_name_and_tag_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationchecklistitem',
            name='task_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tag.tag',
            ),
        ),
    ]
