# Generated by Django 3.1.12 on 2021-09-29 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import laika.storage
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0054_make_tag_optional_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='compliance_architect_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_ca',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contract_sign_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='customer_success_manager_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_csm',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(
                max_length=2000,
                storage=laika.storage.PublicMediaStorage(),
                upload_to=organization.models.organization_file_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sfdc_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(
                choices=[
                    ('ONBOARDING', 'ONBOARDING'),
                    ('ACTIVE', 'ACTIVE'),
                    ('DEACTIVATED', 'DEACTIVATED'),
                    ('TRIAL', 'TRIAL'),
                ],
                default='ONBOARDING',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tier',
            field=models.CharField(
                choices=[('PREMIUM', 'Premium')], default='PREMIUM', max_length=10
            ),
        ),
    ]
