# Generated by Django 3.1.6 on 2021-05-10 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0055_add_more_states_refactoring_of_model'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
              UPDATE organization_organization
              SET state = 'DEACTIVATED'
              WHERE is_active = False;
            COMMIT;
          '''
        )
    ]
