# Generated by Django 3.1.12 on 2021-10-02 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0056_migrate_to_deactivated_delete_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
    ]
