# Generated by Django 3.1.12 on 2021-10-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0003_tag_is_manual'),
        ('action_item', '0002_adding_metadata_action_item'),
        ('organization', '0057_remove_organization_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationchecklist',
            name='name',
        ),
        migrations.AddField(
            model_name='organizationchecklist',
            name='action_item',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checklist',
                to='action_item.actionitem',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationchecklist',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='checklist_tags', to='tag.Tag'
            ),
        ),
        migrations.DeleteModel(
            name='OrganizationChecklistItem',
        ),
    ]
