# Generated by Django 3.1.12 on 2021-10-07 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import laika.storage
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0024_add_number_of_users_field'),
        ('action_item', '0002_adding_metadata_action_item'),
        ('organization', '0058_remove_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingRun',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                (
                    'document',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=organization.models.organization_offboarding_file_path,
                    ),
                ),
                (
                    'checklist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='offboarding_runs',
                        to='organization.organizationchecklist',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='offboarding_runs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingVendor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                (
                    'offboarding_run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.offboardingrun',
                    ),
                ),
                (
                    'vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingSteps',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                (
                    'action_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='action_item.actionitem',
                    ),
                ),
                (
                    'offboarding_run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.offboardingrun',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='offboardingrun',
            name='steps',
            field=models.ManyToManyField(
                through='organization.OffboardingSteps', to='action_item.ActionItem'
            ),
        ),
        migrations.AddField(
            model_name='offboardingrun',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offboarding_run',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='offboardingrun',
            name='vendors',
            field=models.ManyToManyField(
                through='organization.OffboardingVendor', to='vendor.Vendor'
            ),
        ),
    ]
