# Generated by Django 3.1.12 on 2021-10-26 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import laika.storage
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action_item', '0004_remove_explicit_relation'),
        ('organization', '0059_create_offboarding_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChecklistRun',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                (
                    'document',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=organization.models.organization_offboarding_file_path,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationChecklistRunSteps',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('pending', 'Pending'),
                            ('completed', 'Completed'),
                            ('not_applicable', 'Not Applicable'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                (
                    'action_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='action_item.actionitem',
                    ),
                ),
                (
                    'checklist_run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='steps',
                        to='organization.organizationchecklistrun',
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='offboardingsteps',
            name='action_item',
        ),
        migrations.RemoveField(
            model_name='offboardingsteps',
            name='offboarding_run',
        ),
        migrations.RemoveField(
            model_name='offboardingvendor',
            name='offboarding_run',
        ),
        migrations.AddField(
            model_name='offboardingvendor',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('pending', 'Pending'),
                    ('completed', 'Completed'),
                    ('not_applicable', 'Not Applicable'),
                ],
                default='pending',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='organizationchecklist',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationchecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='OffboardingRun',
        ),
        migrations.DeleteModel(
            name='OffboardingSteps',
        ),
        migrations.AddField(
            model_name='organizationchecklistrun',
            name='checklist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checklist_runs',
                to='organization.organizationchecklist',
            ),
        ),
        migrations.AddField(
            model_name='organizationchecklistrun',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checklist_runs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='offboardingvendor',
            name='checklist_run',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vendors',
                to='organization.organizationchecklistrun',
            ),
            preserve_default=False,
        ),
    ]
