# Generated by Django 3.1.12 on 2021-10-28 20:21
from django.contrib.auth.models import Group, Permission
from django.db import migrations
from django.db.models import Q


def add_permissions(apps, schema_editor):
    groups = Group.objects.filter(
        Q(name__contains='_admin') | Q(name__contains='_super')
    )
    permissions = Permission.objects.filter(
        codename__in=[
            'add_organizationchecklistrun',
            'change_organizationchecklistrun',
            'delete_organizationchecklistrun',
            'view_organizationchecklistrun',
        ]
    )
    for group in groups:
        group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0060_update_offboarding_models'),
    ]

    operations = [
        migrations.RunPython(add_permissions, reverse_code=migrations.RunPython.noop),
    ]
