# Generated by Django 3.1.12 on 2021-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0061_checklist_run_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offboardingvendor',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationchecklistrunsteps',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
