# Generated by Django 3.1.12 on 2021-12-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0063_seed_offboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTokenHistory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('name', models.TextField()),
                ('api_key', models.TextField()),
                ('token_identifier', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='api_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='api_tokens',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='apitokenhistory',
            constraint=models.UniqueConstraint(
                fields=('organization', 'token_identifier'),
                name='unique_token_for_organization',
            ),
        ),
    ]
