# Generated by Django 3.1.12 on 2022-01-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0065_create_api_admin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('subtask_text', models.TextField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
