# Generated by Django 3.1.12 on 2022-01-12 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0066_create_subtask_tags_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('view_quick_links', 'Can view quick links')]},
        ),
    ]
