# Generated by Django 3.1.12 on 2022-01-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0067_adding_quick_links_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsetupstep',
            name='name',
            field=models.CharField(
                choices=[
                    ('CONTROL_PRESCRIPTION', 'CONTROL_PRESCRIPTION'),
                    ('DOCUMENTATION_REVIEW', 'DOCUMENTATION_REVIEW'),
                    ('OPERATIONAL_MATURITY_REVIEW', 'OPERATIONAL_MATURITY_REVIEW'),
                    ('SELECT_CERTIFICATIONS', 'SELECT_CERTIFICATIONS'),
                    ('SEED_RELEVANT_DOCUMENTS', 'SEED_RELEVANT_DOCUMENTS'),
                    ('ROADMAP_CONFIGURATION', 'ROADMAP_CONFIGURATION'),
                ],
                max_length=50,
            ),
        ),
    ]
