# Generated by Django 3.1.12 on 2022-01-28 21:33

from django.db import migrations

from organization.models import ACTIVE


def complete_onboardings(apps, schema_editor):
    Onboarding = apps.get_model('organization', 'Onboarding')

    incomplete_onboardings = Onboarding.objects.filter(
        organization__state=ACTIVE
    ).exclude(state='COMPLETED')

    for onboarding in incomplete_onboardings:
        onboarding.state = 'COMPLETED'
        for step in onboarding.setup_steps.all():
            step.completed = True
            step.save()
        onboarding.save()


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0068_add_onboarding_new_step'),
    ]

    operations = [migrations.RunPython(complete_onboardings)]
