# Generated by Django 3.2.13 on 2022-05-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0070_add_onboarding_response_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
