# Generated by Django 3.2.13 on 2022-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0071_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitokenhistory',
            name='usage_type',
            field=models.CharField(
                blank=True,
                choices=[('INTEGRATION', 'INTEGRATION'), ('EXCEL', 'EXCEL')],
                default='INTEGRATION',
                max_length=50,
            ),
        ),
    ]
