# Generated by Django 3.2.13 on 2022-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0072_apitokenhistory_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='calendly_url',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]
