# Generated by Django 3.2.14 on 2022-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0073_organization_calendly_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='state_v2',
            field=models.CharField(
                choices=[
                    ('QUESTIONNAIRE', 'Questionnaire'),
                    ('ARCHITECT_MEETING', 'Architect Meeting'),
                    ('AUTOMATE_COMPLIANCE', 'Automate Compliance'),
                ],
                default='QUESTIONNAIRE',
                max_length=50,
            ),
        ),
    ]
