# Generated by Django 3.2.13 on 2022-08-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0074_onboarding_state_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='calendly_event_id_v2',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='calendly_invitee_id_v2',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
