# Generated by Django 3.2.15 on 2022-10-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0075_onboarding_calendly_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='system_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
