# Generated by Django 3.2.15 on 2022-11-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0076_add_organization_system_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingresponse',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_response', to=settings.AUTH_USER_MODEL),
        ),
    ]
