# Generated by Django 3.2.15 on 2022-12-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0077_onboardingresponse_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='state_v2',
            field=models.CharField(
                choices=[
                    ('QUESTIONNAIRE', 'Questionnaire'),
                    ('ARCHITECT_MEETING', 'Architect Meeting'),
                    ('AUTOMATE_COMPLIANCE', 'Automate Compliance'),
                    ('WAITING', 'Waiting'),
                ],
                default='QUESTIONNAIRE',
                max_length=50,
            ),
        ),
    ]
