from laika.types import ErrorType

CODE_GENERAL_POLICY_ERROR = 'policy_error'
CODE_GENERAL_PUBLISH_POLICY_ERROR = 'publish_policy_error'
CODE_GENERAL_UNPUBLISH_POLICY_ERROR = 'unpublish_policy_error'
CODE_GENERAL_DELETE_POLICIES_ERROR = 'delete_policies_error'
CODE_GENERAL_RESTORE_POLICY_ERROR = 'restore_policy_error'
CODE_GENERAL_SAVE_POLICY_DOCUMENT_ERROR = 'save_policy_document_error'

MSG_VALIDATION_ERROR = 'Validation error'
MSG_DOES_NOT_EXIST_ERROR = 'Does Not Exist Error'
MSG_MISSING_REQUIRED_FIELDS = 'Missing required fields'
MSG_CANNOT_CREATE_POLICY = 'Cannot create policy'
MSG_CANNOT_UPDATE_POLICY = 'Cannot update policy'
MSG_CANNOT_DELETE_POLICIES = 'Cannot delete policies'
MSG_CANNOT_GET_POLICY = 'Cannot get policy'
MSG_CANNOT_GET_POLICIES = 'Cannot get policies'

MSG_CANNOT_PUBLISH_POLICY = 'Cannot publish policy'
MSG_CANNOT_UNPUBLISH_POLICY = 'Cannot unpublish policy'
MSG_CANNOT_GET_POLICY_VERSION_HISTORY = 'Cannot get version history'
MSG_CANNOT_GET_POLICY_VERSION_PREVIEW = 'Cannot get version preview'
MSG_CANNOT_RESTORE_POLICY = 'Cannot restore policy'
MSG_CANNOT_SAVE_POLICY_DOCUMENT = 'Cannot save policy document'

VALIDATION_ERROR = ErrorType(
    code=CODE_GENERAL_POLICY_ERROR, message=MSG_VALIDATION_ERROR
)

DOES_NOT_EXIST_ERROR = ErrorType(
    code=CODE_GENERAL_POLICY_ERROR, message=MSG_DOES_NOT_EXIST_ERROR
)

CANNOT_CREATE_POLICY_ERROR = ErrorType(
    code=CODE_GENERAL_POLICY_ERROR, message=MSG_CANNOT_CREATE_POLICY
)

CANNOT_UPDATE_POLICY_ERROR = ErrorType(
    code=CODE_GENERAL_POLICY_ERROR, message=MSG_CANNOT_UPDATE_POLICY
)

CANNOT_GET_POLICY_ERROR = ErrorType(
    code=CODE_GENERAL_POLICY_ERROR, message=MSG_CANNOT_GET_POLICY
)

CANNOT_GET_POLICIES_ERROR = ErrorType(
    code=CODE_GENERAL_POLICY_ERROR, message=MSG_CANNOT_GET_POLICIES
)

CANNOT_PUBLISH_POLICY_ERROR = ErrorType(
    code=CODE_GENERAL_PUBLISH_POLICY_ERROR, message=MSG_CANNOT_PUBLISH_POLICY
)

MISSING_POLICY_OWNER_ERROR = ErrorType(
    code=CODE_GENERAL_PUBLISH_POLICY_ERROR, message='MissingPolicyOAA'
)

BAD_FORMATTED_DOCX_FILE_ERROR = ErrorType(
    code=CODE_GENERAL_PUBLISH_POLICY_ERROR, message='DOCX file issue'
)

WRONG_DRAFT_FILE_FORMAT_ERROR = ErrorType(
    code=CODE_GENERAL_PUBLISH_POLICY_ERROR, message='Incompatible file format'
)

CANNOT_UNPUBLISH_POLICY_ERROR = ErrorType(
    code=CODE_GENERAL_UNPUBLISH_POLICY_ERROR, message=MSG_CANNOT_UNPUBLISH_POLICY
)

CANNOT_GET_VERSION_HISTORY_ERROR = ErrorType(
    code=CODE_GENERAL_PUBLISH_POLICY_ERROR,
    message=MSG_CANNOT_GET_POLICY_VERSION_HISTORY,
)

CANNOT_DELETE_POLICIES_ERROR = ErrorType(
    code=CODE_GENERAL_DELETE_POLICIES_ERROR, message=MSG_CANNOT_DELETE_POLICIES
)

CANNOT_RESTORE_POLICY_ERROR = ErrorType(
    code=CODE_GENERAL_RESTORE_POLICY_ERROR, message=MSG_CANNOT_RESTORE_POLICY
)

CANNOT_GET_VERSION_PREVIEW_ERROR = ErrorType(
    code=CODE_GENERAL_RESTORE_POLICY_ERROR,
    message=MSG_CANNOT_GET_POLICY_VERSION_PREVIEW,
)

CANNOT_SAVE_POLICY_DOCUMENT_ERROR = ErrorType(
    code=CODE_GENERAL_SAVE_POLICY_DOCUMENT_ERROR,
    message=MSG_CANNOT_SAVE_POLICY_DOCUMENT,
)
