# Generated by Django 3.1.2 on 2021-03-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0012_adding_is_active_field'),
        ('coupon', '0001_audit_and_coupons_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='organization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coupons',
                to='organization.organization',
            ),
        ),
    ]
