# Generated by Django 3.1.2 on 2021-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coupon', '0002_add_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(
                help_text='For example: SOC 2 Type 1 Laika Compliance', max_length=100
            ),
        ),
    ]
