# Generated by Django 3.1.6 on 2021-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coupon', '0003_add_helper_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(
                help_text='For example: SOC 2 Type 1', max_length=100
            ),
        ),
    ]
