# Generated by Django 3.1.6 on 2021-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coupon', '0004_update_text_help_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(
                help_text=(
                    '[Audit Type] [Audit Firm Name] e.g SOC 2 Type 1 Laika Compliance'
                ),
                max_length=100,
            ),
        ),
    ]
