DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 50
ATTRIBUTES_TYPE = {
    'TEXT': 'TEXT',
    'NUMBER': 'NUMBER',
    'DATE': 'DATE',
    'USER': 'USER',
    'BOOLEAN': 'BOOLEAN',
    'SINGLE_SELECT': 'SINGLE_SELECT',
    'JSON': 'JSON',
}
