DEFAULT_CERTIFICATIONS = [
    'SOC 2 Type 1',
    'SOC 2 Type 2',
    'ISO 27001',
    'ISO 27001 v2013',
    'HIPAA',
    'EMEA EU GDPR',
    'PCI',
    'PCI DSS v3.2',
    'Laika Compliance Playbook',
    'Lending',
    'Americas Canada PIPEDA',
    'US FERPA',
    'US - CA CCPA',
]

MY_COMPLIANCE_CERTIFICATIONS = [
    'SOC 1',
    'SOC 2',
    'SOC 2 Security',
    'SOC 2 Privacy',
    'SOC 2 Availability',
    'SOC 2 Processing Integrity',
    'SOC 2 Confidentiality',
    'ISO 27001 (2013)',
    'ISO 27002 (2013)',
    'ISO 27701 (2019)',
    'ISO 27002 (2022)',
    'HIPAA Security',
    'HIPAA Privacy',
    'PCI DSS v3.2.1',
    'GDPR',
    'CCPA',
    'PIPEDA',
    'FERPA',
    'HIPAA',
]
