# Generated by Django 3.1.12 on 2022-03-04 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                   SELECT
                      g.id AS group_id, p.id AS permission_id 
                   FROM
                      public.auth_group g 
                      cross join
                         public.auth_permission p 
                      join django_content_type ct on ct.id = p.content_type_id 
                   WHERE
                      (
                         g.name = 'auditor_admin' or
                         g.name = 'auditor'
                      )
                      AND p.codename = 'add_requirement'
                        AND ct.app_label = 'fieldwork' and ct.model ='requirement'
                    )
                ON CONFLICT DO NOTHING;
                COMMIT;
            '''
        )
    ]
