# Generated by Django 3.1.12 on 2022-03-28 19:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import access_review.models
import laika.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('objects', '0035_organization_object_types_related_name'),
        ('organization', '0070_add_onboarding_response_model'),
        ('evidence', '0026_add_one_to_one_relationship_with_link'),
        ('vendor', '0030_add_very_high_risk_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('in_progress', 'In progress'), ('done', 'Done')],
                        default='in_progress',
                        max_length=32,
                    ),
                ),
                ('notes', models.TextField(blank=True, default='')),
                (
                    'final_report',
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=access_review.models.access_review_upload_directory,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_reviews',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAccessOwner',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('email', models.EmailField(max_length=254)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='external_access_owners',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AccessReviewVendor',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('integration', 'Integration'),
                            ('sso', 'Single Sign-On'),
                            ('manual', 'Manual'),
                        ],
                        default='integration',
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_started', 'Not started'),
                            ('in_progress', 'In progress'),
                            ('completed', 'Completed'),
                        ],
                        default='not_started',
                        max_length=32,
                    ),
                ),
                (
                    'access_review',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='access_review.accessreview',
                    ),
                ),
                (
                    'reviewer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AccessReviewPreference',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'frequency',
                    models.CharField(
                        choices=[('quarterly', 'Quarterly'), ('monthly', 'Monthly')],
                        default='quarterly',
                        max_length=32,
                    ),
                ),
                (
                    'criticality',
                    models.CharField(
                        choices=[
                            ('high', 'High'),
                            ('medium', 'Medium'),
                            ('low', 'Low'),
                        ],
                        default='low',
                        max_length=32,
                    ),
                ),
                (
                    'organization',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_review_preference',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AccessReviewObject',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'review_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('updated', 'Updated'),
                            ('confirmed', 'Confirmed'),
                            ('denied', 'Denied'),
                        ],
                        default='pending',
                        max_length=32,
                    ),
                ),
                ('notes', models.TextField(blank=True, default='')),
                ('original_access', models.JSONField(blank=True, null=True)),
                ('final_snapshot', models.JSONField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                (
                    'access_review_vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='access_review.accessreviewvendor',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='evidence.evidence',
                    ),
                ),
                (
                    'laika_object',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='objects.laikaobject',
                    ),
                ),
            ],
        ),
    ]
