# Generated by Django 3.1.12 on 2022-04-04 17:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0030_add_very_high_risk_rating'),
        ('access_review', '0001_creating_models_for_access_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewVendorPreference',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('in_scope', models.BooleanField(default=False)),
                (
                    'organization_vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_review_vendor_preference',
                        to='vendor.organizationvendor',
                    ),
                ),
                ('reviewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
