# Generated by Django 3.1.12 on 2022-04-04 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0026_add_one_to_one_relationship_with_link'),
        ('access_review', '0002_creating_model_for_access_review_vendor_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessreviewvendor',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='accessreviewobject',
            name='evidence',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='evidence.evidence',
            ),
        ),
        migrations.AlterField(
            model_name='accessreviewvendorpreference',
            name='reviewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
