# Generated by Django 3.1.12 on 2022-04-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0003_evidence_can_be_null_and_reviewr_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessreviewpreference',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
