# Generated by Django 3.2.13 on 2022-05-10 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0004_add_due_date_to_access_review_preference'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                   SELECT
                      g.id AS group_id, p.id AS permission_id 
                   FROM
                      public.auth_group g 
                      cross join
                         public.auth_permission p 
                   WHERE
                      (
                         g.name ilike '%_admin' 
                         OR g.name ilike '%_super' 
                         OR g.name ilike '%_sales' 
                         OR g.name ilike '%_member'
                      )
                      AND p.codename = ANY (array [
                        'add_accessreview',
                        'add_accessreviewpreference',
                        'change_accessreviewvendorpreference',
                        'view_accessreviewpreference',
                        'view_accessreview']
                        )
                    )
                ON CONFLICT DO NOTHING;
                COMMIT;
            '''
        )
    ]
