# Generated by Django 3.2.13 on 2022-05-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0005_add_access_review_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessreview',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_progress', 'In progress'),
                    ('done', 'Done'),
                    ('canceled', 'Canceled'),
                ],
                default='in_progress',
                max_length=32,
            ),
        ),
    ]
