# Generated by Django 3.2.13 on 2022-06-06 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0006_add_canceled_status_to_access_review'),
    ]

    operations = [
        migrations.RunSQL(
            '''
    BEGIN;
    DELETE FROM public.auth_group_permissions WHERE permission_id in (
        SELECT
            id
        FROM
            public.auth_permission
        WHERE
            codename = ANY (
            array ['add_accessreview',
            'add_accessreviewpreference',
            'change_accessreviewvendorpreference',
            'view_accessreviewpreference',
            'view_accessreview']
            )
    );
    COMMIT;
    '''
        ),
        migrations.RunSQL(
            '''
    BEGIN;
    INSERT into
       public.auth_group_permissions (group_id, permission_id) (
       SELECT
          g.id AS group_id, p.id AS permission_id 
       FROM
          public.auth_group g 
          cross join
             public.auth_permission p 
       WHERE
          (
             g.name ilike 'premium_super' 
             OR g.name ilike 'premium_admin' 
             OR g.name ilike 'premium_member'
          )
          AND p.codename = ANY (array [
            'add_accessreview',
            'add_accessreviewpreference',
            'change_accessreviewvendorpreference',
            'view_accessreviewpreference',
            'view_accessreview',
            'change_accessreview']
            )
        )
    ON CONFLICT DO NOTHING;
    COMMIT;
    '''
        ),
    ]
