# Generated by Django 3.2.13 on 2022-06-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0007_update_access_review_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessreviewobject',
            name='review_status',
            field=models.CharField(
                choices=[
                    ('modified', 'Modified'),
                    ('revoked', 'Revoked'),
                    ('unchanged', 'Unchanged'),
                ],
                default='unchanged',
                max_length=32,
            ),
        ),
    ]
