# Generated by Django 3.2.13 on 2022-06-23 21:24

import django.db.models.deletion
from django.db import migrations, models

import access_review.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0040_update_lo_required_fields'),
        ('access_review', '0008_update_statuses_for_access_review_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessreviewobject',
            name='latest_access',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessreviewobject',
            name='evidence',
            field=models.FileField(
                blank=True,
                null=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=access_review.models.access_review_object_upload_directory,
            ),
        ),
        migrations.AlterField(
            model_name='accessreviewobject',
            name='laika_object',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='access_review_objects',
                to='objects.laikaobject',
            ),
        ),
    ]
