# Generated by Django 3.2.13 on 2022-06-16 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_review', '0009_updating_fields_in_access_review_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewUserEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event',
                    models.TextField(
                        choices=[('help_modal_opened', 'Help Modal Opened')]
                    ),
                ),
                (
                    'access_review',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='access_review.accessreview',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
