# Generated by Django 3.2.13 on 2022-07-07 00:28

from django.db import migrations, models

import access_review.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0012_change_access_review_vendor_permision'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessreviewobject',
            name='note_attachment',
            field=models.FileField(
                blank=True,
                null=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=access_review.models.access_review_object_note_attachment_upload_directory,
            ),
        ),
    ]
