# Generated by Django 3.2.14 on 2022-08-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0022_update_alert_choices_access_review'),
        ('access_review', '0013_add_note_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'access_review',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_review_alert',
                        to='access_review.accessreview',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_review_alert',
                        to='alert.alert',
                    ),
                ),
            ],
        ),
    ]
