# Generated by Django 3.2.14 on 2022-07-29 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_review', '0014_update_alert_choices_access_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessreview',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='access_reviews_created',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
