# Generated by Django 3.2.15 on 2022-08-24 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access_review', '0015_adding_created_by_to_access_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessreviewuserevent',
            name='access_review_objects',
            field=models.ManyToManyField(
                related_name='access_review_user_events',
                to='access_review.AccessReviewObject',
            ),
        ),
        migrations.AddField(
            model_name='accessreviewuserevent',
            name='access_review_vendor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='access_review.accessreviewvendor',
            ),
        ),
        migrations.AddField(
            model_name='accessreviewuserevent',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessreviewuserevent',
            name='event',
            field=models.TextField(
                choices=[
                    ('help_modal_opened', 'Help Modal Opened'),
                    ('cancel_access_review', 'Cancel Access Review'),
                    ('create_access_review', 'Create Access Review'),
                    ('complete_access_review', 'Complete Access Review'),
                    ('complete_access_review_vendor', 'Complete Access Review Vendor'),
                    ('reviewed_accounts', 'Reviewed Accounts'),
                    ('unreviewed_accounts', 'Unreviewed Accounts'),
                    ('create_or_update_accounts', 'Create Or Update Accounts Notes'),
                    ('add_accounts_attachment', 'Add Account Attachment'),
                    ('clear_accounts_attachment', 'Clear Account Attachment'),
                ]
            ),
        ),
    ]
