# Generated by Django 3.2.15 on 2022-09-15 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vendor', '0031_very_high_to_critical_risk'),
        ('access_review', '0016_add_event_fields_to_access_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessreviewvendorpreference',
            name='organization_vendor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='access_review_vendor_preference',
                to='vendor.organizationvendor',
            ),
        ),
    ]
