# Generated by Django 3.1.12 on 2021-10-25 03:43

import dateutil.parser
from django.db import migrations, models


class Migration(migrations.Migration):
    def add_announcement(apps, schema_editor):
        Announcement = apps.get_model('announcement', 'Announcement')

        announcement = {
            'title': 'Series B announcement',
            'content': (
                '<span role="img">🎉🎉🎉</span> We raised a $35MM Series B with JPMorgan'
                ' and PayPal Ventures! <span role="img">🎉🎉🎉</span>'
            ),
            'url': 'https://www.heylaika.com/blog/laika-announcements/series-b',
            'publish_start_date': dateutil.parser.parse(
                '2021-11-02 00:00:00.000000 +00:00'
            ),
            'publish_end_date': dateutil.parser.parse(
                '2021-11-10 00:00:00.000000 +00:00'
            ),
        }

        Announcement.objects.create(**announcement)

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('publish_start_date', models.DateTimeField()),
                ('publish_end_date', models.DateTimeField()),
            ],
        ),
        migrations.RunPython(add_announcement),
    ]
