# Generated by Django 3.0.3 on 2020-04-16 05:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0002_update_program_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='badge',
            field=models.CharField(
                blank=True,
                choices=[
                    ('technical_badge', 'technical_badge'),
                    ('default', 'default'),
                ],
                default='default',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='how_to_guide',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
