# Generated by Django 3.0.3 on 2020-05-15 20:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0002_rename_evidence_file_column'),
        ('program', '0003_update_subtask_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyTask',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LegacyTaskEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='evidence.Evidence',
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='program.LegacyTask',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'evidence',
            },
        ),
        migrations.AddField(
            model_name='legacytask',
            name='evidence',
            field=models.ManyToManyField(
                related_name='task',
                through='program.LegacyTaskEvidence',
                to='evidence.Evidence',
            ),
        ),
        migrations.AddField(
            model_name='legacytask',
            name='organization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='legacy_task',
                to='organization.Organization',
            ),
        ),
    ]
