# Generated by Django 3.0.3 on 2020-05-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0003_add_additional_evidence_fields'),
        ('program', '0004_create_legacy_task_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacytask',
            name='evidence',
            field=models.ManyToManyField(
                related_name='legacy_task',
                through='program.LegacyTaskEvidence',
                to='evidence.Evidence',
            ),
        ),
        migrations.AlterField(
            model_name='legacytaskevidence',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='legacy_task_evidence',
                to='program.LegacyTask',
            ),
        ),
    ]
