# Generated by Django 3.0.7 on 2020-07-10 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0006_update_certifications_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='programcertification',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='subtaskcertification',
            name='certification',
        ),
        migrations.DeleteModel(
            name='ProgramCertification',
        ),
        migrations.DeleteModel(
            name='SubtaskCertification',
        ),
    ]
