# Generated by Django 3.0.7 on 2020-07-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    CERTIFICATION_CERTIFICATION = 'certification.Certification'

    dependencies = [
        ('program', '0007_remove_certification_fks'),
        ('certification', '0004_update_certification_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskCertification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'certification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=CERTIFICATION_CERTIFICATION,
                    ),
                ),
                (
                    'subtask',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='program.SubTask',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='ProgramCertification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_locked', models.BooleanField(default=False)),
                (
                    'certification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=CERTIFICATION_CERTIFICATION,
                    ),
                ),
                (
                    'program',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='program.Program',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'certifications',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='certifications',
            field=models.ManyToManyField(
                related_name='programs',
                through='program.ProgramCertification',
                to=CERTIFICATION_CERTIFICATION,
            ),
        ),
        migrations.AddField(
            model_name='subtask',
            name='certifications',
            field=models.ManyToManyField(
                related_name='subtasks',
                through='program.SubtaskCertification',
                to=CERTIFICATION_CERTIFICATION,
            ),
        ),
    ]
