# Generated by Django 3.0.7 on 2020-07-23 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0005_add_unlocked_organization_certifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0008_new_certification_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskCertificationSection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'certification_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='certification.CertificationSection',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'certification_sections',
            },
        ),
        migrations.RemoveField(
            model_name='subtaskcertification',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='subtaskcertification',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='taskcontrol',
            name='control',
        ),
        migrations.RemoveField(
            model_name='taskcontrol',
            name='task',
        ),
        migrations.RemoveField(
            model_name='program',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='task',
            name='controls',
        ),
        migrations.AddField(
            model_name='task',
            name='implementation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_lead',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='program_led',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='ProgramCertification',
        ),
        migrations.DeleteModel(
            name='SubtaskCertification',
        ),
        migrations.DeleteModel(
            name='TaskControl',
        ),
        migrations.AddField(
            model_name='subtaskcertificationsection',
            name='subtask',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='program.SubTask'
            ),
        ),
        migrations.AddField(
            model_name='subtask',
            name='certification_sections',
            field=models.ManyToManyField(
                related_name='subtasks',
                through='program.SubtaskCertificationSection',
                to='certification.CertificationSection',
            ),
        ),
    ]
