# Generated by Django 3.0.7 on 2020-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0009_update_program_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='completed',
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('completed', 'Completed'),
                    ('not_applicable', 'Not Applicable'),
                    ('not_started', 'Not Started'),
                ],
                default='not_started',
                max_length=50,
            ),
        ),
    ]
