# Generated by Django 3.0.7 on 2020-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0010_add_subtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='badge',
        ),
        migrations.AddField(
            model_name='subtask',
            name='badges',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='tier',
            field=models.CharField(
                choices=[
                    ('getting_started', 'Getting Started'),
                    ('next_steps', 'Next Steps'),
                    ('finish_line', 'Finish Line'),
                ],
                default='getting_started',
                max_length=255,
            ),
        ),
    ]
