# Generated by Django 3.0.7 on 2020-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0011_add_tier_add_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
