# Generated by Django 3.0.7 on 2020-08-20 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0012_add_overview_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ('sort_index',)},
        ),
        migrations.AlterField(
            model_name='subtask',
            name='assignee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subtask_assignee',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='priority',
            field=models.CharField(
                choices=[
                    ('required', 'Required'),
                    ('key', 'Key'),
                    ('recommended', 'Recommended'),
                ],
                default='required',
                max_length=50,
            ),
        ),
    ]
