# Generated by Django 3.0.7 on 2020-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0013_update_subtask_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_system_subtask',
            field=models.BooleanField(default=True),
        ),
    ]
