# Generated by Django 3.0.7 on 2020-08-31 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0014_subtask_is_system_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='all_subtasks',
                to='program.Task',
            ),
        ),
    ]
