# Generated by Django 3.0.7 on 2020-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0015_rename_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
