# Generated by Django 3.0.7 on 2020-09-09 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0016_update_program_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='evidence',
        ),
        migrations.DeleteModel(
            name='SubtaskEvidence',
        ),
    ]
