# Generated by Django 3.0.7 on 2020-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0017_remove_subtask_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
