# Generated by Django 3.0.7 on 2020-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0018_update_due_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='complexity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='complexity_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
