# Generated by Django 3.0.7 on 2020-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0019_add_complexity_fields_to_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='animated_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='static_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
