# Generated by Django 3.0.7 on 2020-10-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0021_adding_new_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
