# Generated by Django 3.1.2 on 2020-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0022_subtask_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='how_to_guide',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
