# Generated by Django 3.1.2 on 2020-12-10 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0024_add_comment_task_relation'),
        ('feature', '0002_enable_legacy_policy_for_all_orgs'),
    ]

    def add_comments_feature_flag_for_all_organizations(apps, schema):
        Organization = apps.get_model('organization', 'Organization')
        Flag = apps.get_model('feature', 'Flag')

        all_organizations = Organization.objects.all()

        for organization in all_organizations:
            Flag.objects.get_or_create(
                name='commentsFeatureFlag',
                organization=organization,
                defaults={'is_enabled': False},
            )

    operations = [migrations.RunPython(add_comments_feature_flag_for_all_organizations)]
