# Generated by Django 3.1.2 on 2020-12-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0001_add_comments_models'),
        ('program', '0023_migrate_json_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='comment.comment',
                    ),
                ),
                (
                    'subtask',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='program.subtask',
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='task_comments',
                        to='program.task',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(
                related_name='tasks',
                through='program.TaskComment',
                to='comment.Comment',
            ),
        ),
    ]
