# Generated by Django 3.1.2 on 2020-12-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0024_set_default_false_comments_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='subtask',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='program.subtask',
            ),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task',
                to='comment.comment',
            ),
        ),
    ]
