# Generated by Django 3.1.2 on 2020-12-16 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0025_making_comment_subtask_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={
                'permissions': [
                    (
                        'change_task_implementation_notes',
                        'Can change task implementation notes',
                    ),
                    ('add_task_comment', 'Can add task comment'),
                    ('change_task_comment', 'Can change task comment'),
                    ('delete_task_comment', 'Can delete task comment'),
                    ('view_task_comment', 'Can view task comment'),
                ]
            },
        ),
    ]
