# Generated by Django 3.1.2 on 2020-12-16 19:33

from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_perms(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0026_add_task_commenting_permissions'),
    ]

    operations = [
        # This is because the migration didn't get the permissions created in previous migration
        migrations.RunPython(create_perms),
        migrations.RunSQL(
            '''
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike '%_admin' 
                     OR g.name ilike '%_super' 
                     OR g.name ilike '%_member'
                  )
                  AND p.codename = ANY (array [
                    'add_task_comment',
                    'change_task_comment',
                    'delete_task_comment',
                    'view_task_comment']
                    )
                )
                  ON CONFLICT DO NOTHING;
        '''
        ),
    ]
