# Generated by Django 3.1.2 on 2020-12-29 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0001_initial_version_drive'),
        ('program', '0027_add_task_comment_permissions_to_groups'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE OR REPLACE VIEW tags_by_subtasks_evidence AS
                WITH tags_by_subtasks_evidence(organization_id, subtask_id, subtask_tag_id, 
                    program_id, evidence_id) AS (
                        SELECT drive.organization_id AS organization_id,
                        CAST(evidence_subtasks.id AS text) AS subtask_id,
                        CAST(subtask_tags.id AS text) AS subtask_tag_id,
                        CAST(pp.id AS text) AS program_id,
                        evidence.id AS evidence_id
                        FROM drive_driveevidence drive_evidence
                        INNER JOIN drive_drive drive 
                        ON drive.id = drive_evidence.drive_id 
                        INNER JOIN evidence_evidence evidence 
                        ON evidence.id = drive_evidence.evidence_id
                        LEFT JOIN evidence_systemtagevidence system_tag_evidence 
                        ON evidence.id = system_tag_evidence.evidence_id
                        INNER JOIN tag_tag system_tags 
                        ON system_tags.id = system_tag_evidence.tag_id
                        LEFT JOIN program_subtask evidence_subtasks 
                        ON evidence_subtasks.id = system_tags."name"::uuid
                        LEFT JOIN program_subtasktag evidence_subtask_tags 
                        ON evidence_subtask_tags.subtask_id = evidence_subtasks.id
                        LEFT JOIN tag_tag subtask_tags 
                        ON subtask_tags.id = evidence_subtask_tags.tag_id
                        LEFT JOIN program_task pt 
                        ON pt.id = evidence_subtasks.task_id 
                        LEFT JOIN program_program pp 
                        ON pp.id = pt.program_id 
                )
                SELECT ROW_NUMBER() OVER (ORDER BY subtasks_evidence_tags.evidence_id) 
                    AS id, subtasks_evidence_tags.* 
                FROM tags_by_subtasks_evidence subtasks_evidence_tags
                ORDER BY subtasks_evidence_tags.evidence_id
            '''
        ),
    ]
