# Generated by Django 3.1.2 on 2021-01-12 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0028_tags_by_subtasks_evidence'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            DROP VIEW IF EXISTS tags_by_subtasks_evidence;
        '''
        )
    ]
