# Generated by Django 3.1.2 on 2021-02-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0003_add_alert_permissions_to_group'),
        ('program', '0032_add_default_permissions_for_apofpr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subtask_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'subtask',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subtask',
                        to='program.subtask',
                    ),
                ),
            ],
        ),
    ]
