# Generated by Django 3.1.2 on 2021-03-16 19:48

from django.db import migrations, models

from program.utils.task_numbers import populate_subtask_numbers, populate_task_numbers


class Migration(migrations.Migration):
    def populate_task_numbers(apps, schema):
        Task = apps.get_model('program', 'Task')
        populate_task_numbers(Task)

    def populate_subtasks_number(apps, schema):
        SubTask = apps.get_model('program', 'SubTask')
        populate_subtask_numbers(SubTask)

    dependencies = [
        ('program', '0035_create_number_and_initials_for_subtask'),
    ]

    operations = [
        migrations.RunPython(populate_task_numbers),
        migrations.RunPython(populate_subtasks_number),
    ]
