# Generated by Django 3.1.2 on 2021-03-23 17:29

from django.db import migrations

from program.utils.task_numbers import populate_subtask_numbers, populate_task_numbers


class Migration(migrations.Migration):
    def populate_task_numbers(apps, schema):
        Task = apps.get_model('program', 'Task')
        populate_task_numbers(Task)

    def populate_subtasks_number(apps, schema):
        SubTask = apps.get_model('program', 'SubTask')
        populate_subtask_numbers(SubTask)

    dependencies = [
        ('program', '0036_populate_task_and_subtask_numbers'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            UPDATE program_task
            set number = 0,
            customer_identifier = '';
            UPDATE program_subtask
            set number = 0,
            customer_identifier = '';
        '''
        )
    ]
