# Generated by Django 3.1.2 on 2021-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0040_populate_task_and_subtasks_number_not_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('completed', 'Completed'),
                    ('not_applicable', 'Not Applicable'),
                    ('in_progress', 'In Progress'),
                    ('not_started', 'Not Started'),
                ],
                default='not_started',
                max_length=50,
            ),
        ),
    ]
