# Generated by Django 3.1.6 on 2021-06-07 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0041_new_in_progress_status_for_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacytaskevidence',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='legacytaskevidence',
            name='task',
        ),
        migrations.DeleteModel(
            name='LegacyTask',
        ),
        migrations.DeleteModel(
            name='LegacyTaskEvidence',
        ),
    ]
