# Generated by Django 3.1.12 on 2021-07-15 12:56

from django.db import migrations

from laika.constants import CATEGORIES


def create_tags(apps, tag_name):
    tags_model = apps.get_model('tag', 'Tag')
    organization_model = apps.get_model('organization', 'Organization')
    for organization in organization_model.objects.all():
        tags_model.objects.get_or_create(
            name=tag_name,
            organization=organization,
        )


def create_categories_tags(apps, schema_editor):
    for category in CATEGORIES:
        create_tags(apps, category[0])


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0042_remove_legacy_task'),
    ]

    operations = [migrations.RunPython(create_categories_tags)]
