# Generated by Django 3.1.12 ON 2021-07-15 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0043_add_categories_as_tags'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT INTO public.evidence_tagevidence (tag_id, evidence_id)
                    SELECT distinct tt.id AS tag_id, evi.id AS evidence_id
                    FROM public.program_task pt
                    INNER JOIN public.program_subtask ps
                    ON ps.task_id = pt.id
                    INNER JOIN public.program_program pp
                    ON pp.id = pt.program_id
                    INNER JOIN public.tag_tag tt
                    ON tt.organization_id = pp.organization_id
                    AND pt.category = tt.name
                    INNER JOIN (
                        SELECT ee.id, ee.organization_id, ps2.id AS subtask_id, ps2.task_id
                        FROM public.evidence_evidence ee
                        INNER JOIN public.evidence_systemtagevidence es
                        ON es.evidence_id = ee.id
                        INNER JOIN public.tag_tag tt
                        ON es.tag_id = tt.id
                        INNER JOIN public.program_subtask ps2
                        ON ps2.id::varchar = tt."name"
                    ) evi
                    ON evi.organization_id = pp.organization_id
                    AND evi.subtask_id = ps.id
                    AND pt.id = evi.task_id

                ON CONFLICT DO NOTHING;
                COMMIT;
            '''
        )
    ]
