# Generated by Django 3.1.12 on 2021-11-02 16:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program', '0044_add_category_tag_to_existing_subtasks_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        )
    ]
