# Generated by Django 3.1.12 on 2022-02-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0008_update_recurrent_ai_to_be_not_required'),
        ('program', '0046_update_subtask_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='action_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='action_item',
                to='action_item.actionitem',
            ),
        ),
    ]
