# Generated by Django 3.2.15 on 2022-08-31 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'action_item',
            '0011_update_action_items_to_be_not_recurrent_when_recurrent_schedule_is_empty',
        ),
        ('program', '0050_subtask_migration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='action_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='subtasks',
                to='action_item.actionitem',
            ),
        ),
    ]
