# Generated by Django 3.1.2 on 2020-11-17 19:29

import django.db.models.deletion
from django.db import migrations, models

import laika.storage
import report.models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0008_organization_logo'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=512)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=report.models.template_file_directory_path,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='templates',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
    ]
