# Generated by Django 3.1.2 on 2020-11-26 22:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0002_template_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='display_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
