# Generated by Django 3.1.2 on 2020-11-30 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('link', '0001_link_model'),
        ('report', '0003_add_display_id_and_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='link',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='report',
                to='link.link',
            ),
        ),
    ]
