# Generated by Django 3.1.2 on 2020-12-02 20:49

import django.db.models.deletion
from django.db import migrations, models

import laika.storage
import report.models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0004_report_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(
                blank=True,
                max_length=1024,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=report.models.report_file_directory_path,
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='html_file',
            field=models.FileField(
                blank=True,
                max_length=1024,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=report.models.report_file_directory_path,
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reports',
                to='report.template',
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
