# Generated by Django 3.1.2 on 2020-12-02 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0005_add_template_to_report'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike '%_admin' 
                     OR g.name ilike '%_super' 
                     OR g.name ilike '%_sales' 
                     OR g.name ilike '%_member'
                  )
                  AND p.codename = 'add_report' ) 
                  ON CONFLICT DO NOTHING;
        '''
        ),
    ]
