# Generated by Django 3.1.2 on 2021-03-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0006_add_create_report_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
