# Generated by Django 3.1.2 on 2021-03-06 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0007_update_report_is_deleted_column'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                    public.auth_group_permissions (group_id, permission_id) (
                    SELECT
                        g.id AS group_id, p.id AS permission_id 
                    FROM
                        public.auth_group g 
                        cross join
                            public.auth_permission p 
                    WHERE 
                        g.name in (
                        'premium_admin',
                        'teaser_admin',
                        'starter_admin',
                        'premium_super',
                        'teaser_super',
                        'starter_super',
                        'premium_super'
                        
                        )
                        AND p.codename = 'delete_report'
                    )
      
                ON CONFLICT DO NOTHING;
                COMMIT;
            '''
        )
    ]
