# Generated by Django 3.1.6 on 2021-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0008_add_delete_report_permission_to_admin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
