# Generated by Django 3.0.3 on 2020-03-12 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import concierge.models
import laika.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_auto_20200304_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=concierge.models.concierge_request_directory_path,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('t', 'To Do'), ('p', 'In Progress'), ('d', 'Done')],
                        default='t',
                        max_length=1,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('policy', 'Draft a New Policy Document'),
                            ('ddq', 'Help with a Diligence Questionnaire'),
                            (
                                'time',
                                'Schedule Time with a Laika Compliance & Security'
                                ' Expert',
                            ),
                            ('risk_assesment', 'Schedule a Risk Assessment'),
                        ],
                        max_length=14,
                    ),
                ),
                ('description', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='concierge_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='concierge_requests',
                        to='organization.Organization',
                    ),
                ),
            ],
        ),
    ]
