# Generated by Django 3.0.3 on 2020-04-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0005_auto_20200304_1700'),
        ('concierge', '0001_concierge_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergerequest',
            name='organization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='concierge_requests',
                to='organization.Organization',
            ),
        ),
    ]
