# Generated by Django 3.0.3 on 2020-05-14 22:09

from django.db import migrations, models


def migrate_status_options(apps, schema_editor):
    ConciergeRequest = apps.get_model('concierge', 'ConciergeRequest')

    request_mapping = {'t': 'REQUESTED', 'd': 'CLOSED'}
    for request in ConciergeRequest.objects.all():
        if request.status not in request_mapping:
            continue

        request.status = request_mapping.get(request.status)
        request.save()


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0002_auto_20200421_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conciergerequest', old_name='type', new_name='request_type'
        ),
        migrations.AlterField(
            model_name='conciergerequest',
            name='request_type',
            field=models.CharField(
                choices=[
                    ('policy', 'Draft a New Policy Document'),
                    ('ddq', 'Help with a Diligence Questionnaire'),
                    ('time', 'Schedule Time with a Laika Compliance & Security Expert'),
                    ('risk_assesment', 'Schedule a Risk Assessment'),
                ],
                default='REQUESTED',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='conciergerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conciergerequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('REQUESTED', 'Requested'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED', 'Completed'),
                    ('CLOSED', 'Closed'),
                ],
                default='REQUESTED',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='conciergerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(migrate_status_options),
    ]
