# Generated by Django 3.0.7 on 2020-09-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0003_auto_20200514_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergerequest',
            name='request_type',
            field=models.CharField(
                choices=[
                    ('policy', 'Draft a New Policy Document'),
                    ('ddq', 'Help with a Diligence Questionnaire'),
                    ('time', 'Schedule Time with a Laika Compliance & Security Expert'),
                    ('risk_assesment', 'Schedule a Risk Assessment'),
                    ('request_unlock', 'Unlock Certification'),
                ],
                default='REQUESTED',
                max_length=50,
            ),
        ),
    ]
