# Generated by Django 3.0.7 on 2020-10-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0004_add_new_concierge_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergerequest',
            name='request_type',
            field=models.CharField(
                choices=[
                    ('policy', 'Draft a New Policy Document'),
                    ('ddq', 'Help with a Diligence Questionnaire'),
                    ('time', 'Schedule Time with a Laika Compliance & Security Expert'),
                    ('risk_assesment', 'Schedule a Risk Assessment'),
                    ('request_unlock', 'Unlock Certification'),
                    ('request_integration', 'Request Integration'),
                ],
                default='REQUESTED',
                max_length=50,
            ),
        ),
    ]
