# Generated by Django 3.0.7 on 2020-10-21 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0005_add_integration_request_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciergerequest',
            options={
                'permissions': [
                    (
                        'change_conciergerequest_status',
                        'Can change concierge request status',
                    )
                ]
            },
        ),
    ]
