# Generated by Django 3.1.12 on 2021-12-21 00:26

from django.db import migrations


def create_concierge_group_with_permissions(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')
    g, _ = group.objects.get_or_create(name='concierge')
    permissions_for_open_api_admin = [
        'view_concierge',
        'add_concierge',
        'change_concierge',
        'delete_concierge',
        'control.batch_delete_control',
    ]
    permissions = permission.objects.filter(codename__in=permissions_for_open_api_admin)
    g.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0008_add_concierge_permissions_to_group'),
    ]

    operations = [migrations.RunPython(create_concierge_group_with_permissions)]
