# Generated by Django 3.1.12 on 2022-01-12 17:30

from django.db import migrations


def add_permissions_to_concierge_group(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')
    concierge_group = group.objects.get(name='concierge')
    permissions_for_roadmap = [
        'add_roadmap',
        'view_roadmap',
        'change_roadmap',
        'delete_roadmap',
        'add_controlgroup',
        'view_controlgroup',
        'change_controlgroup',
        'delete_controlgroup',
        'change_control',
        'batch_delete_control',
    ]
    permissions = permission.objects.filter(
        content_type__app_label='control', codename__in=permissions_for_roadmap
    )
    concierge_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0009_set_concierge_group_and_permissions'),
    ]

    operations = [migrations.RunPython(add_permissions_to_concierge_group)]
