# Generated by Django 3.2.12 on 2022-04-22 21:12

from django.db import migrations


def add_permissions_to_concierge_group(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')
    concierge_group = group.objects.get(name='concierge')
    permissions_for_control_prescription = ['view_controlblueprint']
    permissions = permission.objects.filter(
        content_type__app_label='blueprint',
        codename__in=permissions_for_control_prescription,
    )
    concierge_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0010_set_permissions_to_concierge_group'),
    ]

    operations = [migrations.RunPython(add_permissions_to_concierge_group)]
