# Generated by Django 3.0.3 on 2020-06-03 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import certification.models
import laika.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    'logo',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PublicMediaStorage(),
                        upload_to=certification.models.certification_logo_directory_path,
                    ),
                ),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('regex', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationSection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'certification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='certification.Certification',
                    ),
                ),
            ],
        ),
    ]
