# Generated by Django 3.0.3 on 2020-05-29 20:57
from django.db import migrations


def migrate_vendor_certifications_to_certifications(apps, schema_editor):
    VendorCertification = apps.get_model('vendor', 'Certification')
    Certification = apps.get_model('certification', 'Certification')

    for c in VendorCertification.objects.all():
        Certification.objects.create(
            name=c.name,
            logo=c.logo,
            code=c.code,
            description=c.description,
            regex=c.regex,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0001_initial'),
        ('vendor', '0002_create_system_vendors'),
    ]

    operations = [migrations.RunPython(migrate_vendor_certifications_to_certifications)]
