# Generated by Django 3.0.7 on 2020-07-10 18:25

from django.db import migrations, models


def fill_ids(apps, schema_editor):
    Certification = apps.get_model('certification', 'Certification')
    for id, cert in enumerate(Certification.objects.all()):
        cert.id = id + 1
        cert.tmp_name = cert.name
        cert.save()


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0002_migrate_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certification',
            name='tmp_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(fill_ids),
    ]
