# Generated by Django 3.0.7 on 2020-07-10 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0003_add_id_to_certifications'),
        ('control', '0009_remove_certification_fks'),
        ('program', '0007_remove_certification_fks'),
        ('vendor', '0013_remove_certification_fks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificationSection',
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='certification',
            name='id',
        ),
        migrations.AddField(
            model_name='certification',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        migrations.RemoveField(
            model_name='certification',
            name='tmp_name',
        ),
        migrations.CreateModel(
            name='CertificationSection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'certification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='certification.Certification',
                    ),
                ),
            ],
        ),
    ]
