# Generated by Django 3.0.7 on 2020-07-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0006_auto_20200421_1655'),
        ('certification', '0004_update_certification_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationsection',
            name='certification',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sections',
                to='certification.Certification',
            ),
        ),
        migrations.AlterField(
            model_name='certificationsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UnlockedOrganizationCertification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'certification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='certification.Certification',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='certifications',
                        to='organization.Organization',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'certifications',
            },
        ),
    ]
