# Generated by Django 3.0.7 on 2020-08-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0007_DateTimeField_instead_of_DateField'),
        ('certification', '0005_add_unlocked_organization_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockedorganizationcertification',
            name='certification',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='unlocked_organizations',
                to='certification.Certification',
            ),
        ),
        migrations.AlterField(
            model_name='unlockedorganizationcertification',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='unlocked_certifications',
                to='organization.Organization',
            ),
        ),
    ]
