# Generated by Django 3.0.7 on 2020-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0006_rename_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='regex',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
