# Generated by Django 3.1.12 on 2021-12-06 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0007_update_regex_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificationsection',
            unique_together={('name', 'certification')},
        ),
    ]
