# Generated by Django 3.1.12 on 2022-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0010_certification_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='sort_index',
            field=models.IntegerField(blank=True, default=9999999, null=True),
        ),
    ]
