# Generated by Django 3.1.12 on 2022-01-17 21:29

from django.db import migrations

CERTIFICATION_NAMES = [
    'SOC 2 Security',
    'SOC 2 Availability',
    'SOC 2 Confidentiality',
    'SOC 2 Processing Integrity',
    'SOC 2 Privacy',
    'ISO 27001 (2013)',
    'ISO 27002 (2013)',
    'HIPAA Security',
    'HIPAA Privacy',
    'PCI DSS v3.2.1',
    'GDPR',
    'CCPA',
    'PIPEDA',
    'FERPA',
    'SOC 2 Type 1',
    'SOC 2 Type 2',
    'ISO 27001',
    'HIPAA',
    'EMEA EU GDPR',
    'PCI DSS v3.2',
    'Lending',
    'Americas Canada PIPEDA',
    'US FERPA',
    'US - CA CCPA',
]


def set_default_certifications_and_order(apps, schema_editor):
    Certification = apps.get_model('certification', 'Certification')

    for index, cert_name in enumerate(CERTIFICATION_NAMES):
        cert = Certification.objects.filter(name=cert_name).first()
        if cert:
            cert.is_visible = True
            cert.sort_index = index + 1
            cert.save()


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0011_certification_sort_index'),
    ]

    operations = [migrations.RunPython(set_default_certifications_and_order)]
