# Generated by Django 3.1.12 on 2022-02-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0012_set_default_visible_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='certificationsection',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
