# Generated by Django 3.1.12 on 2022-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0013_add_airtable_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='certificationsection',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
