# Generated by Django 3.2.13 on 2022-07-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0015_create_archived_unlocked_org_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='required_action_items',
            field=models.IntegerField(default=0),
        ),
    ]
