# Generated by Django 3.2.13 on 2022-07-11 18:47

from django.db import migrations


def add_required_action_items_value_per_certification(apps, schema_editor):
    required_ai_per_framework = {
        'SOC 2 Security': 302,
        'SOC 2 Availability': 2,
        'SOC 2 Confidentiality': 14,
        'SOC 2 Privacy': 41,
        'SOC 2 Processing Integrity': 24,
        'ISO 27001 (2013)': 114,
        'ISO 27002 (2013)': 450,
        'HIPAA Security': 379,
        'HIPAA Privacy': 104,
        'PCI DSS v3.2.1': 405,
        'GDPR': 85,
        'CCPA': 59,
        'PIPEDA': 83,
        'FERPA': 30,
        'ISO 27701': 343,
        'ISO 27001 (2022)': 55,
        'ISO 27002 (2022)': 240,
    }
    Certification = apps.get_model('certification', 'Certification')
    certifications = Certification.objects.filter(
        name__in=required_ai_per_framework.keys()
    )
    for certification in certifications:
        certification.required_action_items = required_ai_per_framework[
            certification.name
        ]
        certification.save()


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0016_certification_required_action_items'),
    ]

    operations = [
        migrations.RunPython(add_required_action_items_value_per_certification)
    ]
