# Generated by Django 3.2.15 on 2022-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'certification',
            '0017_add_required_action_items_estimation_per_certification',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedunlockedorganizationcertification',
            name='target_audit_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedunlockedorganizationcertification',
            name='target_audit_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlockedorganizationcertification',
            name='target_audit_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlockedorganizationcertification',
            name='target_audit_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
