# Generated by Django 3.0.7 on 2020-10-21 22:34

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('unique_action_item_id', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reference_url', models.TextField()),
                ('sort_index', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboard_view',
                'ordering': [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F('due_date'),
                        descending=True,
                        nulls_last=True,
                    ),
                    'sort_index',
                ],
                'permissions': [('view_dashboard', 'Can view dashboard')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItemMetadata',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('seen', models.BooleanField(default=False)),
                ('action_item_id', models.CharField(max_length=264, unique=True)),
                (
                    'assignee',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='action_item_metadata_assignee',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'action_item_metadata',
            },
        ),
    ]
