# Generated by Django 3.0.7 on 2020-10-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_create_dashboard_view'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE OR REPLACE VIEW dashboard_view AS
                SELECT row_number() OVER () AS id,
                   oo.id AS organization_id,
                   cast(ps.id AS text) AS unique_action_item_id,
                   ps.created_at,
                   ps.updated_at,
                   ps.assignee_id,
                   ps.due_date,
                   ps.completed_on,
                   ps.status,
                   'playbook_task' AS TYPE,
                   concat(pt.name) AS description,
                   concat('playbooks/', pp.id, '/', pt.id) AS reference_url,
                   ps.sort_index,
                   ps.group
            FROM program_subtask ps
            left join public.program_task pt
              ON pt.id = ps.task_id
            left join public.program_program pp
              ON pp.id = pt.program_id
            left join public.organization_organization oo
              ON oo.id = pp.organization_id
        '''
        )
    ]
