# Generated by Django 3.0.7 on 2020-11-03 17:19

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0004_modify_default_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={
                'managed': False,
                'ordering': [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F('due_date'), nulls_last=True
                    )
                ],
                'permissions': [('view_dashboard', 'Can view dashboard')],
            },
        ),
    ]
