# Generated by Django 3.1.2 on 2020-12-15 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_update_default_sort_to_asc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemmetadata',
            name='action_item_id',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterUniqueTogether(
            name='actionitemmetadata',
            unique_together={('action_item_id', 'assignee')},
        ),
    ]
