# Generated by Django 3.1.2 on 2021-01-20 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0006_modify_unique_fields_action_items'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE OR REPLACE RULE update_dashboard_view AS
                ON UPDATE TO dashboard_view
                DO INSTEAD
            UPDATE program_subtask SET assignee_id = new.assignee_id
            WHERE program_subtask.assignee_id = old.assignee_id;
        '''
        )
    ]
