# Generated by Django 3.1.12 on 2021-08-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0013_add_display_id_to_organization_monitor'),
        ('dashboard', '0010_add_description_to_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='organization_monitor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='monitor.organizationmonitor',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_subtype',
            field=models.CharField(
                choices=[
                    ('video', 'Video'),
                    ('training', 'Training'),
                    ('monitor', 'Monitor'),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(
                choices=[('quick_start', 'Quick Start'), ('monitor_task', 'Monitor')],
                max_length=50,
            ),
        ),
    ]
