# Generated by Django 3.1.12 on 2021-09-10 16:15

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.models import Q

from dashboard.models import Task


def add_permissions(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(Task)
    permission1 = Permission.objects.create(
        codename='change_checklist',
        name='Can Change Checklist',
        content_type=content_type,
    )
    permission2 = Permission.objects.create(
        codename='run_checklist',
        name='Can Run Checklist',
        content_type=content_type,
    )
    groups = Group.objects.filter(
        Q(name__contains='_admin') | Q(name__contains='_super')
    )
    for group in groups:
        group.permissions.add(permission1, permission2)


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0011_add_organization_monitor_to_user_task'),
    ]

    operations = [
        migrations.RunPython(add_permissions, reverse_code=migrations.RunPython.noop),
    ]
