# Generated by Django 3.1.12 on 2021-10-26 00:56

from django.db import migrations


def add_dashboard_to_viewer(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    dashboard_permission = Permission.objects.filter(codename__in=['view_dashboard'])
    groups = [
        'premium_super',
        'premium_admin',
        'premium_member',
        'premium_viewer',
        'premium_sales',
    ]
    for group in Group.objects.filter(name__in=groups):
        for permission in dashboard_permission:
            group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0012_adding_offboarding_permissions'),
    ]

    operations = [
        migrations.RunPython(
            add_dashboard_to_viewer, reverse_code=migrations.RunPython.noop
        )
    ]
