# Generated by Django 3.1.12 on 2021-11-26 17:51

from django.db import migrations

from action_item.constants import TYPE_QUICK_START
from action_item.models import ActionItemStatus
from dashboard.models import DefaultTask, UserTaskStatus


def migrate(apps, schema_editor):
    task_model = apps.get_model('dashboard', 'Task')
    action_item_model = apps.get_model('action_item', 'ActionItem')
    task_ids = task_model.objects.filter(
        name__in=[
            DefaultTask.LIBRARY_TRAINING_VIDEO,
            DefaultTask.DATAROOM_TRAINING_VIDEO,
            DefaultTask.COMPLETE_TRAININGS,
        ]
    ).values_list('id', flat=True)
    user_task_model = apps.get_model('dashboard', 'UserTask')
    action_items = user_task_model.objects.filter(task__in=task_ids)
    for item in action_items:
        if not item.assignee:
            item.delete()
            continue
        action_item = action_item_model(
            name=item.description,
            completion_date=item.completed_on,
            description=item.description,
            due_date=item.due_date,
            metadata={
                'referenceUrl': item.reference_url,
                'seen': item.seen,
                'subtaskText': '',
                'type': TYPE_QUICK_START,
                'subtype': item.task.task_subtype,
                'task_metadata': item.task.metadata,
            },
            status=(
                ActionItemStatus.NEW
                if item.status == UserTaskStatus.NOT_STARTED.value
                else item.status
            ),
        )
        action_item.save()
        action_item.assignees.add(item.assignee)
        item.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0015_use_referenceId'),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop),
    ]
