# Generated by Django 3.1.12 on 2021-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0017_add_user_task_to_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_subtype',
            field=models.CharField(choices=[('monitor', 'Monitor')], max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(
                choices=[('monitor_task', 'Monitor')], max_length=50
            ),
        ),
    ]
