# Generated by Django 3.2.15 on 2022-12-19 20:15

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0027_use_gin_index_to_filter_action_items_on_dashboardview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskView',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('model_id', models.UUIDField(blank=True, null=True)),
                ('unique_action_item_id', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reference_url', models.TextField()),
                ('sort_index', models.IntegerField()),
                (
                    'reference_id',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ('reference_name', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(blank=True, default=False)),
                ('is_recurrent', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'task_view',
                'ordering': [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F('due_date'), nulls_last=True
                    )
                ],
                'permissions': [('view_dashboard', 'Can view dashboard')],
                'managed': False,
            },
        ),
    ]
