# Generated by Django 3.0.3 on 2020-03-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0005_auto_20200304_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateField(auto_now_add=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tags',
                        to='organization.Organization',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(
                fields=['name', 'organization'], name='tag_tag_name_3c4027_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'organization')},
        ),
    ]
