# Generated by Django 3.1.2 on 2020-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0002_DateTimeField_instead_of_DateField'),
    ]

    DROP_IS_MANUAL_COLUMN = "ALTER TABLE tag_tag DROP COLUMN IF EXISTS is_manual"

    operations = [
        migrations.RunSQL(DROP_IS_MANUAL_COLUMN),
        migrations.AddField(
            model_name='tag',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
