# Generated by Django 3.1.6 on 2021-04-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0028_remove_onboarding_step_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('is_system_monitor', models.BooleanField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('error', 'Error'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'trigger_condition',
                    models.CharField(
                        choices=[
                            ('return_results', 'Return results'),
                            ('empty_results', 'Empty results'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'frequency',
                    models.CharField(choices=[('daily', 'Daily')], max_length=32),
                ),
                (
                    'runner_type',
                    models.CharField(
                        choices=[
                            ('laika_context', 'Laika Context'),
                            ('steampipe', 'Steampipe'),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMonitor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('active', models.BooleanField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('healthy', 'Healthy'),
                            ('triggered', 'Triggered'),
                            ('no_datasource', 'No Datasource'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'monitor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='monitor.monitor',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MonitorResult',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('healthy', 'Healthy'),
                            ('triggered', 'Triggered'),
                            ('no_datasource', 'No Datasource'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'organization_monitor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='monitor.organizationmonitor',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='organizationmonitor',
            constraint=models.UniqueConstraint(
                fields=('organization', 'monitor'), name='organization_monitor'
            ),
        ),
    ]
