# Generated by Django 3.1.2 on 2021-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0001_create_monitor_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='query',
            field=models.TextField(),
        ),
    ]
