# Generated by Django 3.1.6 on 2021-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0002_update_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='integration_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
