# Generated by Django 3.1.2 on 2021-05-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0003_add_integration_query_to_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='integration_query',
            new_name='validation_query',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='validation_query',
            field=models.TextField(
                blank=True, null=True, verbose_name='Datasource Validation Query'
            ),
        ),
    ]
