# Generated by Django 3.1.2 on 2021-05-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0012_adding_control_evidence'),
        ('monitor', '0004_rename_validation_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='control_references',
            field=models.TextField(
                blank=True, null=True, verbose_name='Control references'
            ),
        ),
        migrations.AddField(
            model_name='organizationmonitor',
            name='controls',
            field=models.ManyToManyField(
                blank=True, related_name='organization_monitors', to='control.Control'
            ),
        ),
        migrations.AlterField(
            model_name='organizationmonitor',
            name='monitor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organization_monitors',
                to='monitor.monitor',
            ),
        ),
    ]
