# Generated by Django 3.1.6 on 2021-05-31 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0041_drop_plan_table'),
        ('monitor', '0005_add_control_monitor_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='is_system_monitor',
        ),
        migrations.AddField(
            model_name='monitor',
            name='parent_monitor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='parent',
                to='monitor.monitor',
            ),
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(
                choices=[('system_monitor', 'System'), ('custom_monitor', 'Custom')],
                default='system_monitor',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='monitor',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='custom_monitors',
                to='organization.organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('monitor_type', 'custom_monitor'),
                        ('organization__isnull', False),
                    ),
                    models.Q(
                        ('monitor_type', 'system_monitor'),
                        ('organization__isnull', True),
                        ('parent_monitor__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='monitor_monitor_custom_type',
            ),
        ),
    ]
