# Generated by Django 3.1.6 on 2021-06-16 22:39

from django.db import migrations

from monitor.models import MonitorHealthCondition


def reverse_health_condition(apps, schema_editor):
    Monitor = apps.get_model('monitor', 'Monitor')
    empty_results = list(
        Monitor.objects.filter(
            health_condition=MonitorHealthCondition.RETURN_RESULTS
        ).values_list('id', flat=True)
    )
    return_results = list(
        Monitor.objects.filter(
            health_condition=MonitorHealthCondition.EMPTY_RESULTS
        ).values_list('id', flat=True)
    )

    Monitor.objects.filter(id__in=empty_results).update(
        health_condition=MonitorHealthCondition.EMPTY_RESULTS
    )
    Monitor.objects.filter(id__in=return_results).update(
        health_condition=MonitorHealthCondition.RETURN_RESULTS
    )


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0007_add_query_to_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='trigger_condition',
            new_name='health_condition',
        ),
        migrations.RunPython(reverse_health_condition),
    ]
