# Generated by Django 3.1.6 on 2021-06-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0003_tag_is_manual'),
        ('monitor', '0008_rename_trigger_condition_to_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='tag_references',
            field=models.TextField(
                blank=True, null=True, verbose_name='Tag references'
            ),
        ),
        migrations.AddField(
            model_name='organizationmonitor',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='organization_monitors', to='tag.Tag'
            ),
        ),
    ]
