# Generated by Django 3.1.12 on 2021-07-14 01:34

from django.db import migrations, models

from monitor.models import MonitorRunnerType


def update_deprecated_runner_type_choices(apps, schema_editor):
    Monitor = apps.get_model('monitor', 'Monitor')
    Monitor.objects.filter(runner_type='steampipe').update(
        runner_type=MonitorRunnerType.ON_DEMAND
    )


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0009_add_tags_to_organization_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='runner_type',
            field=models.CharField(
                choices=[
                    ('laika_context', 'Laika Context'),
                    ('on_demand', 'On Demand'),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(update_deprecated_runner_type_choices),
    ]
