# Generated by Django 3.1.6 on 2021-07-15 17:36

from django.db import migrations, models

from monitor.models import MonitorStatus


def update_error_status_to_inactive(apps, schema_editor):
    Monitor = apps.get_model('monitor', 'Monitor')
    Monitor.objects.filter(status='error').update(status=MonitorStatus.ACTIVE)


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0010_rename_runner_type_from_steampipe_to_on_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=32
            ),
        ),
        migrations.RunPython(update_error_status_to_inactive),
    ]
