# Generated by Django 3.1.12 on 2021-07-21 14:37

from django.db import migrations, models


def generate_sequence(apps, schema_editor):
    organization_monitor = apps.get_model('monitor', 'OrganizationMonitor')
    organization_monitors = organization_monitor.objects.order_by(
        'organization_id', 'id'
    )
    display_id = 1
    prev_org_id = None
    for om in organization_monitors:
        if prev_org_id != om.organization_id:
            prev_org_id = om.organization_id
            display_id = 1
        om.display_id = display_id
        om.save()
        display_id += 1


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0012_add_monitor_result_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmonitor',
            name='display_id',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(generate_sequence),
    ]
