# Generated by Django 3.1.12 on 2021-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0013_add_display_id_to_organization_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='urgency',
            field=models.CharField(
                choices=[
                    ('urgent', 'Urgent'),
                    ('standard', 'Standard'),
                    ('low', 'Low'),
                ],
                default='low',
                max_length=32,
            ),
        ),
    ]
