# Generated by Django 3.1.12 on 2021-08-19 14:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0015_organizationmonitor_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='take_action',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
