# Generated by Django 3.1.12 on 2021-08-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0055_remove_watcherlist_organization_monitor'),
        ('monitor', '0016_add_take_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmonitor',
            name='watcher_list',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_monitor',
                to='user.watcherlist',
            ),
        ),
    ]
