# Generated by Django 3.1.12 on 2021-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0017_change_watcher_list_constrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='fix_me_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
