# Generated by Django 3.1.12 on 2021-10-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0019_monitor_exclude_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorExclusion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('exclusion_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('snapshot', models.JSONField()),
                ('justification', models.TextField()),
                (
                    'organization_monitor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='monitor.organizationmonitor',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MonitorExclusionEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('event_date', models.DateTimeField(auto_now=True)),
                (
                    'event_type',
                    models.TextField(
                        choices=[
                            ('created', 'Created'),
                            ('deleted', 'Deleted'),
                            ('renewed', 'Renewed'),
                            ('deprecated', 'Deprecated'),
                            ('updated_justification', 'Updated Justification'),
                        ]
                    ),
                ),
                ('justification', models.TextField()),
                (
                    'monitor_exclusion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='monitor.monitorexclusion',
                    ),
                ),
            ],
        ),
    ]
