# Generated by Django 3.1.12 on 2021-11-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0022_updating_organization_monitor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorresult',
            name='execution_time',
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=7
            ),
        ),
    ]
