# Generated by Django 3.1.12 on 2021-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0024_add_refresh_type_and_user_to_monitor_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmonitor',
            name='toggled_by_system',
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            UPDATE monitor_organizationmonitor
            SET toggled_by_system = false
            WHERE active = false;
            COMMIT;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
