# Generated by Django 3.1.12 on 2021-11-28 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0025_add_toggled_by_system_to_organization_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmonitor',
            name='created_at',
            field=models.DateTimeField(null=True, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            UPDATE monitor_organizationmonitor
            SET created_at =mr.min
            FROM
            (SELECT organization_monitor_id, MIN(created_at) AS min
                FROM monitor_monitorresult GROUP BY organization_monitor_id) mr
                where id =mr.organization_monitor_id;
            COMMIT;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='organizationmonitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MonitorUserEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event',
                    models.TextField(
                        choices=[
                            ('view_detail', 'View Detail'),
                            ('view_dashboard', 'View Dashboard'),
                        ]
                    ),
                ),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                (
                    'organization_monitor',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='monitor.organizationmonitor',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
