# Generated by Django 3.1.12 on 2021-12-27 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0065_create_api_admin_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0026_monitor_user_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSubscriptionEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event_type',
                    models.TextField(
                        choices=[
                            ('subscribed', 'Subscribed'),
                            ('unsubscribed', 'Unsubscribed'),
                        ]
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.organization',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='monitor_subscription_event',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
