# Generated by Django 3.1.12 on 2022-01-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0029_add_field_to_reference_control_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationmonitor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
