# Generated by Django 3.1.12 on 2022-02-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0030_change_max_length_for_monitor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSourceSystem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='source_systems',
            field=models.ManyToManyField(
                related_name='monitors', to='monitor.MonitorSourceSystem'
            ),
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT INTO monitor_monitorsourcesystem (name) 
            VALUES 
                ('Policies'), ('People'), ('Monitors'), ('Documents'),
                ('Monitor Results'), ('Controls'), ('Evidence Requests'),
                ('Vendors'), ('Audits'), ('Teams'), ('Officers'),
                ('Team members'), ('Training Alumni'), ('Trainings'),
                ('Action Items'), ('Tasks'), ('Subtasks'), ('Users (Laika Object)'),
                ('Change Requests (Laika Object)'), ('Pull Requests (Laika Object)'),
                ('Monitors (Laika Object)'), ('Events (Laika Object)'),
                ('Accounts (Laika Object)'), ('Repositories (Laika Object)'),
                ('Devices (Laika Object)'),('Service Accounts (Laika Object)'),
                ('asana'), ('AWS'), ('Microsoft_Azure'), ('bitbucket'),
                ('shortcut'), ('datadog'), ('Google_Cloud_Platform'),
                ('github'), ('gitlab'), ('google_workspace'), ('heroku'),
                ('jamf'), ('jira'), ('linear'), ('microsoft_365'),
                ('okta'), ('rippling'), ('sentry'), ('vetty'),
                ('Github_Apps'), ('slack'), ('checkr');
            COMMIT;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
