# Generated by Django 3.1.12 on 2022-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0031_adding_source_systems_to_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='source_systems',
        ),
        migrations.AddField(
            model_name='monitor',
            name='source_systems',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='MonitorSourceSystem',
        ),
    ]
