# Generated by Django 3.2.15 on 2022-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0032_refactor_source_systems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmonitor',
            name='display_id',
        ),
        migrations.AddField(
            model_name='monitor',
            name='display_id',
            field=models.TextField(default=''),
        ),
    ]
