# Generated by Django 3.2.15 on 2022-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0018_add_target_audit_dates'),
        ('monitor', '0033_update_monitor_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='frameworks',
            field=models.ManyToManyField(
                related_name='monitors', to='certification.Certification'
            ),
        ),
    ]
