# Generated by Django 3.2.15 on 2022-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0034_associate_frameworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmonitor',
            name='urgency',
            field=models.CharField(
                blank=True,
                choices=[
                    ('urgent', 'Urgent'),
                    ('standard', 'Standard'),
                    ('low', 'Low'),
                ],
                max_length=32,
            ),
        ),
    ]
