# Generated by Django 3.2.15 on 2022-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0035_add_urgency_to_org_monitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoruserevent',
            name='event',
            field=models.TextField(
                choices=[
                    ('view_detail', 'View Detail'),
                    ('view_dashboard', 'View Dashboard'),
                    ('close_dynamic_banner', 'Close Dynamic Banner'),
                ]
            ),
        ),
    ]
