# Generated by Django 3.2.15 on 2022-10-31 15:24

from django.db import migrations


def migrate_monitor_result_status(apps, schema_editor):
    org_monitor_model = apps.get_model('monitor', 'OrganizationMonitor')
    deactivated_monitors = org_monitor_model.objects.filter(
        active=False, toggled_by_system=True
    )
    deactivated_monitors.update(active=True)


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0038_migrate_monitor_result_status'),
    ]

    operations = [
        migrations.RunPython(
            migrate_monitor_result_status, reverse_code=migrations.RunPython.noop
        )
    ]
