# Generated by Django 3.2.15 on 2022-11-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0039_migrate_system_deactivate_monitors_to_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorresult',
            name='status',
            field=models.CharField(
                choices=[
                    ('healthy', 'Healthy'),
                    ('triggered', 'Triggered'),
                    ('connection_error', 'Connection Error'),
                    ('no_data_detected', 'No Data Detected'),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='organizationmonitor',
            name='status',
            field=models.CharField(
                choices=[
                    ('healthy', 'Healthy'),
                    ('triggered', 'Triggered'),
                    ('connection_error', 'Connection Error'),
                    ('no_data_detected', 'No Data Detected'),
                ],
                max_length=32,
            ),
        ),
    ]
