# Generated by Django 3.2.15 on 2022-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0040_remove_no_datasource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='evidence_requests_reference_ids',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Evidence references by id',
            ),
        ),
        migrations.AddField(
            model_name='monitor',
            name='evidence_requests_references',
            field=models.TextField(
                blank=True, null=True, verbose_name='Evidence references'
            ),
        ),
    ]
