# Generated by Django 3.0.3 on 2020-03-17 22:26

import django.db.models.deletion
from django.db import migrations, models

import laika.storage
import seeder.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0005_auto_20200304_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                (
                    'seed_file',
                    models.FileField(
                        blank=True,
                        max_length=512,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=seeder.models.seeder_file_directory_path,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('p', 'Pending'),
                            ('i', 'In Progress'),
                            ('f', 'Failed'),
                            ('d', 'Done'),
                        ],
                        default='p',
                        max_length=1,
                    ),
                ),
                ('status_detail', models.TextField(blank=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seedfiles',
                        to='organization.Organization',
                    ),
                ),
            ],
        ),
    ]
