# Generated by Django 3.0.3 on 2020-04-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0006_auto_20200421_1655'),
        ('seeder', '0001_seeder_initial_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='organization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='seedfiles',
                to='organization.Organization',
            ),
        ),
    ]
