# Generated by Django 3.1.2 on 2021-05-11 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seeder', '0003_seedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='seeds',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
