# Generated by Django 3.1.6 on 2021-05-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0015_add_alerts_perms_to_groups'),
        ('seeder', '0004_seed_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='audit',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='seed_files',
                to='audit.audit',
            ),
        ),
    ]
