# Generated by Django 3.1.2 on 2021-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0006_create_proxy_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedprofile',
            name='default_base',
            field=models.BooleanField(default=False),
        ),
    ]
