# Generated by Django 3.1.6 on 2021-06-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0007_seedprofile_default_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='profile',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile',
                to='seeder.seedprofile',
            ),
        ),
    ]
