# Generated by Django 3.1.6 on 2021-06-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0008_profile_reference_to_org_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile',
                to='seeder.seedprofile',
            ),
        ),
    ]
