# Generated by Django 3.1.6 on 2021-06-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0010_new_training_remainder_type'),
        ('seeder', '0009_seed_profile_blank_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seed_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'seed',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seeds',
                        to='seeder.seed',
                    ),
                ),
            ],
        ),
    ]
