# Generated by Django 3.1.12 on 2022-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0010_seed_alert_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='seed',
            name='content_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='seedprofile',
            name='content_description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
