# Generated by Django 3.1.12 on 2022-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0011_add_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='status',
            field=models.CharField(
                choices=[
                    ('p', 'Pending'),
                    ('i', 'In Progress'),
                    ('f', 'Failed'),
                    ('d', 'Done'),
                    ('u', 'Updating'),
                ],
                default='p',
                max_length=1,
            ),
        ),
    ]
