# Generated by Django 3.1.12 on 2022-03-01 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import laika.storage
import seeder.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0069_complete_onboarding_for_missing_orgs'),
        ('seeder', '0012_add_new_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyComplianceMigration',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('frameworks_detail', models.TextField(blank=True)),
                (
                    'mapping_file',
                    models.FileField(
                        max_length=512,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=seeder.models.seeder_file_directory_path,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('p', 'Pending'),
                            ('i', 'In Progress'),
                            ('f', 'Failed'),
                            ('d', 'Done'),
                            ('u', 'Updating'),
                        ],
                        default='p',
                        max_length=1,
                    ),
                ),
                ('status_detail', models.TextField(blank=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='my_compliance_migrations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='my_compliance_migrations',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
    ]
