# Generated by Django 3.1.12 on 2022-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0013_mycompliancemigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycompliancemigration',
            name='mapped_subtasks',
            field=models.TextField(blank=True),
        ),
    ]
