# Generated by Django 3.2.14 on 2022-07-15 19:47

import django.core.validators
from django.db import migrations, models

import laika.storage
import seeder.models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0014_mycompliancemigration_mapped_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='custom_org_list',
            field=models.FileField(
                blank=True,
                max_length=512,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=seeder.models.seeder_custom_org_file_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['zip']
                    )
                ],
            ),
        ),
    ]
