# Generated by Django 3.2.14 on 2022-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seeder', '0015_seed_custom_org_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedprofile',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visible in Polaris'),
        ),
    ]
