# Generated by Django 3.0.3 on 2020-03-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0005_auto_20200304_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feature_flags',
                        to='organization.Organization',
                    ),
                ),
            ],
        ),
    ]
