# Generated by Django 3.0.3 on 2020-03-30 21:51

from django.db import migrations


def enable_legacy_policy_for_all_organizations(apps, schema_editor):
    Organization = apps.get_model('organization', 'Organization')
    Flag = apps.get_model('feature', 'Flag')

    for organization in Organization.objects.all():
        Flag.objects.get_or_create(
            name='legacyPolicyFeatureFlag',
            organization=organization,
            defaults={'is_enabled': True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [migrations.RunPython(enable_legacy_policy_for_all_organizations)]
