# Generated by Django 3.1.2 on 2021-02-17 14:48

from django.db import migrations


def add_audits_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='auditsFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0002_enable_legacy_policy_for_all_orgs'),
    ]

    operations = [migrations.RunPython(add_audits_feature_flag)]
