# Generated by Django 3.1.2 on 2021-02-26 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0003_add_audits_feature_flag'),
    ]

    operations = [
        migrations.RunSQL(
            '''
           BEGIN;
           DELETE
           FROM public.feature_flag
           WHERE name in(
           'legacyDocumentsFeatureFlag',
           'documentsBetaFeatureFlag',
           'driveFeatureFlag');
            COMMIT;
       '''
        ),
    ]
