# Generated by Django 3.1.2 on 2021-05-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0004_delete_legacy_documents_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(
                choices=[
                    ('commentsFeatureFlag', 'Comments'),
                    ('dashboardFeatureFlag', 'Dashboard'),
                    ('integrationsFeatureFlag', 'Integrations'),
                    ('objectsFeatureFlag', 'Objects'),
                    ('programsFeatureFlag', 'Programs'),
                    ('auditsFeatureFlag', 'Audits'),
                    ('monitorsFeatureFlag', 'Monitors'),
                ],
                max_length=255,
            ),
        ),
    ]
