# Generated by Django 3.1.6 on 2021-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0005_feature_flag_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
