# Generated by Django 3.1.6 on 2021-06-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0019_audit_auto_fetch_run'),
        ('feature', '0006_revert_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorFlag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                (
                    'audit_firm',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feature_flags',
                        to='audit.auditfirm',
                    ),
                ),
            ],
        ),
    ]
