# Generated by Django 3.1.6 on 2021-06-30 21:45

from django.db import migrations


def add_auditor_fieldwork_feature_flag(apps, schema_editor):
    audit_firm_model = apps.get_model('audit', 'AuditFirm')
    flag_model = apps.get_model('feature', 'AuditorFlag')

    for audit_firm in audit_firm_model.objects.all():
        flag_model.objects.get_or_create(
            name='isFieldworkEnabled',
            audit_firm=audit_firm,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0007_auditorflag'),
    ]

    operations = [migrations.RunPython(add_auditor_fieldwork_feature_flag)]
