# Generated by Django 3.1.6 on 2021-12-17 13:30

from django.db import migrations


def add_api_tokens_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='apiTokensFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0008_add_auditor_fieldwork_feature_flag'),
    ]

    operations = [migrations.RunPython(add_api_tokens_feature_flag)]
