# Generated by Django 3.1.12 on 2021-12-20 21:25

from django.db import migrations


def add_playbooks_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='playbooksFeatureFlag',
            organization=organization,
            defaults={'is_enabled': True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0009_add_api_tokens_feature_flag'),
    ]

    operations = [migrations.RunPython(add_playbooks_feature_flag)]
