# Generated by Django 3.1.12 on 2022-01-20 22:43

from django.db import migrations


def add_playbooks_read_only_mode_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='readOnlyPlaybooksFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0010_add_playbooks_feature_flag'),
    ]

    operations = [migrations.RunPython(add_playbooks_read_only_mode_feature_flag)]
