# Generated by Django 3.1.12 on 2022-01-21 18:16

from django.db import migrations


def remove_playbooks_read_only_mode_feature_flag(apps, schema_editor):
    flag_model = apps.get_model('feature', 'Flag')

    flag_model.objects.filter(name='readOnlyPlaybooksFeatureFlag').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0011_add_read_only_playbooks_feature_flag'),
    ]

    operations = [migrations.RunPython(remove_playbooks_read_only_mode_feature_flag)]
