# Generated by Django 3.1.12 on 2022-02-11 04:17

from django.db import migrations


def add_auditor_report_feature_flag(apps, schema_editor):
    audit_firm_model = apps.get_model('audit', 'AuditFirm')
    flag_model = apps.get_model('feature', 'AuditorFlag')

    for audit_firm in audit_firm_model.objects.all():
        flag_model.objects.get_or_create(
            name='reportFeatureFlag',
            audit_firm=audit_firm,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0012_remove_playbooks_read_only_mode_feature_flag'),
    ]

    operations = [migrations.RunPython(add_auditor_report_feature_flag)]
