# Generated by Django 3.1.12 on 2021-02-25 21:51
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_api_tokens_feature_flag(apps, schema_editor):
    flag_model = apps.get_model('feature', 'Flag')
    api_tokens_flags = flag_model.objects.filter(name='apiTokensFeatureFlag')
    logger.info(f'Deleting {api_tokens_flags.count()} api tokens  feature flags!')
    api_tokens_flags.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0013_add_audit_report_feature_flag'),
    ]

    operations = [migrations.RunPython(delete_api_tokens_feature_flag)]
