# Generated by Django 3.2.13 on 2022-07-01 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0072_apitokenhistory_usage_type'),
        ('feature', '0014_remove_api_token_feature_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('name', 'organization')},
        ),
    ]
