# Generated by Django 3.1.2 on 2020-11-23 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('dataroom', '0002_dataroom_migration')]

    operations = [
        # One time operation, is not needed anymore
        # migrations.RunPython(
        #     migrate_laika_papers_to_pdf,
        #     reverse_code=migrations.RunPython.noop
        # ),
    ]
