# Generated by Django 3.1.2 on 2021-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataroom', '0003_update_laika_papers_to_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='is_soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
