# Generated by Django 3.1.2 on 2021-02-19 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import audit.models
import laika.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0012_adding_is_active_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('audit_type', models.CharField(max_length=100)),
                ('audit_configuration', models.JSONField(blank=True, default=dict)),
                ('audit_firm', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'report',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=audit.models.audit_report_directory_path,
                    ),
                ),
                (
                    'auditor',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audits',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audits',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AuditStatus',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested', models.BooleanField(default=False)),
                ('initiated', models.BooleanField(default=False)),
                ('fieldwork', models.BooleanField(default=False)),
                ('in_draft_report', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('confirm_audit_details', models.BooleanField(default=False)),
                ('engagement_letter_link', models.TextField(blank=True, null=True)),
                (
                    'control_design_assessment_link',
                    models.TextField(blank=True, null=True),
                ),
                ('kickoff_meeting_link', models.TextField(blank=True, null=True)),
                ('engagement_letter_checked', models.BooleanField(default=False)),
                (
                    'control_design_assessment_checked',
                    models.BooleanField(default=False),
                ),
                ('kickoff_meeting_checked', models.BooleanField(default=False)),
                (
                    'confirm_engagement_letter_signed',
                    models.BooleanField(default=False),
                ),
                (
                    'confirm_control_design_assessment',
                    models.BooleanField(default=False),
                ),
                ('confirm_kickoff_meeting', models.BooleanField(default=False)),
                ('representation_letter_link', models.TextField(blank=True, null=True)),
                ('management_assertion_link', models.TextField(blank=True, null=True)),
                (
                    'subsequent_events_questionnaire_link',
                    models.TextField(blank=True, null=True),
                ),
                (
                    'draft_report',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=audit.abstract_models.audit_draft_report_directory_path,
                    ),
                ),
                ('review_draft_report_checked', models.BooleanField(default=False)),
                ('representation_letter_checked', models.BooleanField(default=False)),
                ('management_assertion_checked', models.BooleanField(default=False)),
                (
                    'subsequent_events_questionnaire_checked',
                    models.BooleanField(default=False),
                ),
                (
                    'confirm_completion_of_signed_documents',
                    models.BooleanField(default=False),
                ),
                (
                    'final_report',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=audit.abstract_models.audit_draft_report_directory_path,
                    ),
                ),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status',
                        to='audit.audit',
                    ),
                ),
            ],
        ),
    ]
