# Generated by Django 3.1.2 on 2021-02-19 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0001_audit_and_coupons_models'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                   SELECT
                      g.id AS group_id, p.id AS permission_id 
                   FROM
                      public.auth_group g 
                      cross join
                         public.auth_permission p 
                   WHERE
                      (
                         g.name ilike '%_admin' 
                         OR g.name ilike '%_super' 
                      )
                      AND p.codename = ANY (array [
                        'view_audit',
                        'change_audit',
                        'add_audit',
                        'delete_audit' ]
                        )
                    )
                ON CONFLICT DO NOTHING;
                COMMIT;
            '''
        )
    ]
