# Generated by Django 3.1.2 on 2021-02-24 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_add_audit_pemissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='completed_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='fieldwork_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='in_draft_report_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='initiated_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audits',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed Stage'),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='fieldwork',
            field=models.BooleanField(default=False, verbose_name='Fieldwork Stage'),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='in_draft_report',
            field=models.BooleanField(default=False, verbose_name='Draft Report Stage'),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='initiated',
            field=models.BooleanField(default=False, verbose_name='Initiated Stage'),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='requested',
            field=models.BooleanField(default=False, verbose_name='Requested Stage'),
        ),
    ]
