# Generated by Django 3.1.2 on 2021-02-24 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0003_audit_status_model_update'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike '%_admin' 
                     OR g.name ilike '%_super' 
                  )
                  AND p.codename = ANY (array [
                    'view_audit',
                    'change_audit',
                    'add_audit',
                    'delete_audit' ]
                    )
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        )
    ]
