# Generated by Django 3.1.2 on 2021-03-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0004_add_audit_pemissions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='control_design_assessment_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='engagement_letter_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='management_assertion_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='representation_letter_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='subsequent_events_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
