# Generated by Django 3.1.2 on 2021-03-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0005_update_alert_choices_audits'),
        ('audit', '0005_add_url_fields_to_auditstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alerts',
                        to='audit.audit',
                    ),
                ),
            ],
        ),
    ]
