# Generated by Django 3.1.2 on 2021-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0006_auditalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_audit_details_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_completion_of_signed_documents_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_control_design_assessment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_engagement_letter_signed_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_kickoff_meeting_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='control_design_assessment_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='engagement_letter_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='final_report_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='kickoff_meeting_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='management_assertion_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='representation_letter_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='subsequent_events_questionnaire_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
