# Generated by Django 3.1.2 on 2021-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0007_add_timestamps_to_auditstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstatus',
            name='control_design_assessment_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='engagement_letter_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='management_assertion_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='representation_letter_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditstatus',
            name='subsequent_events_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
