# Generated by Django 3.1.2 on 2021-03-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0035_create_auditor_model'),
        ('audit', '0008_changed_url_links_to_textfield_auditstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAuditor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title_role',
                    models.CharField(
                        choices=[
                            ('lead_auditor', 'Lead Auditor'),
                            ('tester', 'Tester'),
                            ('reviewer', 'Reviewer'),
                        ],
                        default='required',
                        max_length=50,
                    ),
                ),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_team',
                        to='audit.audit',
                    ),
                ),
                (
                    'auditor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit',
                        to='user.auditor',
                    ),
                ),
            ],
        ),
    ]
