# Generated by Django 3.1.2 on 2021-04-06 21:13

from django.db import migrations

group_names = [
    'auditor',
    'auditor_admin',
]


def create_permission(apps, model, codename, name):
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    obj_content_type = content_type.objects.get_for_model(model)
    content_type = content_type.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    permission.objects.get_or_create(
        codename=codename, name=name, content_type=content_type
    )


def create_audit_groups_and_permissions(apps, schema_editor):
    audit_auditor = apps.get_model('audit', 'AuditAuditor')
    audit = apps.get_model('audit', 'Audit')

    group = apps.get_model('auth', 'Group')

    # Create new groups for permissions
    for gn in group_names:
        group.objects.create(name=gn)

    create_permission(apps, audit_auditor, 'add_audit_user', 'Can add audit user')

    create_permission(apps, audit, 'assign_audit', 'Can assign an audit')


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0009_auditauditor'),
    ]

    operations = [
        migrations.RunPython(create_audit_groups_and_permissions),
        migrations.RunSQL(
            '''
                            BEGIN;
                            INSERT into
                               public.auth_group_permissions (group_id, permission_id) (
                               SELECT
                                  g.id AS group_id, p.id AS permission_id 
                               FROM
                                  public.auth_group g 
                                  cross join
                                     public.auth_permission p 
                               WHERE
                                  (
                                     g.name = 'auditor_admin' 
                                  )
                                  AND p.codename = ANY (array [
                                    'add_audit_user',
                                    'assign_audit',
                                    'view_auditalert',
                                    'view_audit',
                                    'change_audit']
                                    )
                                )
                            ON CONFLICT DO NOTHING;
                            COMMIT;
                        '''
        ),
        migrations.RunSQL(
            '''
                                BEGIN;
                                INSERT into
                                   public.auth_group_permissions (group_id, permission_id) (
                                   SELECT
                                      g.id AS group_id, p.id AS permission_id 
                                   FROM
                                      public.auth_group g 
                                      cross join
                                         public.auth_permission p 
                                   WHERE
                                      (
                                         g.name = 'auditor' 
                                      )
                                      AND p.codename = ANY (array [
                                        'view_auditalert',
                                        'view_audit',
                                        'change_audit']
                                        )
                                    )
                                ON CONFLICT DO NOTHING;
                                COMMIT;
                            '''
        ),
    ]
