# Generated by Django 3.1.2 on 2021-04-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0035_create_auditor_model'),
        ('audit', '0011_add_delete_user_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFirm',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuditorAuditFirm',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'audit_firm',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='firm_auditors',
                        to='audit.auditfirm',
                    ),
                ),
                (
                    'auditor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='user.auditor'
                    ),
                ),
            ],
        ),
    ]
