# Generated by Django 3.1.2 on 2021-04-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0036_add_audit_firm'),
        ('audit', '0012_add_audit_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditauditor',
            name='auditor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audit_team',
                to='user.auditor',
            ),
        ),
    ]
