# Generated by Django 3.1.6 on 2021-05-17 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0015_add_alerts_perms_to_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='audit_firm',
            new_name='audit_firm_text',
        ),
    ]
