# Generated by Django 3.1.6 on 2021-05-19 17:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_audit_firms_audits(apps, schema_editor):
    Audit = apps.get_model('audit', 'Audit')
    AuditFirm = apps.get_model('audit', 'AuditFirm')
    audits = Audit.objects.all()
    for a in audits:
        if a.audit_firm_text:
            firm = AuditFirm.objects.filter(name=a.audit_firm_text).first()
            if firm:
                a.audit_firm = firm
                a.save()


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0035_alter_name_website_fields'),
        ('audit', '0016_rename_audit_firm_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_firm',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audit',
                to='audit.auditfirm',
            ),
        ),
        migrations.CreateModel(
            name='OrganizationAuditFirm',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'audit_firm',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='firm_organizations',
                        to='audit.auditfirm',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_audit_firms_audits),
    ]
