# Generated by Django 3.1.6 on 2021-05-29 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0017_add_audit_firm_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='audit_firm_text',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='auditor',
        ),
    ]
