# Generated by Django 3.1.6 on 2021-06-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0018_remove_audit_firm_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='auto_fetch_executed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
