# Generated by Django 3.1.12 on 2021-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0019_audit_auto_fetch_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_fieldwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='confirm_fieldwork_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_generated_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
