# Generated by Django 3.1.12 on 2021-09-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0020_add_fieldwork_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditstatus',
            old_name='confirm_fieldwork',
            new_name='complete_fieldwork',
        ),
        migrations.RemoveField(
            model_name='auditstatus',
            name='confirm_fieldwork_updated_at',
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='complete_fieldwork_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
