# Generated by Django 3.1.12 on 2021-09-23 16:10

from django.db import migrations


def create_permission(apps, schema_editor):
    audit_firm = apps.get_model('audit', 'AuditFirm')
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    obj_content_type = content_type.objects.get_for_model(audit_firm)
    content_type = content_type.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    permission.objects.get_or_create(
        codename='view_audit_firm_auditors',
        name='Can view audit firm auditor users',
        content_type=content_type,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0021_rename_fieldwork_stage_fields'),
    ]

    operations = [
        migrations.RunPython(create_permission),
        migrations.RunSQL(
            '''
                                BEGIN;
                                INSERT into
                                   public.auth_group_permissions (group_id, permission_id) (
                                   SELECT
                                      g.id AS group_id, p.id AS permission_id 
                                   FROM
                                      public.auth_group g 
                                      cross join
                                         public.auth_permission p 
                                   WHERE
                                      (
                                         g.name = 'auditor_admin' or g.name = 'auditor'
                                      )
                                      AND p.codename = ANY (array ['view_audit_firm_auditors'])
                                    )
                                ON CONFLICT DO NOTHING;
                                COMMIT;
                            '''
        ),
    ]
