# Generated by Django 3.1.12 on 2021-10-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0022_add_permission_to_auditors_view_auditors'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='first_draft_report_generated_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
