# Generated by Django 3.1.12 on 2021-10-14 17:58

from django.db import migrations


def create_change_audit_user_permission(apps, schema_editor):
    audit_auditor = apps.get_model('audit', 'AuditAuditor')
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    obj_content_type = content_type.objects.get_for_model(audit_auditor)
    content_type = content_type.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    permission.objects.get_or_create(
        codename='change_audit_user',
        name='Can change audit user',
        content_type=content_type,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0023_auditstatus_first_draft_report_generated_timestamp'),
    ]

    operations = [
        migrations.RunPython(create_change_audit_user_permission),
        migrations.RunSQL(
            '''
                                BEGIN;
                                INSERT into
                                   public.auth_group_permissions (group_id, permission_id) (
                                   SELECT
                                      g.id AS group_id, p.id AS permission_id 
                                   FROM
                                      public.auth_group g 
                                      cross join
                                         public.auth_permission p 
                                   WHERE
                                      (
                                         g.name = 'auditor_admin' 
                                      )
                                      AND p.codename = ANY (array [
                                        'change_audit_user'
                                        ]
                                        )
                                    )
                                ON CONFLICT DO NOTHING;
                                COMMIT;
                            '''
        ),
    ]
