# Generated by Django 3.1.12 on 2021-10-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0024_add_permission_to_edit_auditor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStepTimestamp',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('updated_step', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'audit_status',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='audit.auditstatus',
                    ),
                ),
            ],
        ),
    ]
