# Generated by Django 3.1.12 on 2021-10-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0025_auditsteptimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_checked_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
