# Generated by Django 3.1.12 on 2021-11-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0026_auditstatus_draft_report_checked_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='kickoff_call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='kickoff_call_date_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
