# Generated by Django 3.1.12 on 2021-11-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0027_add_auditstatus_kickoff_call_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
