# Generated by Django 3.1.12 on 2021-11-16 19:49

from django.db import migrations, models

import audit.abstract_models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0028_add_is_demo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_file_generated',
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=audit.abstract_models.audit_draft_report_directory_path,
            ),
        ),
    ]
