# Generated by Django 3.1.12 on 2021-11-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
        ('audit', '0029_auditstatus_draft_report_file_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftReportComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('page', models.IntegerField(blank=True, null=True)),
                ('is_latest_version', models.BooleanField(default=True)),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='draft_report_comments',
                        to='audit.audit',
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='draft_report_comments',
                        to='comment.comment',
                    ),
                ),
            ],
        ),
    ]
