# Generated by Django 3.1.12 on 2021-11-19 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0031_draftreportcomment_permissions'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike '%_admin' 
                     OR g.name ilike '%_super'
                     OR g.name ilike '%auditor'
                  )
                  AND p.codename = ANY (array [
                    'add_draftreportcomment',
                    'delete_draftreportcomment',
                    'change_draftreportcomment',
                    'view_draftreportcomment' ]
                    )
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        )
    ]
