# Generated by Django 3.1.12 on 2021-12-06 14:57

from django.db import migrations


def add_draft_report_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='inAppDraftReportingFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0033_create_draft_report_comment_permissions'),
    ]

    operations = [migrations.RunPython(add_draft_report_feature_flag)]
