# Generated by Django 3.1.12 on 2021-12-06 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0034_add_draft_report_feature_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='draft_report_approved_by',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_approved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
