# Generated by Django 3.1.12 on 2021-12-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0035_add_draft_report_approver_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftreportcomment',
            name='auditor_notified',
            field=models.BooleanField(default=False),
        ),
    ]
