# Generated by Django 3.1.12 on 2022-01-06 16:33

from django.db import migrations


def create_permission(apps, model, codename, name):
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    obj_content_type = content_type.objects.get_for_model(model)
    content_type = content_type.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    permission.objects.get_or_create(
        codename=codename, name=name, content_type=content_type
    )


permissions = [
    ('publish_draft_report', 'Can publish draft report'),
]


def create_draft_report_permissions(apps, schema_editor):
    audits_draft_report = apps.get_model('audit', 'Audit')

    for p in permissions:
        create_permission(apps, audits_draft_report, p[0], p[1])


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0036_add_auditor_notified_flag_to_draft_report_comment'),
    ]

    operations = [
        migrations.RunPython(create_draft_report_permissions),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id
               FROM
                  public.auth_group g
                  cross join
                     public.auth_permission p
                  join django_content_type ct on ct.id = p.content_type_id
               WHERE
                  (
                     g.name = 'auditor_admin'
                  )
                  AND p.codename = ANY (array [
                    'publish_draft_report'
                    ]
                    )
                    AND ct.app_label = 'audit' and ct.model ='audit'
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        ),
    ]
