# Generated by Django 3.1.12 on 2022-01-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0037_create_draft_report_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='draft_report_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
