# Generated by Django 3.1.12 on 2022-02-10 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0012_set_default_visible_and_order'),
        ('audit', '0038_auditstatus_draft_report_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFrameworkType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'audit_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('SOC_2_TYPE_1', 'SOC 2 Type 1'),
                            ('SOC_2_TYPE_2', 'SOC 2 Type 2'),
                            ('HITRUST', 'HITRUST'),
                        ],
                        max_length=50,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                (
                    'certification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_type',
                        to='certification.certification',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_framework_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audits',
                to='audit.auditframeworktype',
            ),
        ),
    ]
