# Generated by Django 3.1.12 on 2022-02-09 20:52

from django.db import migrations, models

import audit.abstract_models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0039_create_audit_framework_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstatus',
            name='organization_chart',
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=audit.abstract_models.audit_draft_report_directory_path,
            ),
        ),
        migrations.AddField(
            model_name='auditstatus',
            name='organization_chart_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
