# Generated by Django 3.1.12 on 2022-02-11 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('certification', '0012_set_default_visible_and_order'),
        ('audit', '0040_auditstatus_organization_chart_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auditframeworktype',
            unique_together={('certification', 'audit_type')},
        ),
        migrations.RunSQL(
            '''
            BEGIN;
                INSERT INTO public.certification_certification (created_at, updated_at, name, logo, code, description, regex, is_visible)
                VALUES (now(), now(), 'HITRUST', '', '', '', '', 'true') 
                ON CONFLICT (name)
                DO NOTHING;
            COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
            BEGIN;
                INSERT INTO public.certification_certification (created_at, updated_at, name, logo, code, description, regex, is_visible)
                values(now(), now(), 'SOC 2 Type 1', '', '', '', '', 'true') 
                ON CONFLICT (name)
                DO NOTHING;
            COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
            BEGIN;
                INSERT INTO public.certification_certification (created_at, updated_at, name, logo, code, description, regex, is_visible)
                values(now(), now(), 'SOC 2 Type 2', '', '', '', '', 'true') 
                ON CONFLICT (name)
                DO NOTHING;
            COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT INTO public.audit_auditframeworktype (audit_type, 
                certification_id, description)
            VALUES ('SOC_2_TYPE_1', (SELECT id FROM 
            public.certification_certification where name = 'SOC 2 Type 1'), 
            'The purpose of this AICPA report is to conduct a formalized SOC examination. The report includes management''s description of the system as well as the suitability of the design of controls as of a specific point in time.')
            ON CONFLICT (audit_type, certification_id)
            DO NOTHING;
            COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT INTO public.audit_auditframeworktype (audit_type, 
                certification_id, description) 
            VALUES ('SOC_2_TYPE_2', (SELECT id FROM 
            public.certification_certification where name = 'SOC 2 Type 2'), 
                'The purpose of this AICPA report is to conduct a formalized SOC examination. The report includes management''s description of the system as well as the suitability of both the design and operating effectiveness of controls over a period of time.')
            ON CONFLICT (audit_type, certification_id)
            DO NOTHING;
            COMMIT;
    '''
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT INTO public.audit_auditframeworktype (audit_type, 
                certification_id, description) 
                VALUES ('HITRUST', (SELECT id FROM 
                public.certification_certification where name = 'HITRUST'), 
                'The HITRUST CSF Assurance Program provides a risk-based approach to a HITRUST CSF controls assessment performed by a qualified professional service firm to provide reliable reviews and formal certification as well as assurance for the entire program.')
            ON CONFLICT (audit_type, certification_id)
            DO NOTHING;
            COMMIT;
    '''
        ),
    ]
