# Generated by Django 3.1.12 on 2022-02-14 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0041_add_audit_framework_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditstatus',
            name='organization_chart',
        ),
        migrations.RemoveField(
            model_name='auditstatus',
            name='organization_chart_updated_at',
        ),
    ]
