# Generated by Django 3.1.12 on 2022-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0042_remove_auditstatus_organization_chart'),
    ]

    operations = [
        migrations.RunSQL(
            '''
        BEGIN;
            UPDATE audit_audit 
            SET audit_framework_type_id = (select id from audit_auditframeworktype where audit_type = 'SOC_2_TYPE_1')
            WHERE audit_type = 'SOC 2 Type 1';
        COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
        BEGIN;
            UPDATE audit_audit 
            SET audit_framework_type_id = (select id from audit_auditframeworktype where audit_type = 'SOC_2_TYPE_2')
            WHERE audit_type = 'SOC 2 Type 2';
        COMMIT;
        '''
        ),
    ]
