# Generated by Django 3.1.12 on 2022-02-21 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0043_associate_audit_to_audit_framework_type'),
    ]

    operations = [
        migrations.RunSQL(
            '''
        BEGIN;
            UPDATE audit_audit 
            SET audit_framework_type_id = (select id from audit_auditframeworktype where audit_type = 'SOC_2_TYPE_1')
            WHERE audit_type = 'SOC 2 Type 1' and audit_framework_type_id IS NULL;
        COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
        BEGIN;
            UPDATE audit_audit 
            SET audit_framework_type_id = (select id from audit_auditframeworktype where audit_type = 'SOC_2_TYPE_2')
            WHERE audit_type = 'SOC 2 Type 2' and audit_framework_type_id IS NULL;
        COMMIT;
        '''
        ),
    ]
