# Generated by Django 3.1.12 on 2022-02-28 19:34

from django.db import migrations, models

import audit.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0044_update_audit_framework_for_new_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='exported_audit_file',
            field=models.FileField(
                blank=True,
                max_length=2024,
                null=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=audit.models.audit_exported_directory_path,
            ),
        ),
    ]
