# Generated by Django 3.1.12 on 2022-03-22 04:53

from django.db import migrations, models

import audit.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0046_removing_hitrust_from_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='exported_audit_file',
            field=models.FileField(
                blank=True,
                max_length=2024,
                null=True,
                storage=laika.storage.PrivateMediaStorage(file_overwrite=True),
                upload_to=audit.models.audit_exported_directory_path,
            ),
        ),
    ]
