# Generated by Django 3.1.12 on 2022-04-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0070_add_onboarding_response_model'),
        ('audit', '0047_override_export_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockedAuditFrameworkTypeOrganization',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'audit_framework_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unlocked_organizations',
                        to='audit.auditframeworktype',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unlocked_audit_frameworks',
                        to='organization.organization',
                    ),
                ),
            ],
            options={
                'unique_together': {('organization', 'audit_framework_type')},
            },
        ),
        migrations.RunSQL(
            '''
        BEGIN;
            INSERT INTO public.certification_certification (created_at, 
            updated_at, name, logo, code, description, regex, is_visible)
            values(now(), now(), 'SOC 1 Type 1', '', '', '', '', 'true') 
            ON CONFLICT (name)
            DO NOTHING;
        COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
        BEGIN;
            INSERT INTO public.certification_certification (created_at, 
            updated_at, name, logo, code, description, regex, is_visible)
            values(now(), now(), 'SOC 1 Type 2', '', '', '', '', 'true') 
            ON CONFLICT (name)
            DO NOTHING;
        COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
        BEGIN;
        INSERT INTO public.audit_auditframeworktype (audit_type, 
            certification_id, description)
        VALUES ('SOC_1_TYPE_1', (SELECT id FROM 
            public.certification_certification where name = 'SOC 1 Type 1'), 
            'The purpose of this AICPA report is to conduct a formalized SOC examination. The report includes management''s description of the system as well as the suitability of the design of controls as of a specific point in time.')
            ON CONFLICT (audit_type, certification_id)
            DO NOTHING;
        COMMIT;
        '''
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT INTO public.audit_auditframeworktype (audit_type, 
                certification_id, description) 
            VALUES ('SOC_1_TYPE_2', (SELECT id FROM 
            public.certification_certification where name = 'SOC 1 Type 2'), 
                'The purpose of this AICPA report is to conduct a formalized SOC examination. The report includes management''s description of the system as well as the suitability of both the design and operating effectiveness of controls over a period of time.')
            ON CONFLICT (audit_type, certification_id)
            DO NOTHING;
        COMMIT;
    '''
        ),
    ]
