# Generated by Django 3.1.12 on 2022-04-19 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0048_unlockedauditframeworktypeorganization'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT INTO audit_unlockedauditframeworktypeorganization (audit_framework_type_id, organization_id)
            SELECT DISTINCT aa.audit_framework_type_id,
                oo.id
            FROM audit_audit aa
            JOIN organization_organization oo ON aa.organization_id = oo.id
            JOIN audit_auditframeworktype aa2 ON aa.audit_framework_type_id 
            = aa2.id
            ON CONFLICT (audit_framework_type_id, organization_id)
            DO NOTHING;
            COMMIT;
        '''
        )
    ]
