# Generated by Django 3.1.12 on 2022-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0049_unlock_audit_framework_types_for_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditframeworktype',
            name='audit_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SOC_2_TYPE_1', 'SOC 2 Type 1'),
                    ('SOC_2_TYPE_2', 'SOC 2 Type 2'),
                    ('SOC_1_TYPE_1', 'SOC 1 Type 1'),
                    ('SOC_1_TYPE_2', 'SOC 1 Type 2'),
                    ('HITRUST', 'HITRUST'),
                ],
                max_length=50,
            ),
        ),
    ]
