# Generated by Django 3.2.13 on 2022-07-07 13:30

import django.db.models.deletion
from django.db import migrations, models

import audit.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0050_add_audit_framework_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkReportTemplate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=512)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=audit.models.framework_templates_file_directory_path,
                    ),
                ),
                (
                    'audit_framework_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='templates',
                        to='audit.auditframeworktype',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AuditReportSection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=512)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=audit.models.report_template_file_directory_path,
                    ),
                ),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report_templates',
                        to='audit.audit',
                    ),
                ),
            ],
        ),
    ]
