# Generated by Django 3.2.13 on 2022-07-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0051_auditreportsection_frameworkreporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditreportsection',
            name='audit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='report_sections',
                to='audit.audit',
            ),
        ),
    ]
