# Generated by Django 3.2.14 on 2022-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0052_alter_auditreportsection_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreportsection',
            name='section',
            field=models.CharField(
                blank=True,
                choices=[
                    ('section_1', 'Section 1'),
                    ('section_2', 'Section 2'),
                    ('section_3', 'Section 3'),
                    ('section_4', 'Section 4'),
                    ('section_5', 'Section 5'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='frameworkreporttemplate',
            name='section',
            field=models.CharField(
                blank=True,
                choices=[
                    ('section_1', 'Section 1'),
                    ('section_2', 'Section 2'),
                    ('section_3', 'Section 3'),
                    ('section_4', 'Section 4'),
                    ('section_5', 'Section 5'),
                ],
                max_length=20,
            ),
        ),
    ]
