# Generated by Django 3.2.15 on 2022-09-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0054_add_report_v2_feature_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='use_new_version',
            field=models.BooleanField(blank=True, default=False, null=True),
        )
    ]
