# Generated by Django 3.2.15 on 2022-09-29 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0055_add_new_version_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditstatus',
            name='completed_created_at',
        ),
    ]
