# Generated by Django 3.2.15 on 2022-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0057_create_update_draft_report_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfirm',
            name='signature_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
