# Generated by Django 3.2.15 on 2022-11-25 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0059_create_update_audit_user_preferences_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='compliance_architect',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ca_audits',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='audit',
            name='customer_success_manager',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='csm_audits',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
