# Generated by Django 3.2.15 on 2022-11-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0060_adding_csm_ca_to_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFeedbackReason',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('reason', models.CharField(default='', max_length=200)),
                (
                    'audit_framework_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback_reason',
                        to='audit.auditframeworktype',
                    ),
                ),
            ],
        ),
    ]
