# Generated by Django 3.2.15 on 2022-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0063_add_feedback_permissions_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfeedback',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditfeedback',
            name='reason',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
