# Generated by Django 3.2.15 on 2022-12-09 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0064_update_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfeedback',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audit_feedback',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='auditfeedback',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
