# Generated by Django 3.2.15 on 2022-12-14 17:41

from django.db import migrations


def add_automated_testing_v1_feature_flag(apps, schema_editor):
    audit_firm_model = apps.get_model('audit', 'AuditFirm')
    flag_model = apps.get_model('feature', 'AuditorFlag')

    for audit_firm in audit_firm_model.objects.all():
        flag_model.objects.get_or_create(
            name='automatedTestingV1FeatureFlag',
            audit_firm=audit_firm,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0065_add_user_to_audit_feedback_table'),
    ]

    operations = [migrations.RunPython(add_automated_testing_v1_feature_flag)]
