# Generated by Django 3.2.15 on 2022-12-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0066_add_automated_testing_v1_feature_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
