# Generated by Django 3.0.7 on 2020-06-19 14:43

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import laika.storage
import objects.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0006_auto_20200421_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaikaObjectType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=100)),
                (
                    'logo',
                    models.FileField(
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=objects.models.laika_object_type_logo_path,
                    ),
                ),
                ('color', models.CharField(max_length=100)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.Organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LaikaObject',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'object_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='elements',
                        to='objects.LaikaObjectType',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=60)),
                ('sort_index', models.IntegerField()),
                ('attribute_type', models.CharField(max_length=100)),
                ('default_value', models.CharField(blank=True, max_length=100)),
                ('is_protected', models.BooleanField(default=False)),
                (
                    'object_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attributes',
                        to='objects.LaikaObjectType',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_manually_editable',
            field=models.BooleanField(default=True),
        ),
    ]
