# Generated by Django 3.0.7 on 2020-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laikaobjecttype',
            name='logo',
        ),
        migrations.AddField(
            model_name='laikaobjecttype',
            name='icon_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
