# Generated by Django 3.0.7 on 2020-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0002_change_logo_to_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobjecttype',
            name='display_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
