# Generated by Django 3.0.7 on 2020-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0005_add_choices_to_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(
                choices=[
                    ('BOOLEAN', 'Boolean'),
                    ('NUMBER', 'Number'),
                    ('TEXT', 'Text'),
                    ('DATE', 'Date'),
                    ('USER', 'User'),
                ],
                max_length=100,
            ),
        ),
    ]
