# Generated by Django 3.0.7 on 2020-08-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0006_change_choices_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobjecttype',
            name='is_system_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='laikaobjecttype',
            constraint=models.UniqueConstraint(
                fields=('organization', 'type_name'),
                name='unique_type_name_for_organization',
            ),
        ),
    ]
