# Generated by Django 3.0.7 on 2020-09-24 21:46

from django.db import migrations, models

from objects.types import AttributeTypeFactory


def default_widths(apps, schema_editor):
    attribute_model = apps.get_model("objects", "Attribute")
    for attribute in attribute_model.objects.all():
        attribute_type = AttributeTypeFactory.get_attribute_type(attribute)
        attribute.min_width = attribute_type.get_min_width()

        attribute.save()


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0007_system_object_type'),
    ]

    operations = [
        # step 1: add width fields as nullable
        migrations.AddField(
            model_name='attribute',
            name='min_width',
            field=models.IntegerField(null=True, blank=True),
        ),
        # step 2: set min and max width based on type
        migrations.RunPython(default_widths, reverse_code=migrations.RunPython.noop),
        # step 3: set width fields as not nullable
        migrations.AlterField(
            model_name='attribute',
            name='min_width',
            field=models.IntegerField(null=False, blank=True),
        ),
    ]
