# Generated by Django 3.0.7 on 2020-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0008_attribute_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(
                choices=[
                    ('BOOLEAN', 'Boolean'),
                    ('NUMBER', 'Number'),
                    ('TEXT', 'Text'),
                    ('DATE', 'Date'),
                    ('USER', 'User'),
                    ('SINGLE_SELECT', 'Single Select'),
                ],
                max_length=100,
            ),
        ),
    ]
