# Generated by Django 3.0.7 on 2020-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0009_new_attribute_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laikaobject',
            options={'permissions': [('bulk_upload_object', 'Can bulk upload object')]},
        ),
    ]
