# Generated by Django 3.0.7 on 2020-10-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0010_new_bulk_upload_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobjecttype',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
