# Generated by Django 3.1.2 on 2020-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0011_update_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='_metadata',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='laikaobject',
            name='data',
            field=models.JSONField(),
        ),
    ]
