# Generated by Django 3.1.2 on 2020-12-04 21:31

from django.db import migrations

from objects.migrate import AttributeRename, migrate_lo
from objects.system_types import PULL_REQUEST, USER


def rename_columns(apps, schema_editor):
    pr_renames = [
        AttributeRename(old='number', new='Number'),
        AttributeRename(old='repository', new='Repository'),
        AttributeRename(old='target', new='Target'),
        AttributeRename(old='source', new='Source'),
        AttributeRename(old='state', new='State'),
        AttributeRename(old='title', new='Title'),
        AttributeRename(old='is verified', new='Is Verified'),
        AttributeRename(old='is approved', new='Is Approved'),
        AttributeRename(old='web link', new='Web Link'),
        AttributeRename(old='is open', new='Is Open'),
        AttributeRename(old='approvers', new='Approvers'),
        AttributeRename(old='reporter', new='Reporter'),
        AttributeRename(old='created on', new='Created On'),
        AttributeRename(old='updated on', new='Updated On'),
        AttributeRename(old='organization', new='Organization'),
    ]
    user_renames = [
        AttributeRename(old='id', new='Id'),
        AttributeRename(old='first name', new='First Name'),
        AttributeRename(old='last name', new='Last Name'),
        AttributeRename(old='email', new='Email'),
        AttributeRename(old='is admin', new='Is Admin'),
        AttributeRename(old='is delegated admin', new='Is Delegated Admin'),
        AttributeRename(old='title', new='Title'),
        AttributeRename(old='organization name', new='Organization Name'),
        AttributeRename(old='mfa enabled', new='Mfa Enabled'),
        AttributeRename(old='mfa enforced', new='Mfa Enforced'),
    ]
    migrate_lo(PULL_REQUEST, rename=pr_renames)
    migrate_lo(USER, rename=user_renames)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0012_migrate_json_field'),
    ]

    operations = [
        migrations.RunPython(rename_columns),
    ]
