# Generated by Django 3.1.2 on 2020-12-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0014_add_source_and_connection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobject',
            name='is_manually_created',
            field=models.BooleanField(default=False),
        ),
    ]
