# Generated by Django 3.1.2 on 2021-01-28 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0013_adding_invalid_credential_error'),
        ('objects', '0015_laikaobject_is_manually_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobject',
            name='connection_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='laika_objects',
                to='integration.connectionaccount',
            ),
        ),
    ]
