# Generated by Django 3.1.2 on 2021-01-28 11:50

from django.db import migrations

from objects.migrate import migrate_lo
from objects.system_types import USER


def add_new_columns(apps, schema_editor):
    new_attributes = ['Groups']
    migrate_lo(USER, new=new_attributes)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0016_add_connection_account_reference'),
    ]

    operations = [
        migrations.RunPython(add_new_columns),
    ]
