# Generated by Django 3.1.2 on 2021-02-04 22:19

from django.db import migrations

from objects.migrate import migrate_lo
from objects.system_types import REPOSITORY


def remove_old_columns(apps, schema_editor):
    attributes = [
        'Public URL',
        'Criticality',
        'Is Active',
        'Is Public',
        'Owner',
        'Hosting Service',
    ]
    migrate_lo(REPOSITORY, delete=attributes)


def add_new_columns(apps, schema_editor):
    new_attributes = [
        'Owner',
        'Organization',
        'Public URL',
        'Is Active',
        'Is Public',
        'Updated At',
        'Created At',
    ]
    migrate_lo(REPOSITORY, new=new_attributes)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0018_migrate_pull_requests'),
    ]

    operations = [
        migrations.RunPython(remove_old_columns),
        migrations.RunPython(add_new_columns),
    ]
