# Generated by Django 3.1.2 on 2021-02-08 14:48

from django.db import migrations

from objects.migrate import migrate_lo
from objects.system_types import REPOSITORY


def remove_old_columns(apps, schema_editor):
    attributes = ['Owner']
    migrate_lo(REPOSITORY, delete=attributes)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0019_migrate_to_new_LO_repository'),
    ]

    operations = [
        migrations.RunPython(remove_old_columns),
    ]
