# Generated by Django 3.1.2 on 2021-02-09 19:22

from django.db import migrations

from objects.migrate import migrate_lo
from objects.system_types import PULL_REQUEST


def add_new_column(apps, schema_editor):
    new_attributes = ['Repository Visibility']
    migrate_lo(PULL_REQUEST, new=new_attributes)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0024_updating_user_laika_object_type'),
    ]

    operations = [
        migrations.RunPython(add_new_column),
    ]
