# Generated by Django 3.1.2 on 2021-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0025_adding_repository_visibility_to_pr_lo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(
                choices=[
                    ('BOOLEAN', 'Boolean'),
                    ('NUMBER', 'Number'),
                    ('TEXT', 'Text'),
                    ('DATE', 'Date'),
                    ('USER', 'User'),
                    ('SINGLE_SELECT', 'Single Select'),
                    ('JSON', 'Json'),
                ],
                max_length=100,
            ),
        ),
    ]
