# Generated by Django 3.1.2 on 2021-03-24 00:48

from django.db import migrations

from objects.migrate import migrate_lo
from objects.system_types import DEVICE


def delete_columns(apps, schema_editor):
    delete_attributes = ['Owner']
    migrate_lo(
        DEVICE,
        delete=delete_attributes,
    )


def add_new_columns(apps, schema_editor):
    new_attributes = ['Id', 'Owner', 'Source System', 'Connection Name']
    migrate_lo(DEVICE, new=new_attributes)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0027_migrate_change_request_transitions'),
    ]

    operations = [
        migrations.RunPython(delete_columns),
        migrations.RunPython(add_new_columns),
    ]
