# Generated by Django 3.1.12 on 2021-08-06 19:32
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def update_owners_in_account_objects(apps, schema_editor):
    logger.info('Started updating unassigned owners')
    Organization = apps.get_model('organization', 'Organization')
    for organization in Organization.objects.all():
        for ca in organization.connection_accounts.all():
            if not ca.created_by:
                continue
            accounts = ca.laika_objects.filter(
                object_type__type_name='account', is_manually_created=False
            )
            for account in accounts:
                owner = account.data.get('Owner', None)
                # Integrated accounts only have the email value.
                # They should have id, first_name, last_name and username
                if owner and 'id' not in owner:
                    created_user = {
                        'id': ca.created_by.id,
                        'email': ca.created_by.email,
                        'firstName': ca.created_by.first_name,
                        'lastName': ca.created_by.last_name,
                        'username': ca.created_by.username,
                    }
                    logger.info(
                        f'Updating owner with data {created_user}, '
                        f'in connection account: {ca}, '
                        f'in organization: {organization.name}'
                    )
                    account.data['Owner'] = created_user
                    account.save()
    logger.info('Ended updating unassigned owners')


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0028_adding_source_system_and_organization_device_lo'),
    ]

    operations = [migrations.RunPython(update_owners_in_account_objects)]
