# Generated by Django 3.1.12 on 2021-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0031_add_number_of_records_column_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobject',
            name='deleted_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
