# Generated by Django 3.1.12 on 2022-02-25 19:32

from django.db import migrations
from django.db.models import Q

from objects.system_types import BOOLEAN, User


def add_missing_user_attributes(apps, schema_editor):
    object_type_model = apps.get_model('objects', 'LaikaObjectType')
    attribute_model = apps.get_model('objects', 'Attribute')
    types = object_type_model.objects.filter(
        Q(display_name='Integration Users') | Q(display_name='User')
    )
    for object_type in types:
        object_type.display_name = 'Integration User'
        object_type.save()

    object_types = object_type_model.objects.filter(
        type_name='user',
        display_name__exact='Integration User',
        attributes__isnull=True,
    )

    for object_type in object_types:
        for attribute in User.attributes():
            attribute.update(
                {
                    'min_width': 150
                    if attribute.get('attribute_type') == BOOLEAN
                    else 200,
                    'object_type': object_type,
                    '_metadata': {'is_protected': True},
                }
            )
            attribute_model.objects.create(**attribute)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0032_add_deleted_at_attribute'),
    ]

    operations = [migrations.RunPython(add_missing_user_attributes)]
