# Generated by Django 3.1.12 on 2022-02-23 18:45

from django.db import migrations

from objects.system_types import BackgroundCheck


def add_missing_background_check_attributes(apps, schema_editor):
    object_type_model = apps.get_model('objects', 'LaikaObjectType')
    attribute_model = apps.get_model('objects', 'Attribute')
    types = object_type_model.objects.filter(type_name='background_check')

    for object_type in types:
        for attribute in BackgroundCheck.attributes():
            attribute.update(
                {
                    'min_width': attribute.get('min_width', 150),
                    'object_type': object_type,
                    '_metadata': {'is_protected': True},
                }
            )
            attribute_model.objects.get_or_create(
                object_type=object_type, name=attribute.get('name'), defaults=attribute
            )


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0033_add_missing_laika_object_attribute'),
    ]

    operations = [migrations.RunPython(add_missing_background_check_attributes)]
