# Generated by Django 3.1.12 on 2022-03-24 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0069_complete_onboarding_for_missing_orgs'),
        ('objects', '0034_update_lo_background_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laikaobjecttype',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='laika_object_types',
                to='organization.organization',
            ),
        ),
    ]
