# Generated by Django 3.1.12 on 2022-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0035_organization_object_types_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_required',
            field=models.BooleanField(default=False),
        )
    ]
