# Generated by Django 3.1.12 on 2022-03-16 15:46

from django.db import migrations

from objects.system_types import LO_REQUIRED_FIELDS


def update_attribute_is_required(apps, schema_editor):
    laika_object_type = apps.get_model('objects', 'LaikaObjectType')
    attribute_model = apps.get_model('objects', 'Attribute')
    lo_types = laika_object_type.objects.all()
    for lo_type in lo_types:
        if lo_type.type_name in LO_REQUIRED_FIELDS:
            attributes = attribute_model.objects.filter(object_type=lo_type)
            required_fields = LO_REQUIRED_FIELDS[lo_type.type_name]
            for attribute in attributes:
                if attribute.name in required_fields:
                    attribute.is_required = True
                    attribute.save()


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0036_attribute_is_required'),
    ]

    operations = [migrations.RunPython(update_attribute_is_required)]
