# Generated by Django 3.2.12 on 2022-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0037_update_lo_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='laikaobject',
            name='data_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
