# Generated by Django 3.1.12 on 2022-04-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0017_add_laika_object_alert'),
        ('objects', '0038_data_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaikaObjectAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='laika_object_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'laika_object',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alerts',
                        to='objects.laikaobject',
                    ),
                ),
            ],
        ),
    ]
