# Generated by Django 3.2.15 on 2022-10-23 21:06

from django.db import migrations

from objects.migrate import migrate_lo
from objects.system_types import MONITOR


def migrate_data(apps, schema_editor):
    migrate_lo(MONITOR, new=['Notification Type', 'Destination'], reorder=True)


class Migration(migrations.Migration):
    dependencies = [
        ('objects', '0041_update_lo_type_pull_request_description'),
    ]

    operations = [migrations.RunPython(migrate_data)]
