# Generated by Django 3.1.12 on 2022-02-01 23:25

import django.db.models.deletion
from django.db import migrations, models

import laika.storage
import population.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('fieldwork', '0045_evidence_run_account_lo_fetch'),
        ('audit', '0038_auditstatus_draft_report_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPopulation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('default_source', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                (
                    'pop_type',
                    models.CharField(
                        choices=[
                            ('vendor', 'vendor'),
                            ('laika_object', 'laika_object'),
                            ('people', 'people'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'template',
                    models.FileField(
                        max_length=512,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=population.models.population_templates_directory_path,
                    ),
                ),
                ('description', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('submitted', 'Submitted'),
                            ('accepted', 'Accepted'),
                        ],
                        default='open',
                        max_length=50,
                    ),
                ),
                (
                    'selected_source',
                    models.CharField(
                        choices=[
                            ('manual', 'manual'),
                            ('laika_source', 'laika_source'),
                        ],
                        default='laika_source',
                        max_length=50,
                    ),
                ),
                (
                    'selected_source_display_name',
                    models.CharField(blank=True, max_length=200),
                ),
                ('selected_source_icon', models.CharField(blank=True, max_length=200)),
                ('selected_source_color', models.CharField(blank=True, max_length=200)),
                ('raw_data', models.JSONField()),
                (
                    'data_file',
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=population.models.population_files_directory_path,
                    ),
                ),
                ('data_snapshot', models.JSONField()),
                ('filters', models.JSONField()),
                ('sample_logic', models.TextField()),
                ('sample_size', models.IntegerField()),
                (
                    'completeness_accuracy_attachment',
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=population.models.population_files_directory_path,
                    ),
                ),
                (
                    'audit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='populations',
                        to='audit.audit',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuditPopulationSample',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'population',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='population.auditpopulation',
                    ),
                ),
                (
                    'sample',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='population.sample',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AuditPopulationEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'evidence_request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fieldwork.evidence',
                    ),
                ),
                (
                    'population',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='population.auditpopulation',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='auditpopulation',
            name='evidence_request',
            field=models.ManyToManyField(
                related_name='populations',
                through='population.AuditPopulationEvidence',
                to='fieldwork.Evidence',
            ),
        ),
        migrations.AddField(
            model_name='auditpopulation',
            name='samples',
            field=models.ManyToManyField(
                related_name='populations',
                through='population.AuditPopulationSample',
                to='population.Sample',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='auditpopulation',
            unique_together={('display_id', 'audit')},
        ),
    ]
