# Generated by Django 3.1.12 on 2022-02-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0001_population_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationSource',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('selected_source_display_name', models.CharField(max_length=200)),
                ('selected_source_icon', models.CharField(max_length=200)),
                ('selected_source_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditpopulation',
            name='selected_source_color',
        ),
        migrations.RemoveField(
            model_name='auditpopulation',
            name='selected_source_display_name',
        ),
        migrations.RemoveField(
            model_name='auditpopulation',
            name='selected_source_icon',
        ),
        migrations.AddField(
            model_name='auditpopulation',
            name='source_info',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='population',
                to='population.populationsource',
            ),
        ),
    ]
