# Generated by Django 3.1.12 on 2022-02-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0002_create_population_source_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditpopulation',
            name='data_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditpopulation',
            name='filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditpopulation',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditpopulation',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditpopulation',
            name='sample_logic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditpopulation',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
