# Generated by Django 3.1.12 on 2022-02-04 04:50

from django.db import migrations


def add_population_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='populationFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0003_allow_null'),
    ]

    operations = [migrations.RunPython(add_population_feature_flag)]
