# Generated by Django 3.1.12 on 2022-02-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
        ('population', '0004_add_population_feature_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'pool',
                    models.CharField(
                        choices=[
                            ('lcl', 'LCL'),
                            ('all', 'All'),
                            ('laika', 'Laika'),
                            ('lcl-cx', 'LCL-CX'),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='population_comments',
                        to='comment.comment',
                    ),
                ),
                (
                    'population',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='population_comments',
                        to='population.auditpopulation',
                    ),
                ),
            ],
        ),
    ]
