# Generated by Django 3.1.12 on 2022-02-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
        ('population', '0005_populationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationcomment',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='population',
                to='comment.comment',
            ),
        ),
        migrations.AlterField(
            model_name='populationcomment',
            name='population',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='population.auditpopulation',
            ),
        ),
    ]
