# Generated by Django 3.2.12 on 2022-04-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0008_add_population_comment_permissions_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='data_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
