# Generated by Django 3.2.12 on 2022-04-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0010_add_auditor_group_population_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='configuration_answer_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditpopulation',
            name='configuration_answer_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='auditpopulation',
            name='configuration_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
