# Generated by Django 3.2.13 on 2022-05-25 17:42

import django.db.models.deletion
from django.db import migrations, models

import laika.storage
import population.models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0011_add_question_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationCompletenessAccuracy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=population.models.population_files_directory_path,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='auditpopulation',
            name='completeness_accuracy_attachment',
        ),
        migrations.AddField(
            model_name='populationcompletenessaccuracy',
            name='population',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='completeness_accuracy',
                to='population.auditpopulation',
            ),
        ),
    ]
