# Generated by Django 3.2.13 on 2022-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0013_add_completeness_accuracy_permissions_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='times_moved_back_to_open',
            field=models.IntegerField(default=0),
        ),
    ]
