# Generated by Django 3.2.13 on 2022-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0014_auditpopulation_times_moved_back_to_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='configuration_seed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
