# Generated by Django 3.2.13 on 2022-06-22 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0015_auditpopulation_configuration_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditpopulation',
            name='configuration_answer_column',
        ),
        migrations.RemoveField(
            model_name='auditpopulation',
            name='configuration_answer_type',
        ),
        migrations.RemoveField(
            model_name='auditpopulation',
            name='configuration_question',
        ),
    ]
