# Generated by Django 3.2.13 on 2022-07-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0016_auditpopulation_remove_configuration_question_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'population',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='population_data',
                        to='population.auditpopulation',
                    ),
                ),
            ],
        ),
    ]
