# Generated by Django 3.2.13 on 2022-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0017_auditpopulation_population_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='configuration_filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditpopulation',
            name='configuration_saved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
