# Generated by Django 3.2.13 on 2022-07-15 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0018_auditpopulation_add_configurations_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditpopulation',
            name='raw_data',
        ),
    ]
