# Generated by Django 3.2.14 on 2022-07-20 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0019_remove_auditpopulation_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditpopulation',
            name='template',
        ),
    ]
