# Generated by Django 3.2.15 on 2022-08-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0060_adding_fields_to_track_er_back_to_open_reasons'),
        ('population', '0021_populationdata_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationdata',
            name='evidence_request',
            field=models.ManyToManyField(
                related_name='population_sample',
                through='population.Sample',
                to='fieldwork.Evidence',
            ),
        ),
        migrations.AddField(
            model_name='sample',
            name='evidence_request',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='fieldwork.evidence',
            ),
        ),
        migrations.AddField(
            model_name='sample',
            name='population_data',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='population.populationdata',
            ),
        ),
    ]
