# Generated by Django 3.2.15 on 2022-08-26 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0022_add_er_sample_data_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
    ]
