# Generated by Django 3.2.15 on 2022-08-31 19:33

from django.db import migrations


def add_laika_source_population_feature_flag(apps, schema_editor):
    organization_model = apps.get_model('organization', 'Organization')
    flag_model = apps.get_model('feature', 'Flag')

    for organization in organization_model.objects.all():
        flag_model.objects.get_or_create(
            name='laikaSourcePopSamFeatureFlag',
            organization=organization,
            defaults={'is_enabled': False},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0023_remove_name_field_from_sample_table'),
    ]

    operations = [migrations.RunPython(add_laika_source_population_feature_flag)]
