# Generated by Django 3.2.15 on 2022-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0024_add_laika_source_population_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditpopulation',
            name='selected_source',
            field=models.CharField(
                choices=[('manual', 'manual'), ('laika_source', 'laika_source')],
                max_length=50,
            ),
        ),
    ]
