# Generated by Django 3.2.15 on 2022-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0025_alter_auditpopulation_selected_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='laika_source_configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
