# Generated by Django 3.2.15 on 2022-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('population', '0026_add_laika_source_conf_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpopulation',
            name='selected_default_source',
            field=models.CharField(
                blank=True, choices=[('People', 'People')], max_length=50, null=True
            ),
        ),
    ]
