# Generated by Django 3.2.15 on 2022-12-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fieldwork', '0068_new_columns_for_name_changed'),
        ('population', '0027_auditpopulation_selected_default_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='evidence_request',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='fieldwork.evidence',
            ),
        ),
        migrations.AlterField(
            model_name='sample',
            name='population_data',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='population.populationdata',
            ),
        ),
    ]
