# Generated by Django 3.2.15 on 2022-12-16 17:59

from django.db import migrations
from django.db.models import Q

from population.utils import set_sample_name


def set_sample_names(apps, schema_editor):
    sample_model = apps.get_model('population', 'Sample')
    samples = sample_model.objects.filter(Q(name__isnull=True) | Q(name__exact=''))
    for sample in samples:
        set_sample_name(sample)


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0029_sample_name'),
    ]

    operations = [
        migrations.RunPython(set_sample_names)
    ]
