# Generated by Django 3.0.7 on 2020-08-04 20:08

import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger('drive_migration')


def create_drive_for_existing_organizations(apps, groups):
    Organization = apps.get_model('organization', 'Organization')
    Drive = apps.get_model('drive', 'Drive')
    for organization in Organization.objects.all():
        drive = Drive.objects.create(organization=organization)
        logger.info(f'Drive with id {drive.id} created for organization {organization}')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('evidence', '0007_initial_version_drive'),
        ('organization', '0007_DateTimeField_instead_of_DateField'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='drive',
                        to='organization.Organization',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'drives',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                (
                    'drive',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='folders',
                        to='drive.Drive',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DriveEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'drive',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evidence',
                        to='drive.Drive',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='drive',
                        to='evidence.Evidence',
                    ),
                ),
                (
                    'folder',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evidence',
                        to='drive.Folder',
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_drive_for_existing_organizations),
    ]
