# Generated by Django 3.0.7 on 2020-08-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0007_DateTimeField_instead_of_DateField'),
        ('drive', '0001_initial_version_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='organization',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='drive',
                to='organization.Organization',
            ),
        ),
    ]
