# Generated by Django 3.0.7 on 2020-09-02 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0002_one_to_one_organization_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveevidence',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='owned_evidence',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
