# Generated by Django 3.0.7 on 2020-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0003_owner_in_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveevidence',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
