# Generated by Django 3.1.2 on 2020-12-29 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0004_adding_is_template'),
        ('evidence', '0008_add_system_tag_evidence'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE OR REPLACE VIEW tags_and_system_tags AS
                WITH tags_and_system_tags(organization_id, tag_id) AS (
                    SELECT DISTINCT drive.organization_id AS organization_id,
                    subtask_tags.id AS tag_id
                    FROM drive_driveevidence drive_evidence 
                    INNER JOIN drive_drive drive 
                    ON drive.id = drive_evidence.drive_id 
                    INNER JOIN evidence_evidence evidence 
                    ON evidence.id = drive_evidence.evidence_id
                    LEFT JOIN evidence_systemtagevidence system_tag_evidence 
                    ON evidence.id = system_tag_evidence.evidence_id
                    INNER JOIN tag_tag system_tags 
                    ON system_tags.id = system_tag_evidence.tag_id
                    LEFT JOIN program_subtask evidence_subtasks
                    ON evidence_subtasks.id = system_tags."name"::uuid
                    LEFT JOIN program_subtasktag evidence_subtask_tags 
                    ON evidence_subtask_tags.subtask_id = evidence_subtasks.id
                    LEFT JOIN tag_tag subtask_tags ON subtask_tags.id = evidence_subtask_tags.tag_id
                    
                    UNION ALL
                    
                    SELECT DISTINCT drive.organization_id AS organization_id,
                    evidence_tags.id AS tag_id
                    FROM drive_driveevidence drive_evidence 
                    INNER JOIN drive_drive drive 
                    ON drive.id = drive_evidence.drive_id 
                    INNER JOIN evidence_evidence evidence 
                    ON evidence.id = drive_evidence.evidence_id
                    LEFT JOIN evidence_tagevidence tag_evidence 
                    ON tag_evidence.evidence_id = evidence.id 
                    INNER JOIN tag_tag evidence_tags 
                    ON evidence_tags.id = tag_evidence.tag_id
                    ORDER BY tag_id
                )
                SELECT *, ROW_NUMBER() OVER (ORDER BY tags.tag_id) AS id 
                FROM tags_and_system_tags tags 
        '''
        ),
    ]
