# Generated by Django 3.1.2 on 2021-01-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0005_filter_tags_and_system_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsAndSystemTags',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'db_table': 'tags_and_system_tags',
                'managed': False,
            },
        ),
    ]
