# Generated by Django 3.1.2 on 2021-01-12 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0009_fixing_view_unions'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            DROP VIEW IF EXISTS tags_and_system_tags;
        '''
        )
    ]
