# Generated by Django 3.1.2 on 2021-01-19 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0010_deleting_tags_and_system_tags_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsAndSystemTags',
        ),
    ]
