# Generated by Django 3.0.2 on 2020-02-26 23:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import laika.storage
import policy.models
from laika.constants import CATEGORIES


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_make_address_not_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('display_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                (
                    'category',
                    models.CharField(
                        blank=True, choices=CATEGORIES, default='', max_length=100
                    ),
                ),
                (
                    'draft',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=policy.models.policy_file_directory_path,
                    ),
                ),
                ('draft_key', models.CharField(max_length=20)),
                (
                    'administrator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy_managed',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'approver',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy_approver',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policies',
                        to='organization.Organization',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy_owned',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='PublishedPolicy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                (
                    'contents',
                    models.FileField(
                        max_length=1024,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=policy.models.published_policy_file_directory_path,
                    ),
                ),
                ('comment', models.TextField(blank=True)),
                ('published_key', models.CharField(max_length=20)),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='policy.Policy',
                    ),
                ),
                (
                    'published_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='published_policies',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'published policy',
                'verbose_name_plural': 'published policies',
                'unique_together': {('version', 'policy')},
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(
                fields=['draft_key'], name='policy_poli_draft_k_6cfec1_idx'
            ),
        ),
    ]
