# Generated by Django 3.0.3 on 2020-03-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0001_initial_tag_model'),
        ('policy', '0002_recreate_policy_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy_tags',
                        to='policy.Policy',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='tags',
            field=models.ManyToManyField(
                related_name='policies', through='policy.PolicyTag', to='tag.Tag'
            ),
        ),
    ]
