# Generated by Django 3.0.7 on 2020-11-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0005_change_published_date_to_datetime'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policy',
            name='policy_poli_draft_k_6cfec1_idx',
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(
                fields=['draft_key', 'policy_text'],
                name='policy_poli_draft_k_2d003d_idx',
            ),
        ),
    ]
