# Generated by Django 3.0.7 on 2020-11-04 21:22

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0006_add_new_column_for_search'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policy',
            name='policy_poli_draft_k_2d003d_idx',
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(
                fields=['draft_key'], name='policy_poli_draft_k_6cfec1_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['policy_text'], name='policy_poli_policy__f7b525_hash'
            ),
        ),
    ]
