# Generated by Django 3.1.2 on 2020-11-09 14:42

import logging

from django.db import migrations
from django.db.models import Q

from laika.utils.files import get_docx_file_content

logger = logging.getLogger('policy_migration')


def fill_policy_text(apps, schema_editor):
    Policy = apps.get_model('policy', 'Policy')
    policies = Policy.objects.filter(
        Q(is_published=True) & (Q(policy_text__isnull=True) | Q(policy_text=''))
    )
    policy_id = ''
    try:
        for p in policies:
            policy_id = p.id
            logger.info(f'Getting file content for policy: {policy_id}')
            p.policy_text = get_docx_file_content(p.draft, policy_id)

        Policy.objects.bulk_update(policies, ['policy_text'])
    except Exception as e:
        logger.exception(f'Failed filling policy: {policy_id} text with error {e}')


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0008_making_field_optional'),
    ]

    operations = [migrations.RunPython(fill_policy_text)]
