# Generated by Django 3.1.2 on 2020-11-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0010_fill_polici_text_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
