# Generated by Django 3.1.2 on 2021-03-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0019_adding_values_to_csm_ca_users'),
        ('evidence', '0021_add_evidence_db_constraints'),
        ('policy', '0011_change_back_updated_and_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPolicy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'description',
                    models.CharField(
                        choices=[
                            ('Information Security', 'Information Security'),
                            ('Human Resources Policy', 'Human Resources Policy'),
                            ('Asset Management Policy', 'Asset Management Policy'),
                            (
                                'Business Continuity & Disaster Recovery Policy',
                                'Business Continuity & Disaster Recovery Policy',
                            ),
                            (
                                'Capacity & Performance Planning Policy',
                                'Capacity & Performance Planning Policy',
                            ),
                            (
                                'Change Management & Configuration Management',
                                'Change Management & Configuration Management',
                            ),
                            (
                                'Application Security Policy',
                                'Application Security Policy',
                            ),
                            (
                                'System, Network, and Cloud Security Policy',
                                'System, Network, and Cloud Security Policy',
                            ),
                            (
                                'Continuous Monitoring Policy',
                                'Continuous Monitoring Policy',
                            ),
                            (
                                'Cryptographic Protections Policy',
                                'Cryptographic Protections Policy',
                            ),
                            ('Data Handling Policy', 'Data Handling Policy'),
                            ('Endpoint Security Policy', 'Endpoint Security Policy'),
                            (
                                'Identification & Authentication Policy',
                                'Identification & Authentication Policy',
                            ),
                            ('Incident Response Policy', 'Incident Response Policy'),
                            (
                                'Vulnerability/Threat Management Policy',
                                'Vulnerability/Threat Management Policy',
                            ),
                            (
                                'Physical & Environmental Security Policy',
                                'Physical & Environmental Security Policy',
                            ),
                            ('Privacy Operations Policy', 'Privacy Operations Policy'),
                            ('Risk Management Policy', 'Risk Management Policy'),
                            (
                                'Third-Party Management Policy',
                                'Third-Party Management Policy',
                            ),
                        ],
                        max_length=512,
                    ),
                ),
                ('use_laika_template', models.BooleanField(default=True)),
                (
                    'file',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='onboarding_policy',
                        to='evidence.evidence',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='onboarding_policies',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
    ]
