# Generated by Django 3.1.2 on 2021-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0012_add_onboarding_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingpolicy',
            name='description',
            field=models.CharField(
                choices=[
                    ('Information Security Policy', 'Information Security Policy'),
                    (
                        'Business Continuity and Disaster Recovery Plan',
                        'Business Continuity and Disaster Recovery Plan',
                    ),
                    (
                        'Compliance and Risk Management Policy',
                        'Compliance and Risk Management Policy',
                    ),
                    (
                        'Configuration and Change Management Policy',
                        'Configuration and Change Management Policy',
                    ),
                    (
                        'Data Protection and Handling Policy',
                        'Data Protection and Handling Policy',
                    ),
                    ('Employee Handbook', 'Employee Handbook'),
                    ('Hiring Policy', 'Hiring Policy'),
                    ('Incident Response Policy', 'Incident Response Policy'),
                    ('Privacy Policy', 'Privacy Policy'),
                    (
                        'Supplier Risk Management Policy',
                        'Supplier Risk Management Policy',
                    ),
                ],
                max_length=512,
            ),
        ),
    ]
