# Generated by Django 3.1.12 on 2021-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0014_policy_is_visible_in_dataroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingpolicy',
            name='description',
            field=models.CharField(
                choices=[
                    ('Information Security Policy', 'Information Security Policy'),
                    (
                        'Business Continuity and Disaster Recovery Plan',
                        'Business Continuity and Disaster Recovery Plan',
                    ),
                    (
                        'Compliance and Risk Management Policy',
                        'Compliance and Risk Management Policy',
                    ),
                    (
                        'Configuration and Change Management Policy',
                        'Configuration and Change Management Policy',
                    ),
                    (
                        'Data Protection and Handling Policy',
                        'Data Protection and Handling Policy',
                    ),
                    ('Employee Handbook', 'Employee Handbook'),
                    ('Hiring Policy', 'Hiring Policy'),
                    ('Incident Response Policy', 'Incident Response Policy'),
                    ('Privacy Notice Policy', 'Privacy Notice Policy'),
                    (
                        'Supplier Risk Management Policy',
                        'Supplier Risk Management Policy',
                    ),
                ],
                max_length=512,
            ),
        ),
    ]
