# Generated by Django 3.1.12 on 2021-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0015_onboarding_duplicate_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
