# Generated by Django 3.1.12 on 2021-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0007_add_recurrent_schedule_choices'),
        ('policy', '0016_add_policy_required_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='action_items',
            field=models.ManyToManyField(
                blank=True, related_name='policies', to='action_item.ActionItem'
            ),
        ),
    ]
