# Generated by Django 3.1.12 on 2022-01-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0039_create_roadmap_permissions'),
        ('policy', '0017_add_action_items_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='control_family',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='policy',
                to='control.controlpillar',
            ),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(
                choices=[('Policy', 'Policy'), ('Procedure', 'Procedure')],
                default='Policy',
                max_length=255,
            ),
        ),
    ]
