# Generated by Django 3.1.12 on 2022-02-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0018_control_family_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_draft_edited',
            field=models.BooleanField(default=False),
        ),
    ]
