# Generated by Django 3.1.12 on 2022-02-07 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0019_policy_is_draft_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProxy',
            fields=[],
            options={
                'verbose_name': 'Deleted Policy',
                'verbose_name_plural': 'Deleted Policies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policy.policy',),
        ),
    ]
