# Generated by Django 3.1.12 on 2022-01-31 16:39

from django.db import migrations
from django.db.models import F

from feature.constants import new_controls_feature_flag
from policy.constants import COMPLIANCE_RELEASE_DATE


def set_is_draft_edited_to_true(apps, schema_editor):
    flag = apps.get_model('feature', 'Flag')
    organization = apps.get_model('organization', 'Organization')
    policy = apps.get_model('policy', 'Policy')

    my_compliance_org_ids = organization.objects.filter(
        id__in=flag.objects.filter(
            name=new_controls_feature_flag, is_enabled=True
        ).values_list('organization_id', flat=True)
    ).values_list('id', flat=True)

    policy.objects.filter(
        organization_id__in=my_compliance_org_ids,
        created_at__gte=COMPLIANCE_RELEASE_DATE,
        updated_at__gt=F('created_at'),
    ).update(is_draft_edited=True)


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0020_deleted_policy_version_proxy'),
    ]

    operations = [migrations.RunPython(set_is_draft_edited_to_true)]
