# Generated by Django 3.2.13 on 2022-06-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0021_set_is_draft_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpolicy',
            name='approved_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='published_approved_policies',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='publishedpolicy',
            name='owned_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='published_owned_policies',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
