# Generated by Django 3.2.13 on 2022-06-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0009_comment_permissions_auditor'),
        ('policy', '0023_migrate_owner_appover_from_policy_to_publish_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy_comments',
                        to='comment.comment',
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='policy_comments',
                        to='policy.policy',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='comments',
            field=models.ManyToManyField(
                related_name='policies',
                through='policy.PolicyComment',
                to='comment.Comment',
            ),
        ),
    ]
