# Generated by Django 3.2.15 on 2022-08-16 15:19

from django.db import migrations, models

import laika.storage
import policy.models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0024_add_policy_comment_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpolicy',
            name='embedding',
            field=models.FileField(
                blank=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=policy.models.policy_embedding_file_directory_path,
            ),
        ),
    ]
