# Generated by Django 3.1.2 on 2020-11-23 21:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0008_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('url', models.CharField(max_length=512, unique=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='links',
                        to='organization.organization',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'links',
            },
        ),
    ]
