# Generated by Django 3.1.2 on 2020-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('link', '0001_link_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
