# Generated by Django 3.1.6 on 2021-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('link', '0002_created_at_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
