# Generated by Django 3.1.12 on 2021-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('link', '0003_expiration_date_to_date_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
