SQL_QUERY_PLAYBOOK_EVIDENCE = '''
SELECT
        DISTINCT 'DOCUMENTS' AS evidence_type,
        CC.NAME AS framework_name,
        PT.CATEGORY AS category_name,
        EE.FILE AS evidence_file
    FROM PUBLIC.EVIDENCE_EVIDENCE EE
    LEFT JOIN PUBLIC.EVIDENCE_SYSTEMTAGEVIDENCE STE
        ON EE.ID = STE.EVIDENCE_ID
    LEFT JOIN PUBLIC.TAG_TAG TT ON STE.TAG_ID = TT.ID
    LEFT JOIN PUBLIC.PROGRAM_SUBTASK PS ON TT.name = PS.ID::TEXT
    LEFT JOIN PUBLIC.PROGRAM_SUBTASKCERTIFICATIONSECTION SCS
        ON PS.ID = SCS.SUBTASK_ID
    LEFT JOIN PUBLIC.CERTIFICATION_CERTIFICATIONSECTION CCS
        ON SCS.CERTIFICATION_SECTION_ID = CCS.ID
    LEFT JOIN PUBLIC.CERTIFICATION_CERTIFICATION CC
        ON CCS.CERTIFICATION_ID = CC.ID
    LEFT JOIN PUBLIC.PROGRAM_TASK PT ON PS.TASK_ID = PT.ID
    LEFT JOIN PUBLIC.PROGRAM_PROGRAM PP2 ON PT.PROGRAM_ID = PP2.ID
    LEFT JOIN PUBLIC.ORGANIZATION_ORGANIZATION OO
        ON PP2.ORGANIZATION_ID = OO.ID
    WHERE OO.ID=%s AND EE.TYPE != 'POLICY' AND PP2.ID IN ({})
    UNION ALL
    SELECT
        'POLICY' AS EVIDENCE_TYPE,
        '' AS FRAMEWORK_NAME,
        '' AS CATEGORY_NAME,
        DRAFT AS EVIDENCE_FILE
    FROM
        PUBLIC.POLICY_POLICY
    WHERE ORGANIZATION_ID = %s AND IS_PUBLISHED = true
    ORDER BY evidence_type, framework_name, category_name;
'''
