# Generated by Django 3.2.13 on 2022-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'type',
                    models.CharField(
                        choices=[('policy', 'policy'), ('question', 'question')],
                        max_length=100,
                    ),
                ),
                ('key', models.CharField(default='', max_length=75)),
            ],
        ),
        migrations.AddIndex(
            model_name='index',
            index=models.Index(
                fields=['key', 'type'], name='search_inde_key_1484b3_idx'
            ),
        ),
    ]
