# Generated by Django 3.0.2 on 2020-01-30 16:59

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations

from laika.aws.secrets import get_secret


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        User = apps.get_model('user', 'User')

        ENVIRONMENT = os.getenv("ENVIRONMENT")
        DJANGO_SETTINGS = get_secret(f'{ENVIRONMENT}/laika-app/settings')

        DJANGO_SUPERUSER_NAME = DJANGO_SETTINGS['DJANGO_SUPERUSER_NAME']
        DJANGO_SUPERUSER_EMAIL = DJANGO_SETTINGS['DJANGO_SUPERUSER_EMAIL']
        DJANGO_SUPERUSER_PASSWORD = DJANGO_SETTINGS['DJANGO_SUPERUSER_PASSWORD']

        User.objects.create(
            username=DJANGO_SUPERUSER_NAME,
            email=DJANGO_SUPERUSER_EMAIL,
            password=make_password(DJANGO_SUPERUSER_PASSWORD),
            is_superuser=True,
            is_staff=True,
            first_name='Site',
            last_name='Admin',
        )

    operations = [
        migrations.RunPython(generate_superuser),
    ]
