# Generated by Django 3.0.2 on 2020-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_create_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SuperAdmin', 'SuperAdmin'),
                    ('OrganizationAdmin', 'OrganizationAdmin'),
                    ('OrganizationMember', 'OrganizationMember'),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
