# Generated by Django 3.0.3 on 2020-03-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_add_existing_users_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        )
    ]
