# Generated by Django 3.0.3 on 2020-03-23 21:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0005_auto_20200304_1700'),
        ('user', '0007_remove_created_at_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='officers',
                        to='organization.Organization',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='officer',
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
    ]
