# Generated by Django 3.0.3 on 2020-04-07 19:18

from django.db import migrations


def add_default_permissions_to_all_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    global_menu_permissions = Permission.objects.filter(
        codename__in=[
            'view_plan',
            'view_conciergerequest',
            'view_control',
            'view_dataroom',
            'view_document',
            'view_libraryentry',
            'view_organization',
            'view_policy',
            'view_program',
            'view_training',
            'view_user',
            'view_vendor',
        ]
    )
    groups = [
        'premium_admin',
        'premium_member',
        'premium_super',
        'starter_admin',
        'starter_member',
        'starter_super',
        'teaser_admin',
        'teaser_member',
        'teaser_super',
    ]

    for group in Group.objects.filter(name__in=groups):
        for permission in global_menu_permissions:
            group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0008_import_dynamo_to_officer'),
        ('dataroom', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_default_permissions_to_all_groups)]
