# Generated by Django 3.0.3 on 2020-04-02 17:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0005_auto_20200304_1700'),
        ('user', '0009_add_default_permissions_to_all_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('charter', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teams',
                        to='organization.Organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[('Chair', 'Chair'), ('Member', 'Member')],
                        max_length=50,
                    ),
                ),
                ('phone', models.CharField(max_length=50)),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='user.Team',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_member',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
