# Generated by Django 3.0.3 on 2020-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0011_import_dynamo_to_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Required. 150 characters or fewer.            Letters, digits and'
                    ' @/./+/-/_ only.'
                ),
                max_length=150,
                verbose_name='username',
            ),
        ),
    ]
