# Generated by Django 3.0.7 on 2020-07-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0012_updating_username_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
