# Generated by Django 3.0.7 on 2020-07-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0013_user_DateTimeField_instead_of_DateField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
