# Generated by Django 3.0.7 on 2020-09-02 16:41

from django.db import migrations, models

from user.models import ROLES


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0015_create_additional_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=ROLES, max_length=100),
        ),
    ]
