# Generated by Django 3.0.7 on 2020-08-25 21:18

from django.db import migrations

from organization.constants import TIERS


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0017_create_groups_for_sales_role'),
    ]

    def add_control_permissions_to_groups(apps, schema):
        Permission = apps.get_model('auth', 'Permission')
        Group = apps.get_model('auth', 'Group')
        groups = Group.objects.filter(name__endswith='_sales')
        control_permissions = Permission.objects.filter(
            codename__in=[
                'add_dataroom',
                'change_dataroom',
                'delete_dataroom',
                'view_dataroom',
                'add_dataroomevidence',
                'change_dataroomevidence',
                'delete_dataroomevidence',
                'view_dataroomevidenceadd_libraryentry',
                'change_libraryentry',
                'delete_libraryentry',
                'view_libraryentry',
                'bulk_upload_library',
            ]
        )
        for g in groups:
            for sales_permission in control_permissions:
                g.permissions.add(sales_permission)

    operations = [migrations.RunPython(add_control_permissions_to_groups)]
