# Generated by Django 3.0.7 on 2020-10-13 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0018_add_permissions_to_sales_role'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into public.auth_group_permissions (group_id, permission_id)
            (SELECT g.id AS group_id,
                    p.id AS permission_id
            FROM public.auth_group g
            cross join public.auth_permission p
            WHERE g.name ilike '%_sales'
            AND p.codename in (
                'add_dataroom',
                'change_dataroom',
                'delete_dataroom',
                'view_dataroom',
                'add_dataroomevidence',
                'change_dataroomevidence',
                'delete_dataroomevidence',
                'view_dataroomevidence',
                'add_libraryentry',
                'change_libraryentry',
                'delete_libraryentry',
                'view_libraryentry',
                'bulk_upload_library',
                'add_evidence',
                'change_evidence',
                'delete_evidence',
                'view_evidence',
                'add_tagevidence',
                'change_tagevidence',
                'delete_tagevidence',
                'view_tagevidence',
                'rename_evidence',
                'add_driveevidence',
                'change_driveevidence',
                'delete_driveevidence',
                'view_driveevidence'
            ))
            ON CONFLICT DO NOTHING;

            COMMIT;
        '''
        )
    ]
