# Generated by Django 3.0.7 on 2020-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0019_fix_salesperson_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='email_preference',
            field=models.CharField(
                choices=[('Never', 'Never'), ('Daily', 'Daily'), ('Weekly', 'Weekly')],
                default='Weekly',
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(email_preference__in=['Never', 'Daily', 'Weekly']),
                name='user_user_email_preference_valid',
            ),
        ),
    ]
