# Generated by Django 3.1.2 on 2020-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0020_add_email_preference_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='first name'
            ),
        ),
    ]
