# Generated by Django 3.1.2 on 2021-01-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0022_making_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert_preference',
            field=models.CharField(
                choices=[
                    ('Never', 'Never'),
                    ('Daily', 'Daily'),
                    ('Immediately', 'Immediately'),
                ],
                default='Daily',
                max_length=50,
            ),
        ),
    ]
