# Generated by Django 3.1.2 on 2021-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0023_user_alert_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visual_preferences',
            field=models.JSONField(null=True),
        ),
    ]
