# Generated by Django 3.1.2 on 2021-01-25 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0024_user_visual_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='visual_preferences',
            new_name='user_preferences',
        ),
    ]
