# Generated by Django 3.1.2 on 2021-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0025_auto_20210125_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
