# Generated by Django 3.1.2 on 2021-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0026_auto_20210125_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                help_text=(
                    'Required. 150 characters or fewer.            Letters, digits and'
                    ' @/./+/-/_ only.'
                ),
                max_length=150,
                verbose_name='username',
            ),
        ),
    ]
