# Generated by Django 3.1.2 on 2021-02-08 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0027_making_username_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'permissions': [
                    ('change_user_preferences', 'Can change user preferences')
                ]
            },
        ),
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike '%_admin' 
                     OR g.name ilike '%_super' 
                     OR g.name ilike '%_member'
                  )
                  AND p.codename = ANY (array [
                    'change_user_preferences']
                    )
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        ),
    ]
