# Generated by Django 3.1.2 on 2021-02-11 22:42

from django.db import migrations, models

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0028_add_user_preferences_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_preferences',
            field=models.JSONField(
                blank=True, default=user.models.default_user_preferences
            ),
        ),
    ]
