# Generated by Django 3.1.2 on 2021-02-11 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0029_add_default_user_preferences'),
    ]

    def populate_user_preferences(apps, schema):
        User = apps.get_model('user', 'User')
        for user in User.objects.all():
            profile = {'emails': user.email_preference, 'alerts': user.alert_preference}
            user.user_preferences['profile'] = profile
            user.save()

    operations = [
        migrations.RunPython(populate_user_preferences),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_user_email_preference_valid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alert_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_preference',
        ),
    ]
