# Generated by Django 3.1.2 on 2021-02-19 21:28

from django.db import migrations, models

import laika.storage
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0030_migrate_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(
                blank=True,
                null=True,
                max_length=1024,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=user.models.user_picture_directory_path,
            ),
        ),
    ]
