# Generated by Django 3.1.2 on 2021-03-05 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0032_add_people_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='manager_user',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
