# Generated by Django 3.1.2 on 2021-03-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0014_adding_aws_error'),
        ('user', '0033_update_manager_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connection_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='people',
                to='integration.connectionaccount',
            ),
        ),
    ]
