# Generated by Django 3.1.2 on 2021-03-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0034_people_integration_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='user.user',
                    ),
                ),
            ],
        ),
    ]
