# Generated by Django 3.1.2 on 2021-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0012_add_audit_firm'),
        ('user', '0035_create_auditor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='audit_firms',
            field=models.ManyToManyField(
                related_name='auditors',
                through='audit.AuditorAuditFirm',
                to='audit.AuditFirm',
            ),
        ),
    ]
