# Generated by Django 3.1.2 on 2021-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0036_add_audit_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discovery_state',
            field=models.CharField(
                choices=[
                    ('New', 'New'),
                    ('Ignored', 'Ignored'),
                    ('Confirmed', 'Confirmed'),
                ],
                default='Confirmed',
                max_length=25,
            ),
        ),
    ]
