# Generated by Django 3.1.2 on 2021-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0037_discovery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa',
            field=models.BooleanField(default=False),
        ),
    ]
