# Generated by Django 3.1.6 on 2021-04-28 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0038_add_mfa_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='user',
            field=models.OneToOneField(
                help_text=(
                    '\n    First_name, last_name, email, role, password and username'
                    ' (email)\n    are required when creating a new audit user.\n    '
                ),
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
