# Generated by Django 3.1.2 on 2021-05-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0040_add_concierge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finch_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
