# Generated by Django 3.1.2 on 2021-05-31 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0041_add_finch_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierge',
            name='user',
            field=models.OneToOneField(
                help_text=(
                    '\n    first_name, last_name, email, role, password and username'
                    ' (email)\n    are required when creating a new concierge'
                    ' user.\n    '
                ),
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='concierge',
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
