# Generated by Django 3.1.6 on 2021-06-11 16:22

from django.db import migrations, models

from user.models import EMPLOYMENT_STATUS_ACTIVE, EMPLOYMENT_STATUS_INACTIVE


def restore_data_from_employee_field(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for item in User.objects.all().iterator():
        new_value = None
        if item.employed is True:
            new_value = EMPLOYMENT_STATUS_ACTIVE
        elif item.employed is False:
            new_value = EMPLOYMENT_STATUS_INACTIVE
        if new_value:
            item.employment_status = new_value
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0042_add_concierge_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('potential_hire', 'Potential Hire'),
                    ('active', 'Active'),
                    ('inactive', 'Inactive'),
                ],
                max_length=100,
            ),
        ),
        migrations.RunPython(
            restore_data_from_employee_field, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='user',
            name='employed',
        ),
    ]
