# Generated by Django 3.1.6 on 2021-06-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0043_add_employment_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('potential_hire', 'Potential Hire'),
                    ('active', 'Active'),
                    ('inactive', 'Inactive'),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
