# Generated by Django 3.1.6 on 2021-06-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0044_allow_null_for_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_check_passed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('na', 'N/A'),
                    ('pending', 'Pending'),
                    ('passed', 'Passed'),
                    ('flagged', 'Flagged'),
                ],
                max_length=50,
            ),
        ),
    ]
