# Generated by Django 3.1.6 on 2021-06-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0045_add_background_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_check_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('na', 'N/A'),
                    ('pending', 'Pending'),
                    ('passed', 'Passed'),
                    ('flagged', 'Flagged'),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
