# Generated by Django 3.1.6 on 2021-07-05 22:40

from django.db import migrations


def create_permission(apps, model, codename, name):
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    obj_content_type = content_type.objects.get_for_model(model)
    content_type = content_type.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    permission.objects.get_or_create(
        codename=codename, name=name, content_type=content_type
    )


permissions = [
    ('view_fieldwork', 'Can see fieldwork'),
]


def create_user_permissions(apps, schema_editor):
    user_model = apps.get_model('user', 'User')

    for p in permissions:
        create_permission(apps, user_model, p[0], p[1])


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0046_allow_null_for_background_status'),
    ]

    operations = [
        migrations.RunPython(create_user_permissions),
        migrations.RunSQL(
            '''
                BEGIN;
                INSERT into
                   public.auth_group_permissions (group_id, permission_id) (
                   SELECT
                      g.id AS group_id, p.id AS permission_id 
                   FROM
                      public.auth_group g 
                      cross join
                         public.auth_permission p 
                      join django_content_type ct on ct.id = p.content_type_id 
                   WHERE g.name ilike '%_super%'
                      AND p.codename = 'view_fieldwork'
                        AND ct.app_label = 'user' AND ct.model ='user'
                    )
                ON CONFLICT DO NOTHING;
                COMMIT;
            '''
        ),
    ]
