# Generated by Django 3.1.12 on 2021-07-27 21:47

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0049_order_by_organization_first_name'),
    ]

    operations = [
        UnaccentExtension(),
    ]
