# Generated by Django 3.1.12 on 2021-08-09 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor', '0013_add_display_id_to_organization_monitor'),
        ('user', '0050_add_unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatcherList',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'organization_monitor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='watchers',
                        to='monitor.organizationmonitor',
                    ),
                ),
                (
                    'users',
                    models.ManyToManyField(
                        blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
