# Generated by Django 3.1.12 on 2021-08-04 17:23

from django.db import migrations, models
from django.db.models import Q

from user.models import BACKGROUND_CHECK_STATUS_PASSED


def set_value_field_by_default(apps, schema_editor):
    User = apps.get_model('user', 'User')
    Training = apps.get_model('training', 'Training')
    Alumni = apps.get_model('training', 'Alumni')

    trainings_by_role = {}

    def is_compliant_completed(user):
        return (
            user.security_training
            and user.background_check_status == BACKGROUND_CHECK_STATUS_PASSED
            and user.background_check_passed_on is not None
        )

    def is_security_training_completed(user, training_ids):
        return Alumni.objects.filter(
            training__id__in=training_ids, user=user
        ).values_list('id', flat=True).count() == len(training_ids)

    for user in User.objects.prefetch_related('organization').all().iterator():
        if user.role and user.role not in trainings_by_role:
            trainings_by_role[user.role] = (
                Training.objects.filter(organization=user.organization)
                .filter(Q(roles__contains=user.role))
                .values_list('id', flat=True)
            )
        user_training_ids = trainings_by_role.get(user.role, [])
        user.security_training = is_security_training_completed(user, user_training_ids)
        user.compliant_completed = is_compliant_completed(user)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0051_create_watcher_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compliant_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='security_training',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_value_field_by_default, reverse_code=migrations.RunPython.noop
        ),
    ]
