# Generated by Django 3.1.12 on 2021-09-02 23:15

from django.db import migrations, models


def map_employment_values_to_choices(apps, schema_editor):
    user = apps.get_model('user', 'User')
    map_subtype = {
        'Full-time': 'full_time',
        'Full-Time': 'full_time',
        'Part-time': 'part_time',
        'Part-Time': 'part_time',
        'Intern': 'intern',
        'Individual Contractor': 'individual_contractor',
        'Temporary': 'temp',
    }
    map_type = {'Employee': 'employee', 'Contractor': 'contractor'}
    for user in user.objects.all().iterator():
        _employment_type = user.employment_type
        _employment_subtype = user.employment_subtype
        if _employment_type not in map_type.values():
            user.employment_type = map_type.get(_employment_type)
        if _employment_subtype not in map_subtype.values():
            user.employment_subtype = map_subtype.get(_employment_subtype)
        if _employment_subtype is None and _employment_type in map_subtype:
            user.employment_subtype = map_subtype.get(_employment_type)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0055_remove_watcherlist_organization_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_subtype',
            field=models.CharField(
                blank=True,
                choices=[
                    ('full_time', 'Full-time'),
                    ('part_time', 'Part-time'),
                    ('intern', 'Intern'),
                    ('temp', 'Temporary'),
                    ('seasonal', 'Seasonal'),
                    ('individual_contractor', 'Individual Contractor'),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.CharField(
                blank=True,
                choices=[('contractor', 'Contractor'), ('employee', 'Employee')],
                max_length=100,
                null=True,
            ),
        ),
        migrations.RunPython(
            map_employment_values_to_choices, reverse_code=migrations.RunPython.noop
        ),
    ]
