# Generated by Django 3.1.12 on 2021-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0056_employment_type_subtype_to_choices'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
