# Generated by Django 3.1.12 on 2021-09-08 14:16

import django.contrib.auth.models
from django.db import migrations, models

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0057_add_soft_delete_to_users'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserSoftDeleteManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=('email',),
                name='unique_email',
            ),
        ),
    ]
