# Generated by Django 3.1.12 on 2021-10-01 18:44

import django.contrib.auth.models
from django.db import migrations

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0058_modify_unique_email_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[],
            options={
                'verbose_name': 'Soft Deleted User',
                'verbose_name_plural': 'Soft Deleted Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', user.models.UserSoftDeleteManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
