# Generated by Django 3.1.12 on 2021-11-17 17:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0059_userproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'token',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('temporary_code', models.CharField(max_length=64)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='magic_link',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
