# Generated by Django 3.1.12 on 2022-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0060_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='policies_reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
