# Generated by Django 3.1.12 on 2022-02-15 20:26

from django.db import migrations


def create_permission(apps, model, codename, name):
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    obj_content_type = content_type.objects.get_for_model(model)
    content_type = content_type.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    permission.objects.get_or_create(
        codename=codename, name=name, content_type=content_type
    )


permissions = [
    ('view_help_center', 'Can see help center'),
]


def create_user_permissions(apps, schema_editor):
    user_model = apps.get_model('user', 'User')

    for p in permissions:
        create_permission(apps, user_model, p[0], p[1])


def asign_permission_to_group(apps, scheme_editor):
    permission_model = apps.get_model('auth', 'Permission')
    permissions = permission_model.objects.filter(codename='view_help_center')
    group_model = apps.get_model('auth', 'Group')
    premium_admin_group = group_model.objects.get(name='premium_admin')
    premium_member_group = group_model.objects.get(name='premium_member')
    premium_admin_group.permissions.add(*permissions)
    premium_member_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0061_user_policy_review'),
    ]

    operations = [
        migrations.RunPython(create_user_permissions),
        migrations.RunPython(asign_permission_to_group),
    ]
