# Generated by Django 3.1.12 on 2022-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0062_add_help_center_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
