# Generated by Django 3.1.12 on 2022-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0063_user_invitation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_expired',
            field=models.BooleanField(default=False),
        ),
    ]
