# Generated by Django 3.1.12 on 2022-03-31 21:21

from django.db import migrations


def add_can_view_user_permission_to_viewer_role(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')
    group_list = ['premium_viewer', 'premium_member', 'premium_admin', 'premium_super']

    permissions = permission.objects.filter(codename='view_user')

    for group in group.objects.filter(name__in=group_list):
        group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0064_user_password_expired'),
    ]

    operations = [migrations.RunPython(add_can_view_user_permission_to_viewer_role)]
