# Generated by Django 3.2.13 on 2022-05-04 22:18

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0065_add_viewer_role_can_view_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                (
                    'type',
                    models.CharField(choices=[('pentest', 'Pentest')], max_length=128),
                ),
                ('calendar', models.TextField()),
                (
                    'users',
                    models.ManyToManyField(
                        blank=True, related_name='partners', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
