# Generated by Django 3.2.13 on 2022-05-19 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0019_alter_alert_type'),
        ('user', '0066_add_partner_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_alerts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
