# Generated by Django 3.2.13 on 2022-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0067_useralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='typeform',
            field=models.TextField(null=True),
        ),
    ]
