# Generated by Django 3.2.13 on 2022-06-01 20:00

from django.db import migrations
from django.db.models import F, Func, JSONField, Value

from user.constants import ALERT_PREFERENCES


class Migration(migrations.Migration):
    def update_user_preferences(apps, schema_editor):
        user_model = apps.get_model('user', 'User')

        user_model.objects.filter(user_preferences__profile__alerts='Weekly').update(
            user_preferences=Func(
                F("user_preferences"),
                Value(["profile", "alerts"]),
                Value(ALERT_PREFERENCES['DAILY'], JSONField()),
                function="jsonb_set",
            )
        )

    dependencies = [
        ('user', '0068_adding_typeform_field_to_partner'),
    ]

    operations = [
        migrations.RunPython(
            update_user_preferences, reverse_code=migrations.RunPython.noop
        )
    ]
