# Generated by Django 3.2.13 on 2022-06-07 18:52

from django.db import migrations
from django.db.models import F, Func, JSONField, Value

from user.constants import ALERT_PREFERENCES


class Migration(migrations.Migration):
    def update_user_preferences(apps, schema_editor):
        user_model = apps.get_model('user', 'User')

        # we are using all_objects instead of objects to update the soft
        # deleted users
        user_model.all_objects.filter(
            user_preferences__profile__alerts='Weekly'
        ).update(
            user_preferences=Func(
                F("user_preferences"),
                Value(["profile", "alerts"]),
                Value(ALERT_PREFERENCES['DAILY'], JSONField()),
                function="jsonb_set",
            )
        )

    dependencies = [
        ('user', '0069_update_users_preferences_alerts_frequency'),
    ]

    operations = [
        migrations.RunPython(
            update_user_preferences, reverse_code=migrations.RunPython.noop
        )
    ]
