# Generated by Django 3.2.13 on 2022-07-25 16:36

from django.db import migrations, models

from training.utils import has_trainings_assigned_completed


def update_user_assigned_trainings_completed(apps, schema_editor):
    user_model = apps.get_model('user', 'User')
    users = user_model.objects.all().prefetch_related('organization')
    users_to_update = []
    chunk_size = 2000
    for idx, user in enumerate(users.iterator(chunk_size=chunk_size)):
        user.assigned_trainings_completed = has_trainings_assigned_completed(user)
        users_to_update.append(user)
        if idx % chunk_size == 0 and users_to_update:
            user_model.objects.bulk_update(
                users_to_update, ['assigned_trainings_completed']
            )
            users_to_update.clear()
    if users_to_update:
        user_model.objects.bulk_update(
            users_to_update, ['assigned_trainings_completed']
        )


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0071_alter_user_background_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_trainings_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            update_user_assigned_trainings_completed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
