# Generated by Django 3.2.15 on 2022-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0072_add_assigned_trainings_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
