# Generated by Django 3.2.15 on 2022-10-12 23:38

from django.db import migrations

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0074_generate_admin_accounts_for_all_orgs'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserSoftDeleteManager()),
                ('all_objects', user.models.UserCustomManager()),
            ],
        ),
    ]
