# Generated by Django 3.0.3 on 2020-03-26 00:04

import django.db.models.deletion
from django.db import migrations, models

import evidence.models
import laika.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tag', '0001_initial_tag_model'),
        ('organization', '0005_auto_20200304_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                (
                    'filename',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=evidence.models.evidence_upload_directory,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evidence',
                        to='organization.Organization',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='TagEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='evidence.Evidence',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='tags',
            field=models.ManyToManyField(
                related_name='evidence', through='evidence.TagEvidence', to='tag.Tag'
            ),
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'permissions': [('rename_evidence', 'Can rename evidence')]},
        ),
    ]
