# Generated by Django 3.0.3 on 2020-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='filename',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.CharField(max_length=512, blank=True),
        ),
    ]
