# Generated by Django 3.0.3 on 2020-05-19 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0004_auto_20200421_1655'),
        ('evidence', '0002_rename_evidence_file_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='legacy_document',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='other_evidence',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='evidence',
            name='policy',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='evidence',
                to='policy.Policy',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('POLICY', 'Policy'),
                    ('LEGACY_DOCUMENT', 'Legacy Document'),
                    ('FILE', 'File'),
                    ('OTHER', 'Other Evidence'),
                    ('TEAM', 'Team'),
                    ('OFFICER', 'Officer'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
