# Generated by Django 3.0.3 on 2020-06-22 17:03

from django.db import migrations

from evidence.models import Evidence


def add_rename_evidence_permission(apps, groups):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    obj_content_type = ContentType.objects.get_for_model(Evidence)
    content_type = ContentType.objects.get(
        app_label=obj_content_type.app_label, model=obj_content_type.model
    )
    Permission.objects.get_or_create(
        codename='rename_evidence',
        name='Can rename evidence',
        content_type=content_type,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0003_add_additional_evidence_fields'),
    ]

    operations = [migrations.RunPython(add_rename_evidence_permission)]
