# Generated by Django 3.0.7 on 2020-07-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0005_change_published_date_to_datetime'),
        ('evidence', '0005_migrate_other_evidence_to_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={
                'permissions': [('rename_evidence', 'Can rename evidence')],
                'verbose_name_plural': 'evidence',
            },
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='other_evidence',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='policy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='evidence',
                to='policy.Policy',
            ),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('POLICY', 'Policy'),
                    ('LEGACY_DOCUMENT', 'Legacy Document'),
                    ('FILE', 'File'),
                    ('TEAM', 'Team'),
                    ('OFFICER', 'Officer'),
                ],
                max_length=20,
            ),
        ),
    ]
