# Generated by Django 3.0.7 on 2020-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0008_add_system_tag_evidence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['name'], name='evidence_ev_name_681fb6_idx'),
        ),
    ]
