# Generated by Django 3.0.7 on 2020-10-07 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import evidence.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0008_organization_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0009_index_evidence_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncExportRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'link',
                    models.FileField(
                        blank=True,
                        max_length=2024,
                        null=True,
                        storage=laika.storage.PrivateMediaStorage(),
                        upload_to=evidence.models.async_export_upload_directory,
                    ),
                ),
                ('delivered', models.BooleanField(default=False)),
                ('errors', models.TextField(blank=True)),
                (
                    'export_type',
                    models.CharField(
                        choices=[('DATAROOM', 'Dataroom'), ('DRIVE', 'Drive')],
                        max_length=20,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='export_requests',
                        to='organization.Organization',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='user_export_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AsyncExportEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='export_request',
                        to='evidence.Evidence',
                    ),
                ),
                (
                    'export_request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evidence',
                        to='evidence.AsyncExportRequest',
                    ),
                ),
            ],
        ),
    ]
