# Generated by Django 3.0.7 on 2020-10-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0010_create_async_export_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncexportrequest',
            name='evidence',
            field=models.ManyToManyField(
                related_name='export_requests',
                through='evidence.AsyncExportEvidence',
                to='evidence.Evidence',
            ),
        ),
        migrations.AddField(
            model_name='asyncexportrequest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asyncexportevidence',
            name='evidence',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='evidence.Evidence'
            ),
        ),
        migrations.AlterField(
            model_name='asyncexportevidence',
            name='export_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='export_evidence',
                to='evidence.AsyncExportRequest',
            ),
        ),
    ]
