# Generated by Django 3.0.7 on 2020-10-26 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0002_DateTimeField_instead_of_DateField'),
        ('evidence', '0011_update_to_export_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTagLegacyEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='evidence.Evidence',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'legacy tags',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='system_tags_legacy',
            field=models.ManyToManyField(
                related_name='system_legacy_tag',
                through='evidence.SystemTagLegacyEvidence',
                to='tag.Tag',
            ),
        ),
    ]
