# Generated by Django 3.0.7 on 2020-11-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0012_system_tags_legacy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidence',
            name='evidence_ev_name_681fb6_idx',
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(
                fields=['name', 'evidence_text'], name='evidence_ev_name_1169b5_idx'
            ),
        ),
    ]
