# Generated by Django 3.0.7 on 2020-11-04 21:33

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0013_add_new_column_for_search'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidence',
            name='evidence_ev_name_1169b5_idx',
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['name'], name='evidence_ev_name_681fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['evidence_text'], name='evidence_ev_evidenc_01eede_hash'
            ),
        ),
    ]
