# Generated by Django 3.0.7 on 2020-11-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0014_updating_evidence_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
