# Generated by Django 3.1.2 on 2020-11-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0016_fill_evidence_text_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='legacy_evidence',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='evidence.evidence',
            ),
        ),
    ]
