# Generated by Django 3.1.2 on 2020-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0017_legacy_evidence_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncexportrequest',
            name='export_type',
            field=models.CharField(
                choices=[('DATAROOM', 'Dataroom'), ('DOCUMENTS', 'Documents')],
                max_length=20,
            ),
        ),
    ]
