# Generated by Django 3.1.2 on 2020-11-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0018_updating_async_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='legacy_evidence',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='migrated_evidence',
                to='evidence.evidence',
            ),
        ),
    ]
