# Generated by Django 3.1.2 on 2021-02-19 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0019_name_to_migrated_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtagevidence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
