# Generated by Django 3.1.2 on 2021-02-25 20:15

from django.db import connection, migrations, models


def migrate_duplicated_tag_evidences(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            '''DELETE FROM evidence_tagevidence duplicate
            USING evidence_tagevidence source WHERE duplicate.id > source.id
            AND duplicate.evidence_id = source.evidence_id
            AND duplicate.tag_id=source.tag_id'''
        )


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0020_add_created_at_field'),
    ]

    operations = [
        migrations.RunPython(migrate_duplicated_tag_evidences),
        migrations.AddConstraint(
            model_name='asyncexportrequest',
            constraint=models.CheckConstraint(
                check=models.Q(export_type__in=['DATAROOM', 'DOCUMENTS']),
                name='evidence_asyncexportrequest_valid_export_type',
            ),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(
                check=models.Q(
                    type__in=[
                        'POLICY',
                        'LEGACY_DOCUMENT',
                        'FILE',
                        'TEAM',
                        'OFFICER',
                        'LINK',
                        'LAIKA_PAPER',
                    ]
                ),
                name='evidence_evidence_valid_evidence_type',
            ),
        ),
        migrations.AddConstraint(
            model_name='tagevidence',
            constraint=models.UniqueConstraint(
                fields=('tag', 'evidence'), name='unique_tag_evidence'
            ),
        ),
    ]
