# Generated by Django 3.1.2 on 2021-03-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0023_create_ignore_word_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoreword',
            name='language',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ignore_words',
                to='evidence.language',
            ),
        ),
        migrations.AlterField(
            model_name='ignoreword',
            name='word',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='language',
            name='evidence',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='languages',
                to='evidence.evidence',
            ),
        ),
    ]
