# Generated by Django 3.1.6 on 2021-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0024_update_language_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncexportrequest',
            name='time_zone',
            field=models.CharField(default='US/Eastern', max_length=50),
        ),
    ]
