# Generated by Django 3.1.6 on 2021-07-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('link', '0003_expiration_date_to_date_time_field'),
        ('evidence', '0025_add_time_zone_to_async_export_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncexportrequest',
            name='link_model',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='async_export_request',
                to='link.link',
            ),
        ),
    ]
