# Generated by Django 3.1.12 on 2021-12-01 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0063_seed_offboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('idp_id', models.CharField(max_length=20)),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('AZURE', 'Azure AD'),
                            ('GOOGLE', 'Google'),
                            ('OKTA', 'Okta'),
                        ],
                        default='Okta',
                        max_length=10,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='identity_provider',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='IdentityProviderDomain',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('domain', models.TextField()),
                (
                    'idp',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domains',
                        to='sso.identityprovider',
                    ),
                ),
            ],
        ),
    ]
