# Generated by Django 3.1.12 on 2021-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='name',
            field=models.CharField(default='SAML integration', max_length=40),
        ),
    ]
