# Generated by Django 3.1.12 on 2022-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0002_identityprovider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityproviderdomain',
            name='domain',
            field=models.TextField(unique=True),
        ),
    ]
