# Generated by Django 3.1.12 on 2022-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0003_set_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='rule_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
