# Generated by Django 3.1.12 on 2022-03-07 14:30

from django.db import migrations


def add_client_configs(apps, schema_editor):
    AZURE_AD = 'Azure AD'

    IdentityProvider = apps.get_model('sso', 'IdentityProvider')
    IdentityProviderDomain = apps.get_model('sso', 'IdentityProviderDomain')
    Organization = apps.get_model('organization', 'Organization')

    providers = [
        {
            'org_name': 'Omada',
            'domains': ['omada.net', 'omada.dk', 'omadaidentity.com'],
            'idp_id': '0oa19ws391hXOCsLf5d7',
            'organization_id': '235efd52-7adb-457f-a40b-9b4c09232f6c',
            'provider': AZURE_AD,
        },
        {
            'org_name': 'Vinli',
            'domains': ['vin.li'],
            'idp_id': '0oa1t1tlyf1hS3CS55d7',
            'organization_id': 'd70ba4c0-904d-472c-84c8-200815ce6190',
            'provider': 'Okta',
        },
        {
            'org_name': 'Telnyx',
            'domains': ['telnyx.com'],
            'idp_id': '0oa1t3iculmkHDKa75d7',
            'organization_id': '56290371-192b-4ee0-ab47-cfefcfe0bdaf',
            'provider': 'Okta',
        },
        {
            'org_name': 'Praetorian',
            'domains': ['praetorian.com'],
            'idp_id': '0oa27zbs4zt7Jf9vk5d7',
            'organization_id': '63096f99-986c-4c70-b772-e5ca920bd7d7',
            'provider': 'Okta',
        },
        {
            'org_name': 'Orum',
            'domains': ['orum.io'],
            'idp_id': '0oa29aupgtov583Y25d7',
            'organization_id': '3268aecc-a36c-4ee4-a244-53b0a3c72f27',
            'provider': 'Okta',
        },
        {
            'org_name': 'Flatfile',
            'domains': [],
            'idp_id': '0oa2dnhh8nGCZcayV5d7',
            'organization_id': 'df4115ed-0182-4c8f-8778-fd0bfe4871d2',
            'provider': 'Okta',
        },
        {
            'org_name': 'Zageno',
            'domains': ['zageno.com'],
            'idp_id': '0oa2fvd89pwcNSFaC5d7',
            'organization_id': '155a0525-167e-4983-88f5-a18b52f213d5',
            'provider': 'Okta',
        },
        {
            'org_name': 'Ionic',
            'domains': ['ionic.io'],
            'idp_id': '0oa2iewomcdgE0xFt5d7',
            'organization_id': 'b5d43e0a-01e7-4b94-9f63-4952e64bf676',
            'provider': 'Google',
        },
        {
            'org_name': 'Codat',
            'domains': [],
            'idp_id': '0oa2ka10giRd0g4a35d7',
            'organization_id': '813580f5-5edc-4cfb-bac3-5c0ef0cec7e0',
            'provider': AZURE_AD,
        },
        {
            'org_name': 'PlusPlus',
            'domains': ['plusplus.co'],
            'idp_id': '0oa3g13ny01W499Yg5d7',
            'organization_id': 'bbe02c25-c706-4424-8a74-a7c1d2a1f5a5',
            'provider': 'Google',
        },
        {
            'org_name': 'Passthrough',
            'domains': ['passthrough.com'],
            'idp_id': '0oa3g1447qgUDFlyo5d7',
            'organization_id': 'e6d5c9d8-58ca-4ba5-bb11-0bdf7829c5c0',
            'provider': 'Google',
        },
        {
            'org_name': 'Jane Technologies',
            'domains': ['iheartjane.com'],
            'idp_id': '0oa3pwp5bgdQqsfEb5d7',
            'organization_id': '3775d7d8-ef0b-4572-a8d5-3d756a7cd774',
            'provider': 'Google',
        },
        {
            'org_name': 'Tradeteq',
            'domains': ['tradeteq.com'],
            'idp_id': '0oa3sclcjnQ6085XP5d7',
            'organization_id': '9bd8452c-0973-4c3c-909d-ff6d3718f3d4',
            'provider': AZURE_AD,
        },
        {
            'org_name': 'Homee',
            'domains': ['homeeondemand.com', 'homee.com'],
            'idp_id': '0oa3t17hbai4VaTSZ5d7',
            'organization_id': '3ab18df4-a24e-4b87-a58f-e4571c3f1acd',
            'provider': 'Okta',
        },
        {
            'org_name': 'Itopia',
            'domains': ['itopia.com'],
            'idp_id': '0oa3t1k9zvDK8N5se5d7',
            'organization_id': '2978e5d5-6242-42be-bae8-b0bdfc45e75d',
            'provider': 'Google',
        },
        {
            'org_name': 'HeyDoc',
            'domains': ['heydoc.co.uk'],
            'idp_id': '0oa3xwl1507V3FISh5d7',
            'organization_id': 'ef64d733-6e02-4efc-b989-75034ebfa17a',
            'provider': 'Okta',
        },
        {
            'org_name': 'Applied Value Tech',
            'domains': [],
            'idp_id': '0oa40clig6bUI4S2L5d7',
            'organization_id': 'ef64d733-6e02-4efc-b989-75034ebfa17a',
            'provider': AZURE_AD,
        },
    ]

    for provider in providers:
        organization = Organization.objects.filter(
            id=provider['organization_id']
        ).first()
        if organization is not None:
            idp = IdentityProvider.objects.create(
                organization=organization,
                idp_id=provider['idp_id'],
                provider=provider['provider'],
                name=f'{organization.name} {provider["provider"]}',
            )
            for domain in provider['domains']:
                IdentityProviderDomain.objects.create(domain=domain, idp=idp)


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0004_add_rule_id'),
    ]

    operations = [migrations.RunPython(add_client_configs)]
