# Generated by Django 3.1.12 on 2022-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0005_add_current_sso_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='state',
            field=models.CharField(default='PENDING_IDP_DATA', max_length=20),
        ),
    ]
