# Generated by Django 3.2.13 on 2022-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0008_current_clients_update_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='name',
            field=models.CharField(default='SAML integration', max_length=255),
        ),
    ]
