# Generated by Django 3.1.12 on 2021-09-24 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_required', models.BooleanField(blank=True, default=False)),
                ('is_recurrent', models.BooleanField(blank=True, default=False)),
                ('recurrent_schedule', models.CharField(blank=True, max_length=999)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('new', 'New'),
                            ('pending', 'Pending'),
                            ('completed', 'Completed'),
                        ],
                        default='new',
                        max_length=15,
                    ),
                ),
                (
                    'parent_action_item',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='steps',
                        to='action_item.actionitem',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserActionItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignees',
                        to='action_item.actionitem',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='action_items',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
