# Generated by Django 3.1.12 on 2021-10-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='parent_action_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='steps',
                to='action_item.actionitem',
            ),
        ),
    ]
