# Generated by Django 3.1.12 on 2021-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0002_adding_metadata_action_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('pending', 'Pending'),
                    ('completed', 'Completed'),
                    ('not_applicable', 'Not Applicable'),
                ],
                default='new',
                max_length=15,
            ),
        ),
    ]
