# Generated by Django 3.1.12 on 2021-10-15 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action_item', '0003_add_not_applicable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assignees',
            field=models.ManyToManyField(
                related_name='action_items', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name='UserActionItem',
        ),
    ]
