# Generated by Django 3.1.12 on 2021-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0014_alert_types_cleanup'),
        ('action_item', '0005_actionitem_evidences'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='alerts',
            field=models.ManyToManyField(related_name='action_items', to='alert.Alert'),
        ),
    ]
