# Generated by Django 3.1.12 on 2021-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0006_actionitem_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='recurrent_schedule',
            field=models.CharField(
                blank=True,
                choices=[
                    ('weekly', 'Weekly'),
                    ('monthly', 'Monthly'),
                    ('quarterly', 'Quarterly'),
                    ('semi_annually', 'Semi annually'),
                    ('annually', 'Annually'),
                    ('bi_annually', 'Bi annually'),
                ],
                default='weekly',
                max_length=999,
            ),
        ),
    ]
