# Generated by Django 3.1.12 on 2022-01-31 16:39

from django.db import migrations

from action_item.constants import TYPE_CONTROL


def update_recurrent_ai_to_not_required(apps, schema_editor):
    action_item = apps.get_model('action_item', 'ActionItem')
    for action_item in action_item.objects.filter(
        is_recurrent=True, metadata__type__iexact=TYPE_CONTROL
    ):
        action_item.is_required = False
        action_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0007_add_recurrent_schedule_choices'),
    ]

    operations = [migrations.RunPython(update_recurrent_ai_to_not_required)]
