# Generated by Django 3.2.13 on 2022-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0008_update_recurrent_ai_to_be_not_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemTags',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('item_text', models.TextField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
