# Generated by Django 3.2.15 on 2022-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0009_create_action_item_tag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='recurrent_schedule',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'One time only'),
                    ('weekly', 'Weekly'),
                    ('monthly', 'Monthly'),
                    ('quarterly', 'Quarterly'),
                    ('semi_annually', 'Semi annually'),
                    ('annually', 'Annually'),
                    ('bi_annually', 'Bi annually'),
                ],
                default='',
                max_length=999,
            ),
        ),
    ]
