# Generated by Django 3.2.15 on 2022-08-11 16:23

from django.db import migrations


def update_not_recurrent_ai_to_have_empty_recurrent_schedule(apps, schema_editor):
    action_item = apps.get_model('action_item', 'ActionItem')

    not_recurrent_and_with_recurrent_schedule_action_items = action_item.objects.filter(
        is_recurrent=False
    ).exclude(recurrent_schedule='')

    for ai in not_recurrent_and_with_recurrent_schedule_action_items:
        ai.recurrent_schedule = ''

    action_item.objects.bulk_update(
        not_recurrent_and_with_recurrent_schedule_action_items, ['recurrent_schedule']
    )


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0010_alter_actionitem_recurrent_schedule'),
    ]

    operations = [
        migrations.RunPython(
            update_not_recurrent_ai_to_have_empty_recurrent_schedule,
            migrations.RunPython.noop,
        )
    ]
