# Generated by Django 3.2.15 on 2022-09-29 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0003_tag_is_manual'),
        (
            'action_item',
            '0011_update_action_items_to_be_not_recurrent_when_recurrent_schedule_is_empty',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemAssociatedTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='action_item_tags',
                        to='action_item.actionitem',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tag.tag'
                    ),
                ),
            ],
        ),
    ]
