# Generated by Django 3.2.15 on 2022-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0003_tag_is_manual'),
        ('action_item', '0012_actionitemassociatedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='tags',
            field=models.ManyToManyField(
                related_name='tags',
                through='action_item.ActionItemAssociatedTag',
                to='tag.Tag',
            ),
        ),
    ]
