# Generated by Django 3.2.15 on 2022-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0013_actionitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
