# Generated by Django 3.2.15 on 2022-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0015_migrate_action_item_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='display_id',
            field=models.IntegerField(default=9999999),
        ),
    ]
