# Generated by Django 3.2.15 on 2022-12-14 14:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0016_actionitem_display_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actionitem',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['metadata'], name='action_item_metadat_8b7d64_gin'
            ),
        ),
    ]
