# Generated by Django 3.1.2 on 2021-01-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0001_adding_alert_models'),
        ('comment', '0001_add_comments_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comment_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alerts',
                        to='comment.comment',
                    ),
                ),
            ],
        ),
    ]
