# Generated by Django 3.1.2 on 2021-01-11 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_adding_alert_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='resolved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comment_resolver',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
