# Generated by Django 3.1.2 on 2021-01-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0003_adding_resolved_fields_to_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
