# Generated by Django 3.1.2 on 2021-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0004_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.CharField(
                blank=True,
                choices=[('RESOLVED', 'RESOLVED'), ('UNRESOLVED', 'UNRESOLVED')],
                default='UNRESOLVED',
                max_length=25,
            ),
        ),
    ]
