# Generated by Django 3.1.2 on 2021-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0005_comment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
