# Generated by Django 3.1.2 on 2021-01-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alert', '0003_add_alert_permissions_to_group'),
        ('comment', '0006_adding_delete_field_to_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyAlert',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reply_alert',
                        to='alert.alert',
                    ),
                ),
                (
                    'reply',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alerts',
                        to='comment.reply',
                    ),
                ),
            ],
        ),
    ]
