# Generated by Django 3.1.12 on 2022-03-23 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            BEGIN;
            INSERT into
               public.auth_group_permissions (group_id, permission_id) (
               SELECT
                  g.id AS group_id, p.id AS permission_id 
               FROM
                  public.auth_group g 
                  cross join
                     public.auth_permission p 
               WHERE
                  (
                     g.name ilike 'auditor%' 
                  )
                  AND p.codename = ANY (array [
                    'add_comment',
                    'delete_comment',
                    'change_comment',
                    'view_comment',
                    'add_reply',
                    'delete_reply',
                    'change_reply',
                    'view_reply']
                    )
                )
            ON CONFLICT DO NOTHING;
            COMMIT;
        '''
        )
    ]
