# Generated by Django 3.2.13 on 2022-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0009_comment_permissions_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='action_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
