# Integrations
import os

from botocore.config import Config

from laika.settings import DJANGO_SETTINGS

ENVIRONMENT = os.getenv("ENVIRONMENT")

# INTEGRATIONS

INTEGRATIONS_ENCRYPTION_KEY = DJANGO_SETTINGS.get('INTEGRATIONS_ENCRYPTION_KEY')

# S3 TEMPLATE
LAIKA_PUBLIC_TEMPLATES_BUCKET = DJANGO_SETTINGS.get('LAIKA_PUBLIC_TEMPLATES_BUCKET')

# Google Workspace
GOOGLE_WORKSPACE_DIRECTORY_API_URL = 'https://www.googleapis.com/admin/directory/v1'
GOOGLE_WORKSPACE_OAUTH_URL = 'https://oauth2.googleapis.com/token'
GOOGLE_WORKSPACE_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_GOOGLE_CLIENT_ID')
GOOGLE_WORKSPACE_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_GOOGLE_CLIENT_SECRET')

# Atlassian
ATLASSIAN_OAUTH_URL = 'https://auth.atlassian.com/oauth/token'
ATLASSIAN_API_URL = 'https://api.atlassian.com'
ATLASSIAN_ACCOUNT_CLAIM = 'https://atlassian.com/systemAccountId'
ATLASSIAN_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_ATLASSIAN_CLIENT_ID')
ATLASSIAN_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_ATLASSIAN_CLIENT_SECRET')

# Github
GITHUB_OAUTH_URL = 'https://github.com/login/oauth/access_token'
GITHUB_REST_API_URL = 'https://api.github.com'
GITHUB_API_URL = 'https://api.github.com/graphql'
GITHUB_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_GITHUB_CLIENT_ID')
GITHUB_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_GITHUB_CLIENT_SECRET')
GITHUB_APPS_URL = 'https://api.github.com'
GITHUB_APP_ID = DJANGO_SETTINGS.get('INTEGRATION_GITHUB_APP_ID')
GITHUB_APP_PEM = DJANGO_SETTINGS.get('INTEGRATION_GITHUB_APP_PEM')
GITHUB_APP_BUCKET = DJANGO_SETTINGS.get('INTEGRATION_GITHUB_APP_BUCKET')

# Gitlab
GITLAB_BASE_URL = 'https://gitlab.com'
GITLAB_API_URL = 'https://gitlab.com/api/graphql'
GITLAB_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_GITLAB_CLIENT_ID')
GITLAB_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_GITLAB_CLIENT_SECRET')

# Datadog
DATADOG_US_API_URL = 'https://api.datadoghq.com/api'
DATADOG_EU_API_URL = 'https://api.datadoghq.eu/api'
DATADOG_US3_API_URL = 'https://api.us3.datadoghq.com/api'
DATADOG_US1_FED_API_URL = 'https://api.ddog-gov.com/api'
DATADOG_SITES = [
    DATADOG_US_API_URL,
    DATADOG_EU_API_URL,
    DATADOG_US3_API_URL,
    DATADOG_US1_FED_API_URL,
]

# Bitbucket
BITBUCKET_OAUTH_ENDPOINT = 'https://bitbucket.org/site/oauth2'
BITBUCKET_API_ENDPOINT = 'https://api.bitbucket.org'
BITBUCKET_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_BITBUCKET_CLIENT_ID')
BITBUCKET_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_BITBUCKET_CLIENT_SECRET')

# Asana
ASANA_OAUTH_URL = 'https://app.asana.com/-/oauth_token'
ASANA_API_ENDPOINT = 'https://app.asana.com/api/1.0'
ASANA_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_ASANA_CLIENT_ID')
ASANA_CLIENT_SECRET_ID = DJANGO_SETTINGS.get('INTEGRATION_ASANA_CLIENT_SECRET')

# Finch
FINCH_API_URL = 'https://api.tryfinch.com'
FINCH_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_FINCH_CLIENT_ID')
FINCH_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_FINCH_CLIENT_SECRET')

# Shortcut
SHORTCUT_API_URL = 'https://api.app.shortcut.com'

# JAMF
JAMF_API_URL = 'jamfcloud.com/api'

# Microsoft
MICROSOFT_OAUTH_URL = (
    'https://login.microsoftonline.com/organizations/oauth2/v2.0/token'
)
MICROSOFT_API_URL = 'https://graph.microsoft.com/v1.0'
MICROSOFT_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_MICROSOFT_CLIENT_ID')
MICROSOFT_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_MICROSOFT_CLIENT_SECRET')

# Azure DevOps
AZURE_DEVOPS_VSSPS_BASE_URL = 'https://app.vssps.visualstudio.com'
AZURE_DEVOPS_SECRET_ID = DJANGO_SETTINGS.get('INTEGRATION_AZURE_DEVOPS_SECRET')
AZURE_BOARDS_SECRET_ID = DJANGO_SETTINGS.get('INTEGRATION_AZURE_BOARDS_SECRET')

# Microsoft Intune
MICROSOFT_INTUNE_CLIENT_ID = DJANGO_SETTINGS.get(
    'INTEGRATION_MICROSOFT_INTUNE_CLIENT_ID'
)
MICROSOFT_INTUNE_CLIENT_SECRET = DJANGO_SETTINGS.get(
    'INTEGRATION_MICROSOFT_INTUNE_CLIENT_SECRET'
)

# AWS
AWS_ROLE_NAME = DJANGO_SETTINGS.get('INTEGRATION_AWS_CROSS_ACCOUNT_ROLE')
AWS_EXTERNAL_ID = DJANGO_SETTINGS.get('LAIKA_INTEGRATIONS_AWS_STS_ROLE_EXTERNAL_ID')
AWS_CONFIG = Config(retries={'max_attempts': 10, 'mode': 'standard'})

# Rippling
RIPPLING_OAUTH_URL = DJANGO_SETTINGS.get('INTEGRATION_RIPPLING_OAUTH_URL')
RIPPLING_API_URL = DJANGO_SETTINGS.get('INTEGRATION_RIPPLING_API_URL')
RIPPLING_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_RIPPLING_CLIENT_ID')
RIPPLING_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_RIPPLING_CLIENT_SECRET')
RIPPLING_DEVICE_WAIT = DJANGO_SETTINGS.get('INTEGRATION_RIPPLING_DEVICE_WAIT', 2)

# Linear
LINEAR_OAUTH_URL = 'https://api.linear.app/oauth/token'
LINEAR_API_URL = 'https://api.linear.app/graphql'
LINEAR_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_LINEAR_CLIENT_ID')
LINEAR_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_LINEAR_CLIENT_SECRET')

# Slack
SLACK_API_URL = 'https://slack.com/api'
SLACK_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_SLACK_CLIENT_ID')
SLACK_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_SLACK_CLIENT_SECRET')

# Checkr
CHECKR_API_URL = DJANGO_SETTINGS.get('INTEGRATION_CHECKR_API_URL')
CHECKR_CLIENT_ID = DJANGO_SETTINGS.get('INTEGRATION_CHECKR_CLIENT_ID')
CHECKR_CLIENT_SECRET = DJANGO_SETTINGS.get('INTEGRATION_CHECKR_CLIENT_SECRET')

# Heroku
HEROKU_API_URL = 'https://api.heroku.com'

# Jumpcloud
JUMPCLOUD_API_URL = 'https://console.jumpcloud.com/api'

# DigitalOcean
DIGITALOCEAN_API_URL = 'https://api.digitalocean.com/v2'

# Store requests and responses on test mode
INTEGRATIONS_TROUBLESHOOTING_BUCKET = DJANGO_SETTINGS.get(
    'INTEGRATIONS-TROUBLESHOOTING-BUCKET'
)
