# Generated by Django 3.0.3 on 2020-04-13 17:24

from django.contrib.auth.management import create_permissions
from django.db import migrations

# This is to make sure the permissions are created for the next migration
# that adds them to the groups


def create_perms(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={
                'permissions': [
                    ('batch_delete_control', 'Can batch delete controls'),
                    ('change_control_status', 'Can change control status'),
                    ('associate_user', 'Can associate user to control'),
                ]
            },
        ),
        migrations.RunPython(create_perms),
    ]
