# Generated by Django 3.0.3 on 2020-04-13 17:25

from django.db import migrations


def add_control_permissions_to_groups(apps, groups):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    groups = Group.objects.all()
    control_permissions = Permission.objects.filter(
        codename__in=[
            'view_control',
            'delete_control',
            'change_control',
            'add_control',
            'batch_delete_control',
            'change_control_status',
            'associate_user',
        ]
    )

    view_permission = [p for p in control_permissions if p.codename == 'view_control'][
        0
    ]
    for g in groups:
        g.permissions.add(view_permission)

        if (
            'super' in g.name
            or g.name == 'starter_admin'
            or g.name == 'premium_admin'
            or g.name == 'starter_member'
            or g.name == 'premium_member'
        ):
            allowd_permissions = [
                'add_control',
                'delete_control',
                'change_control',
                'change_control_status',
            ]
            permissions = [
                p for p in control_permissions if p.codename in allowd_permissions
            ]
            g.permissions.add(*permissions)

        if 'super' in g.name or g.name == 'starter_admin' or g.name == 'premium_admin':
            allowd_permissions = ['batch_delete_control', 'associate_user']
            permissions = [
                p for p in control_permissions if p.codename in allowd_permissions
            ]
            g.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0002_add_control_additional_permissions'),
    ]

    operations = [migrations.RunPython(add_control_permissions_to_groups)]
