# Generated by Django 3.0.3 on 2020-04-14 21:24

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0003_add_control_permissions_to_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='control',
            name='id',
        ),
        migrations.AddField(
            model_name='control',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='control',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
