# Generated by Django 3.0.3 on 2020-04-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0003_policy_tags_relation'),
        ('control', '0003_import_dynamo_to_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPolicy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'control',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='control_policies',
                        to='control.Control',
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='policy.Policy'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='policies',
            field=models.ManyToManyField(
                related_name='controls',
                through='control.ControlPolicy',
                to='policy.Policy',
            ),
        ),
    ]
