# Generated by Django 3.0.3 on 2020-04-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0002_add_control_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
