# Generated by Django 3.0.3 on 2020-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0005_updating_control_user_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
