# Generated by Django 3.0.7 on 2020-07-10 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0008_add_certifications_to_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='certification_sections',
        ),
        migrations.DeleteModel(
            name='ControlCertificationSection',
        ),
    ]
