# Generated by Django 3.0.7 on 2020-07-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0009_remove_certification_fks'),
        ('certification', '0004_update_certification_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCertificationSection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'certification_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='certification.CertificationSection',
                    ),
                ),
                (
                    'control',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='control.Control',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'certification sections',
            },
        ),
        migrations.AddField(
            model_name='control',
            name='certification_sections',
            field=models.ManyToManyField(
                related_name='controls',
                through='control.ControlCertificationSection',
                to='certification.CertificationSection',
            ),
        ),
    ]
