# Generated by Django 3.0.7 on 2020-08-04 20:42

import django.db.models.deletion
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def create_perms(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0006_remove_other_evidence_column'),
        ('control', '0011_update_control_certification_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={
                'permissions': [
                    ('batch_delete_control', 'Can batch delete controls'),
                    ('change_control_status', 'Can change control status'),
                    ('associate_user', 'Can associate user to control'),
                    ('add_control_evidence', 'Can add control evidence'),
                    ('delete_control_evidence', 'Can delete control evidence'),
                ]
            },
        ),
        migrations.CreateModel(
            name='ControlEvidence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'control',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='control.Control',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='evidence.Evidence',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='evidence',
            field=models.ManyToManyField(
                related_name='controls',
                through='control.ControlEvidence',
                to='evidence.Evidence',
            ),
        ),
        migrations.RunPython(create_perms),
    ]
