# Generated by Django 3.1.6 on 2021-07-08 20:52

import django.db.models.deletion
from django.db import migrations, models

import control.models
import laika.storage


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0012_adding_control_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPillar',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                (
                    'illustration',
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        storage=laika.storage.PublicMediaStorage(),
                        upload_to=control.models.pillar_illustration_directory_path,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='pillar',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='control',
                to='control.controlpillar',
            ),
        ),
    ]
