# Generated by Django 3.1.6 on 2021-07-08 21:00

from django.db import migrations


def add_control_pillars(apps, schema_editor):
    ControlPillar = apps.get_model('control', 'ControlPillar')

    pillars = [
        'Security & Privacy Governance',
        'HR Governance',
        'Asset Management',
        'Risk Management',
        'Third Party Management',
        'System Network and Cloud Security',
        'Continuous Monitoring',
        'Endpoint Security',
        'Vulnerability and Threat Management',
        'Physical and Environment Management',
        'Cryptographic',
        'Data Handling',
        'Identification and Authentication',
        'Privacy Operations',
        'Business Continuity and Disaster Recovery',
        'Capacity and Performance Planning',
        'Incident Response',
        'Change and Configuration Management',
    ]

    for p in pillars:
        ControlPillar.objects.get_or_create(name=p)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0013_new_control_pillar_model'),
    ]

    operations = [
        migrations.RunPython(add_control_pillars),
    ]
