# Generated by Django 3.1.12 on 2021-07-22 18:48

from django.db import migrations
from django.db.models import Q


def draft_and_published_to_not_implemented(apps, schema_editor):
    Control = apps.get_model('control', 'Control')
    Control.objects.filter(Q(status='DRAFT') | Q(status='PUBLISHED')).update(
        status='NOT IMPLEMENTED'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0015_add_implementation_guide_model'),
    ]

    operations = [migrations.RunPython(draft_and_published_to_not_implemented)]
