# Generated by Django 3.1.12 on 2021-07-27 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0016_draft_and_published_to_not_implemented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='owner',
            new_name='owner1',
        ),
        migrations.AddField(
            model_name='control',
            name='owner2',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='control_owner1',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='owner3',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='control_owner2',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
