# Generated by Django 3.1.12 on 2021-07-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0017_add_new_owner_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpillar',
            name='name',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Security & Privacy Governance', 'Security & Privacy Governance'),
                    ('HR Governance', 'HR Governance'),
                    ('Asset Management', 'Asset Management'),
                    ('Risk Management', 'Risk Management'),
                    ('Third Party Management', 'Third Party Management'),
                    (
                        'System Network and Cloud Security',
                        'System Network and Cloud Security',
                    ),
                    ('Continuous Monitoring', 'Continuous Monitoring'),
                    ('Endpoint Security', 'Endpoint Security'),
                    (
                        'Vulnerability and Threat Management',
                        'Vulnerability and Threat Management',
                    ),
                    (
                        'Physical and Environment Management',
                        'Physical and Environment Management',
                    ),
                    ('Cryptographic', 'Cryptographic'),
                    ('Data Handling', 'Data Handling'),
                    (
                        'Identification and Authentication',
                        'Identification and Authentication',
                    ),
                    ('Privacy Operations', 'Privacy Operations'),
                    (
                        'Business Continuity and Disaster Recovery',
                        'Business Continuity and Disaster Recovery',
                    ),
                    (
                        'Capacity and Performance Planning',
                        'Capacity and Performance Planning',
                    ),
                    ('Incident Response', 'Incident Response'),
                    (
                        'Change and Configuration Management',
                        'Change and Configuration Management',
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
