# Generated by Django 3.1.12 on 2021-07-23 20:49

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def map_control_categories_to_pillar_names(apps, schema_editor):
    control = apps.get_model('control', 'Control')
    pillar = apps.get_model('control', 'ControlPillar')

    # These constants are created due to sonarcube showing issues for repeated strings
    ASSET_MANAGEMENT = 'Asset Management'
    RISK_MANAGEMENT = 'Risk Management'
    SECURITY_AND_PRIVACY_GOVERNANCE = 'Security & Privacy Governance'
    SYSTEM_NETWORK_AND_CLOUD_SECURITY = 'System Network and Cloud Security'

    category_to_pillar = {
        'Security & Privacy Governance': SECURITY_AND_PRIVACY_GOVERNANCE,
        'Human Resources Security': 'HR Governance',
        'Asset Management': ASSET_MANAGEMENT,
        'Risk Management': RISK_MANAGEMENT,
        'Third-Party Management': 'Third Party Management',
        'Cloud Security': SYSTEM_NETWORK_AND_CLOUD_SECURITY,
        'Monitoring': 'Continuous Monitoring',
        'Endpoint Security': 'Endpoint Security',
        'Vulnerability & Patch Management': 'Vulnerability and Threat Management',
        'Threat Management': 'Vulnerability and Threat Management',
        'Physical & Environmental Security': 'Physical and Environment Management',
        'Cryptographic Protections': 'Cryptographic',
        'Data Classification & Handling': 'Data Handling',
        'Identification & Authentication': 'Identification and Authentication',
        'Privacy': 'Privacy Operations',
        'Business Continuity & Disaster Recovery': (
            'Business Continuity and Disaster Recovery'
        ),
        'Capacity & Performance Planning': 'Capacity and Performance Planning',
        'Incident Response': 'Incident Response',
        'Change Management': 'Change and Configuration Management',
        'Configuration Management': 'Change and Configuration Management',
        'Embedded Technology': 'Continuous Monitoring',
        'Information Assurance': RISK_MANAGEMENT,
        'Maintenance': ASSET_MANAGEMENT,
        'Mobile Device Management': ASSET_MANAGEMENT,
        'Network Security': SYSTEM_NETWORK_AND_CLOUD_SECURITY,
        'Project & Resource Management': SECURITY_AND_PRIVACY_GOVERNANCE,
        'Secure Engineering & Architecture': SYSTEM_NETWORK_AND_CLOUD_SECURITY,
        'Security Operations': SECURITY_AND_PRIVACY_GOVERNANCE,
        'Security Awareness & Training': 'HR Governance',
        'Technology Development & Acquisition': ASSET_MANAGEMENT,
        'Web Security': SYSTEM_NETWORK_AND_CLOUD_SECURITY,
    }

    for category, pillar_name in category_to_pillar.items():
        try:
            pillar_instance = pillar.objects.get(name=pillar_name)
            control.objects.filter(category__contains=category).update(
                pillar=pillar_instance
            )
        except Exception as e:
            logger.exception(
                f'Error when applying migration 0018_categories_to_pillars {e}. '
                f'ControlPillar with name {pillar_name} does not exist'
            )


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0014_add_control_pillars'),
        ('control', '0018_add_controlpillar_name_choices'),
    ]

    operations = [migrations.RunPython(map_control_categories_to_pillar_names)]
