# Generated by Django 3.1.12 on 2021-07-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0008_update_content_comments'),
        ('control', '0019_categories_to_pillars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={
                'permissions': [
                    ('batch_delete_control', 'Can batch delete controls'),
                    ('change_control_status', 'Can change control status'),
                    ('associate_user', 'Can associate user to control'),
                    ('add_control_evidence', 'Can add control evidence'),
                    ('delete_control_evidence', 'Can delete control evidence'),
                    ('add_control_comment', 'Can add control comment'),
                    ('change_control_comment', 'Can change control comment'),
                    ('delete_control_comment', 'Can delete control comment'),
                    ('view_control_comment', 'Can view control comment'),
                ]
            },
        ),
        migrations.CreateModel(
            name='ControlComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='control',
                        to='comment.comment',
                    ),
                ),
                (
                    'control',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='control_comments',
                        to='control.control',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='comments',
            field=models.ManyToManyField(
                related_name='controls',
                through='control.ControlComment',
                to='comment.Comment',
            ),
        ),
    ]
