# Generated by Django 3.1.12 on 2021-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0020_add_comments_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='reference_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
