# Generated by Django 3.1.12 on 2021-08-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0021_adding_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
