# Generated by Django 3.1.12 on 2021-08-25 14:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0023_update_control_comment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationguide',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
