# Generated by Django 3.1.12 on 2021-09-02 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0024_using_tinymce_HTMLField'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={
                'permissions': [
                    ('batch_delete_control', 'Can batch delete controls'),
                    ('change_control_status', 'Can change control status'),
                    ('associate_user', 'Can associate user to control'),
                    ('add_control_evidence', 'Can add control evidence'),
                    ('delete_control_evidence', 'Can delete control evidence'),
                ]
            },
        ),
    ]
