# Generated by Django 3.1.12 on 2021-09-02 21:50

from django.db import migrations


def add_default_permissions_control_comments(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    control_comment_permissions = Permission.objects.filter(
        codename__in=[
            'add_controlcomment',
            'change_controlcomment',
            'delete_controlcomment',
            'view_controlcomment',
        ]
    )
    groups = [
        'premium_super',
        'premium_admin',
        'premium_member',
    ]
    for group in Group.objects.filter(name__in=groups):
        for permission in control_comment_permissions:
            group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0025_remove_control_manual_permissions'),
    ]

    operations = [migrations.RunPython(add_default_permissions_control_comments)]
