# Generated by Django 3.1.12 on 2021-10-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('action_item', '0002_adding_metadata_action_item'),
        ('control', '0026_add_default_permission_control_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='action_items',
            field=models.ManyToManyField(
                related_name='controls', to='action_item.ActionItem'
            ),
        ),
    ]
