# Generated by Django 3.1.12 on 2021-10-14 14:49

from django.db import migrations


def add_default_permissions_for_control_action_item(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    archived_permissions = Permission.objects.filter(
        codename__in=[
            'add_controlactionitem',
            'change_controlactionitem',
            'delete_controlactionitem',
            'view_controlactionitem',
        ]
    )

    groups = [
        'premium_super',
        'premium_admin',
        'premium_member',
    ]

    for group in Group.objects.filter(name__in=groups):
        for permission in archived_permissions:
            group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0027_control_action_items'),
    ]

    operations = [migrations.RunPython(add_default_permissions_for_control_action_item)]
