# Generated by Django 3.1.12 on 2021-10-25 21:20

from django.db import migrations


def allow_add_control_only_for_premium_super(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')

    permissions = permission.objects.filter(codename='add_control')

    for group in group.objects.all().exclude(name='premium_super'):
        group.permissions.remove(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0029_add_actionitem_permissions_to_control_mutation'),
    ]

    operations = [migrations.RunPython(allow_add_control_only_for_premium_super)]
