# Generated by Django 3.1.12 on 2021-10-28 16:23

from django.db import migrations


def allow_add_control_for_premium_admin(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')

    permissions = permission.objects.filter(codename='add_control')

    for group in group.objects.filter(name='premium_admin'):
        group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0030_create_control_permissions'),
    ]

    operations = [migrations.RunPython(allow_add_control_for_premium_admin)]
