# Generated by Django 3.1.12 on 2021-11-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0062_change_checklist_date_to_null'),
        ('control', '0031_add_control_for_premium_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='roadmap',
                        to='organization.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ControlGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('sort_order', models.IntegerField()),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='control_groups',
                        to='organization.organization',
                    ),
                ),
                (
                    'roadmap',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='groups',
                        to='control.roadmap',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='controls',
                to='control.controlgroup',
            ),
        ),
    ]
