# Generated by Django 3.1.12 on 2021-11-16 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0032_add_road_map_and_control_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlgroup',
            name='organization',
        ),
    ]
