# Generated by Django 3.1.12 on 2021-11-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0033_remove_control_group_organization_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='has_new_action_items',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
