# Generated by Django 3.1.12 on 2021-11-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0034_add_flag_new_action_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlgroup',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
