# Generated by Django 3.1.12 on 2021-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0035_controlgroup_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='group',
        ),
        migrations.AddField(
            model_name='controlgroup',
            name='controls',
            field=models.ManyToManyField(related_name='group', to='control.Control'),
        ),
    ]
