# Generated by Django 3.1.12 on 2021-11-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0036_change_control_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlgroup',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
