# Generated by Django 3.1.12 on 2022-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0037_change_due_date_specificity'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpillar',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='controlpillar',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
