# Generated by Django 3.1.12 on 2022-01-12 18:21

from django.db import migrations


def allow_roadmap_actions_for_premium_admin_contributor(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permissions = Permission.objects.filter(
        codename__in=['change_roadmap', 'view_roadmap']
    )

    groups = ['premium_super', 'premium_admin', 'premium_member']

    for group in Group.objects.all():
        group.permissions.remove(*permissions)

    for group in Group.objects.filter(name__in=groups):
        for permission in permissions:
            group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0038_pillar_change_name_add_acronym'),
    ]

    operations = [
        migrations.RunPython(
            allow_roadmap_actions_for_premium_admin_contributor,
            reverse_code=migrations.RunPython.noop,
        )
    ]
