# Generated by Django 3.1.12 on 2022-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0039_create_roadmap_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='implementation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
