# Generated by Django 3.2.13 on 2022-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0041_create_permission_for_mycompliance_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='household',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
