# Generated by Django 3.2.13 on 2022-07-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blueprint', '0039_alter_implementationguideblueprint_options'),
        ('control', '0042_control_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='implementation_guide_blueprint',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_controls',
                to='blueprint.implementationguideblueprint',
            ),
        ),
    ]
