# Generated by Django 3.2.13 on 2022-07-12 17:35

from django.db import migrations


def copy_implementation_guide_values(apps, schema_editor):
    Control = apps.get_model('control', 'Control')
    ImplementationGuideBlueprint = apps.get_model(
        'blueprint', 'ImplementationGuideBlueprint'
    )
    for control in Control.objects.filter(implementation_guide__isnull=False):
        guide = ImplementationGuideBlueprint.objects.filter(
            name=control.implementation_guide.name
        ).first()

        if guide:
            control.implementation_guide_blueprint = guide
            control.save()


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0043_control_implementation_guide_blueprint'),
    ]

    operations = [migrations.RunPython(copy_implementation_guide_values)]
