# Generated by Django 3.2.13 on 2022-07-12 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0045_remove_control_implementation_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImplementationGuide',
        ),
    ]
