# Generated by Django 3.2.15 on 2022-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0047_add_start_date_to_control_group_and_action_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='display_id',
            field=models.IntegerField(default=9999999),
        ),
    ]
