# Generated by Django 3.2.15 on 2022-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('control', '0048_alter_control_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='framework_tag',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
