# Generated by Django 3.0.2 on 2020-01-23 17:06

import django.db.models.deletion
from django.db import migrations, models

import training.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                (
                    'category',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Asset Management', 'Asset Management'),
                            (
                                'Business Continuity & Disaster Recovery',
                                'Business Continuity & Disaster Recovery',
                            ),
                            (
                                'Capacity & Performance Planning',
                                'Capacity & Performance Planning',
                            ),
                            ('Change Management', 'Change Management'),
                            ('Compliance', 'Compliance'),
                            ('Configuration Management', 'Configuration Management'),
                            ('Cryptographic Protections', 'Cryptographic Protections'),
                            (
                                'Data Classification & Handling',
                                'Data Classification & Handling',
                            ),
                            ('Endpoint Security', 'Endpoint Security'),
                            ('Human Resources Security', 'Human Resources Security'),
                            (
                                'Identification & Authentication',
                                'Identification & Authentication',
                            ),
                            ('Incident Response', 'Incident Response'),
                            ('Information Assurance', 'Information Assurance'),
                            ('Mobile Device Management', 'Mobile Device Management'),
                            ('Monitoring', 'Monitoring'),
                            ('Network Security', 'Network Security'),
                            (
                                'Physical & Environmental Security',
                                'Physical & Environmental Security',
                            ),
                            ('Privacy', 'Privacy'),
                            (
                                'Project & Resource Management',
                                'Project & Resource Management',
                            ),
                            ('Risk Management', 'Risk Management'),
                            (
                                'Secure Engineering & Architecture',
                                'Secure Engineering & Architecture',
                            ),
                            (
                                'Security & Privacy Governance',
                                'Security & Privacy Governance',
                            ),
                            (
                                'Security Awareness & Training',
                                'Security Awareness & Training',
                            ),
                            ('Security Operations', 'Security Operations'),
                            (
                                'Technology Development & Acquisition',
                                'Technology Development & Acquisition',
                            ),
                            ('Third-Party Management', 'Third-Party Management'),
                            ('Threat Management', 'Threat Management'),
                            (
                                'Vulnerability & Patch Management',
                                'Vulnerability & Patch Management',
                            ),
                            ('Other', 'Other'),
                        ],
                        default='',
                        max_length=100,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                (
                    'slides',
                    models.FileField(
                        blank=True,
                        upload_to=training.models.training_file_directory_path,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organization.Organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alumni',
                        to='training.Training',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'alumni',
            },
        ),
    ]
