# Generated by Django 3.0.2 on 2020-02-04 17:55

from django.db import migrations, models

import laika.storage
import training.models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0002_alumni_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='slides',
            field=models.FileField(
                blank=True,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=training.models.training_file_directory_path,
            ),
        ),
    ]
