# Generated by Django 3.0.2 on 2020-02-04 19:00

from django.db import migrations, models

import laika.storage
import training.models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0003_auto_20200204_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='slides',
            field=models.FileField(
                blank=True,
                max_length=512,
                storage=laika.storage.PrivateMediaStorage(),
                upload_to=training.models.training_file_directory_path,
            ),
        ),
    ]
