# Generated by Django 3.0.2 on 2020-02-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0004_increase_training_filename_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
