# Generated by Django 3.0.2 on 2020-02-12 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0005_freeze_alumni_information'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            UPDATE training_alumni AS ta
            SET first_name = uu.first_name,
                last_name = uu.last_name,
                email = uu.email 
            FROM user_user AS uu
            WHERE ta.user_id = uu.id 
        '''
        )
    ]
