# Generated by Django 3.0.3 on 2020-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0006_backfill_alumni_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Asset Management', 'Asset Management'),
                    (
                        'Business Continuity & Disaster Recovery',
                        'Business Continuity & Disaster Recovery',
                    ),
                    (
                        'Capacity & Performance Planning',
                        'Capacity & Performance Planning',
                    ),
                    ('Change Management', 'Change Management'),
                    ('Cloud Security', 'Cloud Security'),
                    ('Compliance', 'Compliance'),
                    ('Configuration Management', 'Configuration Management'),
                    ('Cryptographic Protections', 'Cryptographic Protections'),
                    (
                        'Data Classification & Handling',
                        'Data Classification & Handling',
                    ),
                    ('Embedded Technology', 'Embedded Technology'),
                    ('Endpoint Security', 'Endpoint Security'),
                    ('Human Resources Security', 'Human Resources Security'),
                    (
                        'Identification & Authentication',
                        'Identification & Authentication',
                    ),
                    ('Incident Response', 'Incident Response'),
                    ('Information Assurance', 'Information Assurance'),
                    ('Maintenance', 'Maintenance'),
                    ('Mobile Device Management', 'Mobile Device Management'),
                    ('Monitoring', 'Monitoring'),
                    ('Network Security', 'Network Security'),
                    (
                        'Physical & Environmental Security',
                        'Physical & Environmental Security',
                    ),
                    ('Privacy', 'Privacy'),
                    ('Project & Resource Management', 'Project & Resource Management'),
                    ('Risk Management', 'Risk Management'),
                    (
                        'Secure Engineering & Architecture',
                        'Secure Engineering & Architecture',
                    ),
                    ('Security & Privacy Governance', 'Security & Privacy Governance'),
                    ('Security Awareness & Training', 'Security Awareness & Training'),
                    ('Security Operations', 'Security Operations'),
                    (
                        'Technology Development & Acquisition',
                        'Technology Development & Acquisition',
                    ),
                    ('Third-Party Management', 'Third-Party Management'),
                    ('Threat Management', 'Threat Management'),
                    (
                        'Vulnerability & Patch Management',
                        'Vulnerability & Patch Management',
                    ),
                    ('Web Security', 'Web Security'),
                    ('Other', 'Other'),
                ],
                default='',
                max_length=100,
            ),
        ),
    ]
