# Generated by Django 3.0.3 on 2020-04-21 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0007_auto_20200325_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='training',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='alumni',
                to='training.Training',
            ),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trainings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
