# Generated by Django 3.0.7 on 2020-07-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0008_auto_20200421_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
