# Generated by Django 3.1.2 on 2021-02-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0009_DateTimeField_instead_of_DateField'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='training_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='training_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='training',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='alumni',
                to='training.training',
            ),
        ),
    ]
