# Generated by Django 3.1.6 on 2021-04-20 20:41

from django.db import migrations


class Migration(migrations.Migration):
    def populate_training_assignee(apps, schema):
        training_model = apps.get_model('training', 'Training')
        training_assignee_model = apps.get_model('training', 'TrainingAssignee')
        user_model = apps.get_model('user', 'User')

        trainings = training_model.objects.filter(
            name='Laika Security Awareness and Incident Response Training'
        )

        for training in trainings:
            organization_id = training.organization.id
            users = user_model.objects.filter(organization=organization_id)

            for user in users:
                training_assignee_model.objects.create(user=user, training=training)

    dependencies = [
        ('training', '0012_training_assignee'),
    ]

    operations = [
        migrations.RunPython(populate_training_assignee),
    ]
