# Generated by Django 3.1.6 on 2021-06-25 16:55
import json

from django.db import migrations, models


class Migration(migrations.Migration):
    def update_training_roles(apps, schema_editor):
        training_model = apps.get_model("training", "Training")
        for training in training_model.objects.all():
            training.roles = [
                "OrganizationAdmin",
                "OrganizationMember",
                "OrganizationSales",
                "OrganizationViewer",
            ]
            training.save()

    dependencies = [
        ('training', '0013_populate_training_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='roles',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(update_training_roles),
    ]
