# Generated by Django 3.1.6 on 2021-07-05 18:14

from django.db import migrations, models

import training.models


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0014_training_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='roles',
            field=models.JSONField(default=training.models.generate_default_roles),
        ),
    ]
